// Code generated by scripts/gen_damagetags.py. DO NOT EDIT.

package server

// dmgTag is one vanilla damage-type tag, as a bit. The tags answer the
// questions the damage pipeline asks of every hit — whether armour absorbs
// it, whether a shield stops it, which protection enchantment guards it.
type dmgTag uint64

const (
	tagAlwaysHurtsEnderDragons dmgTag = 1 << iota
	tagAlwaysKillsArmorStands
	tagAlwaysMostSignificantFall
	tagAlwaysTriggersSilverfish
	tagAvoidsGuardianThorns
	tagBurnFromStepping
	tagBurnsArmorStands
	tagBypassesArmor
	tagBypassesEffects
	tagBypassesEnchantments
	tagBypassesInvulnerability
	tagBypassesResistance
	tagBypassesShield
	tagBypassesWolfArmor
	tagCanBreakArmorStand
	tagDamagesHelmet
	tagIgnitesArmorStands
	tagIsDrowning
	tagIsExplosion
	tagIsFall
	tagIsFire
	tagIsFreezing
	tagIsLightning
	tagIsPlayerAttack
	tagIsProjectile
	tagMaceSmash
	tagNoAnger
	tagNoImpact
	tagNoKnockback
	tagPanicCauses
	tagPanicEnvironmentalCauses
	tagWitchResistantTo
	tagWitherImmuneTo
)

// dmgType names one vanilla damage type. The type travels with the damage
// from wherever it was dealt, because by the time a hit reaches the armour
// there is no way to tell a lava burn from a starving stomach.
type dmgType uint8

const (
	dtArrow dmgType = iota
	dtBadRespawnPoint
	dtCactus
	dtCampfire
	dtCramming
	dtDragonBreath
	dtDrown
	dtDryOut
	dtEnderPearl
	dtExplosion
	dtFall
	dtFallingAnvil
	dtFallingBlock
	dtFallingStalactite
	dtFireball
	dtFireworks
	dtFlyIntoWall
	dtFreeze
	dtGeneric
	dtGenericKill
	dtHotFloor
	dtInFire
	dtInWall
	dtIndirectMagic
	dtLava
	dtLightningBolt
	dtMaceSmash
	dtMagic
	dtMobAttack
	dtMobAttackNoAggro
	dtMobProjectile
	dtOnFire
	dtOutOfWorld
	dtOutsideBorder
	dtPlayerAttack
	dtPlayerExplosion
	dtSonicBoom
	dtSpear
	dtSpit
	dtStalagmite
	dtStarve
	dtSting
	dtSweetBerryBush
	dtThorns
	dtThrown
	dtTrident
	dtUnattributedFireball
	dtWindCharge
	dtWither
	dtWitherSkull
)

// dmgTypeNames is the registry name of each damage type, for diagnostics.
var dmgTypeNames = [...]string{
	dtArrow:                "arrow",
	dtBadRespawnPoint:      "bad_respawn_point",
	dtCactus:               "cactus",
	dtCampfire:             "campfire",
	dtCramming:             "cramming",
	dtDragonBreath:         "dragon_breath",
	dtDrown:                "drown",
	dtDryOut:               "dry_out",
	dtEnderPearl:           "ender_pearl",
	dtExplosion:            "explosion",
	dtFall:                 "fall",
	dtFallingAnvil:         "falling_anvil",
	dtFallingBlock:         "falling_block",
	dtFallingStalactite:    "falling_stalactite",
	dtFireball:             "fireball",
	dtFireworks:            "fireworks",
	dtFlyIntoWall:          "fly_into_wall",
	dtFreeze:               "freeze",
	dtGeneric:              "generic",
	dtGenericKill:          "generic_kill",
	dtHotFloor:             "hot_floor",
	dtInFire:               "in_fire",
	dtInWall:               "in_wall",
	dtIndirectMagic:        "indirect_magic",
	dtLava:                 "lava",
	dtLightningBolt:        "lightning_bolt",
	dtMaceSmash:            "mace_smash",
	dtMagic:                "magic",
	dtMobAttack:            "mob_attack",
	dtMobAttackNoAggro:     "mob_attack_no_aggro",
	dtMobProjectile:        "mob_projectile",
	dtOnFire:               "on_fire",
	dtOutOfWorld:           "out_of_world",
	dtOutsideBorder:        "outside_border",
	dtPlayerAttack:         "player_attack",
	dtPlayerExplosion:      "player_explosion",
	dtSonicBoom:            "sonic_boom",
	dtSpear:                "spear",
	dtSpit:                 "spit",
	dtStalagmite:           "stalagmite",
	dtStarve:               "starve",
	dtSting:                "sting",
	dtSweetBerryBush:       "sweet_berry_bush",
	dtThorns:               "thorns",
	dtThrown:               "thrown",
	dtTrident:              "trident",
	dtUnattributedFireball: "unattributed_fireball",
	dtWindCharge:           "wind_charge",
	dtWither:               "wither",
	dtWitherSkull:          "wither_skull",
}

// dmgTypeTags is the tag set of each damage type.
var dmgTypeTags = [...]dmgTag{
	dtArrow:                tagAlwaysKillsArmorStands | tagIsProjectile | tagPanicCauses,
	dtBadRespawnPoint:      tagAlwaysHurtsEnderDragons | tagAvoidsGuardianThorns | tagIsExplosion | tagNoKnockback,
	dtCactus:               tagBypassesShield | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtCampfire:             tagBurnFromStepping | tagBypassesShield | tagIgnitesArmorStands | tagIsFire | tagNoKnockback,
	dtCramming:             tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtDragonBreath:         tagBypassesArmor | tagBypassesShield | tagNoKnockback | tagPanicCauses,
	dtDrown:                tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagIsDrowning | tagNoImpact | tagNoKnockback | tagWitherImmuneTo,
	dtDryOut:               tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtEnderPearl:           tagBypassesArmor | tagBypassesShield | tagIsFall | tagNoKnockback,
	dtExplosion:            tagAlwaysHurtsEnderDragons | tagAvoidsGuardianThorns | tagIsExplosion | tagNoKnockback | tagPanicCauses,
	dtFall:                 tagBypassesArmor | tagBypassesShield | tagIsFall | tagNoKnockback,
	dtFallingAnvil:         tagBypassesShield | tagDamagesHelmet,
	dtFallingBlock:         tagDamagesHelmet,
	dtFallingStalactite:    tagBypassesShield | tagDamagesHelmet,
	dtFireball:             tagAlwaysKillsArmorStands | tagIsFire | tagIsProjectile | tagPanicCauses,
	dtFireworks:            tagAlwaysHurtsEnderDragons | tagAvoidsGuardianThorns | tagIsExplosion | tagPanicCauses,
	dtFlyIntoWall:          tagBypassesArmor | tagBypassesShield | tagNoKnockback,
	dtFreeze:               tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagIsFreezing | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtGeneric:              tagBypassesArmor | tagBypassesShield | tagNoKnockback,
	dtGenericKill:          tagBypassesArmor | tagBypassesInvulnerability | tagBypassesResistance | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtHotFloor:             tagBurnFromStepping | tagBypassesShield | tagIsFire | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtInFire:               tagBypassesShield | tagIgnitesArmorStands | tagIsFire | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtInWall:               tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtIndirectMagic:        tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagPanicCauses | tagWitchResistantTo,
	dtLava:                 tagBypassesShield | tagIsFire | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtLightningBolt:        tagBypassesShield | tagIsLightning | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtMaceSmash:            tagCanBreakArmorStand | tagIsPlayerAttack | tagMaceSmash | tagPanicCauses,
	dtMagic:                tagAlwaysTriggersSilverfish | tagAvoidsGuardianThorns | tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback | tagPanicCauses | tagWitchResistantTo,
	dtMobAttack:            tagPanicCauses,
	dtMobAttackNoAggro:     tagNoAnger,
	dtMobProjectile:        tagIsProjectile | tagPanicCauses,
	dtOnFire:               tagBurnsArmorStands | tagBypassesArmor | tagBypassesShield | tagIsFire | tagNoKnockback | tagPanicCauses | tagPanicEnvironmentalCauses,
	dtOutOfWorld:           tagAlwaysMostSignificantFall | tagBypassesArmor | tagBypassesInvulnerability | tagBypassesResistance | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtOutsideBorder:        tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtPlayerAttack:         tagCanBreakArmorStand | tagIsPlayerAttack | tagPanicCauses,
	dtPlayerExplosion:      tagAlwaysHurtsEnderDragons | tagAvoidsGuardianThorns | tagCanBreakArmorStand | tagIsExplosion | tagNoKnockback | tagPanicCauses,
	dtSonicBoom:            tagBypassesArmor | tagBypassesEnchantments | tagBypassesShield | tagPanicCauses | tagWitchResistantTo,
	dtSpear:                tagCanBreakArmorStand | tagIsPlayerAttack | tagNoKnockback | tagPanicCauses,
	dtStalagmite:           tagBypassesArmor | tagBypassesShield | tagIsFall | tagNoKnockback,
	dtStarve:               tagBypassesArmor | tagBypassesEffects | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback,
	dtSting:                tagPanicCauses,
	dtSweetBerryBush:       tagBypassesShield | tagNoKnockback,
	dtThorns:               tagAvoidsGuardianThorns | tagBypassesWolfArmor | tagWitchResistantTo,
	dtThrown:               tagIsProjectile | tagPanicCauses,
	dtTrident:              tagAlwaysKillsArmorStands | tagIsProjectile | tagPanicCauses,
	dtUnattributedFireball: tagIsFire | tagIsProjectile | tagPanicCauses,
	dtWindCharge:           tagAlwaysKillsArmorStands | tagIsProjectile | tagPanicCauses,
	dtWither:               tagBypassesArmor | tagBypassesShield | tagBypassesWolfArmor | tagNoKnockback | tagPanicCauses,
	dtWitherSkull:          tagAlwaysKillsArmorStands | tagIsProjectile | tagPanicCauses,
}

// dmgTypeExhaustion is the food exhaustion each damage type costs, which
// is a property of the type in vanilla and so belongs here rather than at
// the ~20 places that deal damage. Types absent from this table cost
// nothing (the vanilla default is 0.0).
var dmgTypeExhaustion = [...]float32{
	dtArrow:                0.1,
	dtBadRespawnPoint:      0.1,
	dtCactus:               0.1,
	dtCampfire:             0.1,
	dtDryOut:               0.1,
	dtExplosion:            0.1,
	dtFallingAnvil:         0.1,
	dtFallingBlock:         0.1,
	dtFallingStalactite:    0.1,
	dtFireball:             0.1,
	dtFireworks:            0.1,
	dtHotFloor:             0.1,
	dtInFire:               0.1,
	dtLava:                 0.1,
	dtLightningBolt:        0.1,
	dtMaceSmash:            0.1,
	dtMobAttack:            0.1,
	dtMobAttackNoAggro:     0.1,
	dtMobProjectile:        0.1,
	dtPlayerAttack:         0.1,
	dtPlayerExplosion:      0.1,
	dtSpear:                0.1,
	dtSpit:                 0.1,
	dtSting:                0.1,
	dtSweetBerryBush:       0.1,
	dtThorns:               0.1,
	dtThrown:               0.1,
	dtTrident:              0.1,
	dtUnattributedFireball: 0.1,
	dtWindCharge:           0.1,
	dtWitherSkull:          0.1,
}
