// Code generated by scripts/gen_dyecolors.py; DO NOT EDIT.

package server

// dyeFireworkColor is the colour a dye contributes to a firework star
// (DyeColor.getFireworkColor) — not the dye's own text or map colour.
// Indexed by the DyeColor id, which is what the wire and the loom use.

var dyeFireworkColor = [16]int32{
	0xF0F0F0, // 0 white
	0xEB8844, // 1 orange
	0xC354CD, // 2 magenta
	0x6689D3, // 3 light_blue
	0xDECF2A, // 4 yellow
	0x41CD34, // 5 lime
	0xD88198, // 6 pink
	0x434343, // 7 gray
	0xABABAB, // 8 light_gray
	0x287697, // 9 cyan
	0x7B2FBE, // 10 purple
	0x253192, // 11 blue
	0x51301A, // 12 brown
	0x3B511A, // 13 green
	0xB3312C, // 14 red
	0x1E1B1B, // 15 black
}
