// Code generated by scripts/gen_effectcolors.py; DO NOT EDIT.

package server

// effectColor is each effect's particle/liquid colour as vanilla registers
// it in MobEffects. A potion's colour is the mix of the effects it carries
// (PotionContents.getColor), and without these every potion renders the
// default purple.

var effectColorByName = map[string]int32{
	"absorption":             0x2552A5, // beneficial
	"bad_omen":               0x0B6138, // neutral
	"blindness":              0x1F1F23, // harmful
	"breath_of_the_nautilus": 0x00FFEE, // beneficial
	"conduit_power":          0x1DC2D1, // beneficial
	"darkness":               0x292721, // harmful
	"dolphins_grace":         0x88A3BE, // beneficial
	"fire_resistance":        0xFF9900, // beneficial
	"glowing":                0x94A061, // neutral
	"haste":                  0xD9C043, // beneficial
	"health_boost":           0xF87D23, // beneficial
	"hero_of_the_village":    0x44FF44, // beneficial
	"hunger":                 0x587653, // harmful
	"infested":               0x8C9B8C, // harmful
	"instant_damage":         0xA9656A, // harmful
	"instant_health":         0xF82423, // beneficial
	"invisibility":           0xF6F6F6, // beneficial
	"jump_boost":             0xFDFF84, // beneficial
	"levitation":             0xCEFFFF, // harmful
	"luck":                   0x59C106, // beneficial
	"mining_fatigue":         0x4A4217, // harmful
	"nausea":                 0x551D4A, // harmful
	"night_vision":           0xC2FF66, // beneficial
	"oozing":                 0x99FFA3, // harmful
	"poison":                 0x87A363, // harmful
	"raid_omen":              0xDE4058, // neutral
	"regeneration":           0xCD5CAB, // beneficial
	"resistance":             0x9146F0, // beneficial
	"saturation":             0xF82423, // beneficial
	"slow_falling":           0xF3CFB9, // beneficial
	"slowness":               0x8BAFE0, // harmful
	"speed":                  0x33EBFF, // beneficial
	"strength":               0xFFC700, // beneficial
	"trial_omen":             0x16A6A6, // neutral
	"unluck":                 0xC0A44D, // harmful
	"water_breathing":        0x98DAC0, // beneficial
	"weakness":               0x484D48, // harmful
	"weaving":                0x78695A, // harmful
	"wind_charged":           0xBDC9FF, // harmful
	"wither":                 0x736156, // harmful
}
