// Code generated by scripts/gen_foods.py; DO NOT EDIT.

package server

// foodPoints maps an edible item id to the hunger points eating it restores.
var foodPoints = map[int32]int{
	1007: 4,  // apple
	1061: 6,  // mushroom_stew
	1067: 5,  // bread
	1097: 3,  // porkchop
	1098: 8,  // cooked_porkchop
	1100: 4,  // golden_apple
	1101: 4,  // enchanted_golden_apple
	1135: 1,  // pufferfish_bucket
	1136: 2,  // salmon_bucket
	1137: 2,  // cod_bucket
	1138: 1,  // tropical_fish_bucket
	1190: 2,  // cod
	1191: 2,  // salmon
	1192: 1,  // tropical_fish
	1193: 1,  // pufferfish
	1194: 5,  // cooked_cod
	1195: 6,  // cooked_salmon
	1236: 2,  // cookie
	1256: 2,  // melon_slice
	1257: 1,  // dried_kelp
	1260: 3,  // beef
	1261: 8,  // cooked_beef
	1262: 2,  // chicken
	1263: 6,  // cooked_chicken
	1264: 4,  // rotten_flesh
	1272: 2,  // spider_eye
	1378: 3,  // carrot
	1379: 1,  // potato
	1380: 5,  // baked_potato
	1381: 2,  // poisonous_potato
	1383: 6,  // golden_carrot
	1392: 8,  // pumpkin_pie
	1400: 3,  // rabbit
	1401: 5,  // cooked_rabbit
	1402: 10, // rabbit_stew
	1415: 2,  // mutton
	1416: 6,  // cooked_mutton
	1434: 4,  // chorus_fruit
	1438: 1,  // beetroot
	1440: 6,  // beetroot_soup
	1492: 6,  // suspicious_stew
	1525: 2,  // sweet_berries
	1526: 2,  // glow_berries
	1533: 6,  // honey_bottle
}

// foodSaturation maps an edible item id to the saturation eating it restores
// (vanilla: foodPoints × saturationModifier × 2).
var foodSaturation = map[int32]float32{
	1007: 2.4,  // apple
	1061: 7.2,  // mushroom_stew
	1067: 6,    // bread
	1097: 1.8,  // porkchop
	1098: 12.8, // cooked_porkchop
	1100: 9.6,  // golden_apple
	1101: 9.6,  // enchanted_golden_apple
	1135: 0.2,  // pufferfish_bucket
	1136: 0.4,  // salmon_bucket
	1137: 0.4,  // cod_bucket
	1138: 0.2,  // tropical_fish_bucket
	1190: 0.4,  // cod
	1191: 0.4,  // salmon
	1192: 0.2,  // tropical_fish
	1193: 0.2,  // pufferfish
	1194: 6,    // cooked_cod
	1195: 9.6,  // cooked_salmon
	1236: 0.4,  // cookie
	1256: 1.2,  // melon_slice
	1257: 0.6,  // dried_kelp
	1260: 1.8,  // beef
	1261: 12.8, // cooked_beef
	1262: 1.2,  // chicken
	1263: 7.2,  // cooked_chicken
	1264: 0.8,  // rotten_flesh
	1272: 3.2,  // spider_eye
	1378: 3.6,  // carrot
	1379: 0.6,  // potato
	1380: 6,    // baked_potato
	1381: 1.2,  // poisonous_potato
	1383: 14.4, // golden_carrot
	1392: 4.8,  // pumpkin_pie
	1400: 1.8,  // rabbit
	1401: 6,    // cooked_rabbit
	1402: 12,   // rabbit_stew
	1415: 1.2,  // mutton
	1416: 9.6,  // cooked_mutton
	1434: 2.4,  // chorus_fruit
	1438: 1.2,  // beetroot
	1440: 7.2,  // beetroot_soup
	1492: 7.2,  // suspicious_stew
	1525: 0.4,  // sweet_berries
	1526: 0.4,  // glow_berries
	1533: 1.2,  // honey_bottle
}
