// Code generated by scripts/gen_foods.py; DO NOT EDIT.

package server

// foodPoints maps an edible item id to the hunger points eating it restores.
var foodPoints = map[int32]int{
	893:  4,  // apple
	947:  6,  // mushroom_stew
	953:  5,  // bread
	983:  3,  // porkchop
	984:  8,  // cooked_porkchop
	986:  4,  // golden_apple
	987:  4,  // enchanted_golden_apple
	1019: 1,  // pufferfish_bucket
	1020: 2,  // salmon_bucket
	1021: 2,  // cod_bucket
	1022: 1,  // tropical_fish_bucket
	1057: 2,  // cod
	1058: 2,  // salmon
	1059: 1,  // tropical_fish
	1060: 1,  // pufferfish
	1061: 5,  // cooked_cod
	1062: 6,  // cooked_salmon
	1102: 2,  // cookie
	1106: 2,  // melon_slice
	1107: 1,  // dried_kelp
	1110: 3,  // beef
	1111: 8,  // cooked_beef
	1112: 2,  // chicken
	1113: 6,  // cooked_chicken
	1114: 4,  // rotten_flesh
	1122: 2,  // spider_eye
	1227: 3,  // carrot
	1228: 1,  // potato
	1229: 5,  // baked_potato
	1230: 2,  // poisonous_potato
	1232: 6,  // golden_carrot
	1241: 8,  // pumpkin_pie
	1249: 3,  // rabbit
	1250: 5,  // cooked_rabbit
	1251: 10, // rabbit_stew
	1264: 2,  // mutton
	1265: 6,  // cooked_mutton
	1283: 4,  // chorus_fruit
	1287: 1,  // beetroot
	1289: 6,  // beetroot_soup
	1340: 6,  // suspicious_stew
	1373: 2,  // sweet_berries
	1374: 2,  // glow_berries
	1381: 6,  // honey_bottle
}

// foodSaturation maps an edible item id to the saturation eating it restores
// (vanilla: foodPoints × saturationModifier × 2).
var foodSaturation = map[int32]float32{
	893:  2.4,  // apple
	947:  7.2,  // mushroom_stew
	953:  6,    // bread
	983:  1.8,  // porkchop
	984:  12.8, // cooked_porkchop
	986:  9.6,  // golden_apple
	987:  9.6,  // enchanted_golden_apple
	1019: 0.2,  // pufferfish_bucket
	1020: 0.4,  // salmon_bucket
	1021: 0.4,  // cod_bucket
	1022: 0.2,  // tropical_fish_bucket
	1057: 0.4,  // cod
	1058: 0.4,  // salmon
	1059: 0.2,  // tropical_fish
	1060: 0.2,  // pufferfish
	1061: 6,    // cooked_cod
	1062: 9.6,  // cooked_salmon
	1102: 0.4,  // cookie
	1106: 1.2,  // melon_slice
	1107: 0.6,  // dried_kelp
	1110: 1.8,  // beef
	1111: 12.8, // cooked_beef
	1112: 1.2,  // chicken
	1113: 7.2,  // cooked_chicken
	1114: 0.8,  // rotten_flesh
	1122: 3.2,  // spider_eye
	1227: 3.6,  // carrot
	1228: 0.6,  // potato
	1229: 6,    // baked_potato
	1230: 1.2,  // poisonous_potato
	1232: 14.4, // golden_carrot
	1241: 4.8,  // pumpkin_pie
	1249: 1.8,  // rabbit
	1250: 6,    // cooked_rabbit
	1251: 12,   // rabbit_stew
	1264: 1.2,  // mutton
	1265: 9.6,  // cooked_mutton
	1283: 2.4,  // chorus_fruit
	1287: 1.2,  // beetroot
	1289: 7.2,  // beetroot_soup
	1340: 7.2,  // suspicious_stew
	1373: 0.4,  // sweet_berries
	1374: 0.4,  // glow_berries
	1381: 1.2,  // honey_bottle
}
