// Code generated by scripts/gen_durability.py — DO NOT EDIT.
// Source: the game's own item components, via scripts/extract.
// (armor points/toughness are vanilla constants hand-coded in the script).

package server

// itemMaxDurability: item id -> max durability. An item is wearable-out
// iff it has an entry here.
var itemMaxDurability = map[int32]int{
	971:  25,   // carrot_on_a_stick
	972:  100,  // warped_fungus_on_a_stick
	974:  432,  // elytra
	1001: 275,  // turtle_helmet
	1004: 64,   // wolf_armor
	1005: 64,   // flint_and_steel
	1008: 384,  // bow
	1025: 59,   // wooden_sword
	1026: 59,   // wooden_shovel
	1027: 59,   // wooden_pickaxe
	1028: 59,   // wooden_axe
	1029: 59,   // wooden_hoe
	1030: 190,  // copper_sword
	1031: 190,  // copper_shovel
	1032: 190,  // copper_pickaxe
	1033: 190,  // copper_axe
	1034: 190,  // copper_hoe
	1035: 131,  // stone_sword
	1036: 131,  // stone_shovel
	1037: 131,  // stone_pickaxe
	1038: 131,  // stone_axe
	1039: 131,  // stone_hoe
	1040: 32,   // golden_sword
	1041: 32,   // golden_shovel
	1042: 32,   // golden_pickaxe
	1043: 32,   // golden_axe
	1044: 32,   // golden_hoe
	1045: 250,  // iron_sword
	1046: 250,  // iron_shovel
	1047: 250,  // iron_pickaxe
	1048: 250,  // iron_axe
	1049: 250,  // iron_hoe
	1050: 1561, // diamond_sword
	1051: 1561, // diamond_shovel
	1052: 1561, // diamond_pickaxe
	1053: 1561, // diamond_axe
	1054: 1561, // diamond_hoe
	1055: 2031, // netherite_sword
	1056: 2031, // netherite_shovel
	1057: 2031, // netherite_pickaxe
	1058: 2031, // netherite_axe
	1059: 2031, // netherite_hoe
	1068: 55,   // leather_helmet
	1069: 80,   // leather_chestplate
	1070: 75,   // leather_leggings
	1071: 65,   // leather_boots
	1072: 121,  // copper_helmet
	1073: 176,  // copper_chestplate
	1074: 165,  // copper_leggings
	1075: 143,  // copper_boots
	1076: 165,  // chainmail_helmet
	1077: 240,  // chainmail_chestplate
	1078: 225,  // chainmail_leggings
	1079: 195,  // chainmail_boots
	1080: 165,  // iron_helmet
	1081: 240,  // iron_chestplate
	1082: 225,  // iron_leggings
	1083: 195,  // iron_boots
	1084: 363,  // diamond_helmet
	1085: 528,  // diamond_chestplate
	1086: 495,  // diamond_leggings
	1087: 429,  // diamond_boots
	1088: 77,   // golden_helmet
	1089: 112,  // golden_chestplate
	1090: 105,  // golden_leggings
	1091: 91,   // golden_boots
	1092: 407,  // netherite_helmet
	1093: 592,  // netherite_chestplate
	1094: 555,  // netherite_leggings
	1095: 481,  // netherite_boots
	1186: 64,   // fishing_rod
	1255: 238,  // shears
	1374: 500,  // mace
	1446: 336,  // shield
	1447: 59,   // wooden_spear
	1448: 131,  // stone_spear
	1449: 190,  // copper_spear
	1450: 250,  // iron_spear
	1451: 32,   // golden_spear
	1452: 1561, // diamond_spear
	1453: 2031, // netherite_spear
	1483: 250,  // trident
	1491: 465,  // crossbow
	1578: 64,   // brush
}

// itemStackSize: NON-BLOCK items whose max stack differs from 64.
var itemStackSize = map[int32]int{
	656:  1,  // shulker_box
	657:  1,  // white_shulker_box
	658:  1,  // orange_shulker_box
	659:  1,  // magenta_shulker_box
	660:  1,  // light_blue_shulker_box
	661:  1,  // yellow_shulker_box
	662:  1,  // lime_shulker_box
	663:  1,  // pink_shulker_box
	664:  1,  // gray_shulker_box
	665:  1,  // light_gray_shulker_box
	666:  1,  // cyan_shulker_box
	667:  1,  // purple_shulker_box
	668:  1,  // blue_shulker_box
	669:  1,  // brown_shulker_box
	670:  1,  // green_shulker_box
	671:  1,  // red_shulker_box
	672:  1,  // black_shulker_box
	949:  1,  // saddle
	950:  1,  // white_harness
	951:  1,  // orange_harness
	952:  1,  // magenta_harness
	953:  1,  // light_blue_harness
	954:  1,  // yellow_harness
	955:  1,  // lime_harness
	956:  1,  // pink_harness
	957:  1,  // gray_harness
	958:  1,  // light_gray_harness
	959:  1,  // cyan_harness
	960:  1,  // purple_harness
	961:  1,  // blue_harness
	962:  1,  // brown_harness
	963:  1,  // green_harness
	964:  1,  // red_harness
	965:  1,  // black_harness
	966:  1,  // minecart
	967:  1,  // chest_minecart
	968:  1,  // furnace_minecart
	969:  1,  // tnt_minecart
	970:  1,  // hopper_minecart
	971:  1,  // carrot_on_a_stick
	972:  1,  // warped_fungus_on_a_stick
	974:  1,  // elytra
	975:  1,  // oak_boat
	976:  1,  // oak_chest_boat
	977:  1,  // spruce_boat
	978:  1,  // spruce_chest_boat
	979:  1,  // birch_boat
	980:  1,  // birch_chest_boat
	981:  1,  // jungle_boat
	982:  1,  // jungle_chest_boat
	983:  1,  // acacia_boat
	984:  1,  // acacia_chest_boat
	985:  1,  // cherry_boat
	986:  1,  // cherry_chest_boat
	987:  1,  // dark_oak_boat
	988:  1,  // dark_oak_chest_boat
	989:  1,  // pale_oak_boat
	990:  1,  // pale_oak_chest_boat
	991:  1,  // mangrove_boat
	992:  1,  // mangrove_chest_boat
	993:  1,  // poplar_boat
	994:  1,  // poplar_chest_boat
	995:  1,  // bamboo_raft
	996:  1,  // bamboo_chest_raft
	1001: 1,  // turtle_helmet
	1004: 1,  // wolf_armor
	1005: 1,  // flint_and_steel
	1008: 1,  // bow
	1025: 1,  // wooden_sword
	1026: 1,  // wooden_shovel
	1027: 1,  // wooden_pickaxe
	1028: 1,  // wooden_axe
	1029: 1,  // wooden_hoe
	1030: 1,  // copper_sword
	1031: 1,  // copper_shovel
	1032: 1,  // copper_pickaxe
	1033: 1,  // copper_axe
	1034: 1,  // copper_hoe
	1035: 1,  // stone_sword
	1036: 1,  // stone_shovel
	1037: 1,  // stone_pickaxe
	1038: 1,  // stone_axe
	1039: 1,  // stone_hoe
	1040: 1,  // golden_sword
	1041: 1,  // golden_shovel
	1042: 1,  // golden_pickaxe
	1043: 1,  // golden_axe
	1044: 1,  // golden_hoe
	1045: 1,  // iron_sword
	1046: 1,  // iron_shovel
	1047: 1,  // iron_pickaxe
	1048: 1,  // iron_axe
	1049: 1,  // iron_hoe
	1050: 1,  // diamond_sword
	1051: 1,  // diamond_shovel
	1052: 1,  // diamond_pickaxe
	1053: 1,  // diamond_axe
	1054: 1,  // diamond_hoe
	1055: 1,  // netherite_sword
	1056: 1,  // netherite_shovel
	1057: 1,  // netherite_pickaxe
	1058: 1,  // netherite_axe
	1059: 1,  // netherite_hoe
	1061: 1,  // mushroom_stew
	1068: 1,  // leather_helmet
	1069: 1,  // leather_chestplate
	1070: 1,  // leather_leggings
	1071: 1,  // leather_boots
	1072: 1,  // copper_helmet
	1073: 1,  // copper_chestplate
	1074: 1,  // copper_leggings
	1075: 1,  // copper_boots
	1076: 1,  // chainmail_helmet
	1077: 1,  // chainmail_chestplate
	1078: 1,  // chainmail_leggings
	1079: 1,  // chainmail_boots
	1080: 1,  // iron_helmet
	1081: 1,  // iron_chestplate
	1082: 1,  // iron_leggings
	1083: 1,  // iron_boots
	1084: 1,  // diamond_helmet
	1085: 1,  // diamond_chestplate
	1086: 1,  // diamond_leggings
	1087: 1,  // diamond_boots
	1088: 1,  // golden_helmet
	1089: 1,  // golden_chestplate
	1090: 1,  // golden_leggings
	1091: 1,  // golden_boots
	1092: 1,  // netherite_helmet
	1093: 1,  // netherite_chestplate
	1094: 1,  // netherite_leggings
	1095: 1,  // netherite_boots
	1102: 16, // oak_sign
	1103: 16, // spruce_sign
	1104: 16, // birch_sign
	1105: 16, // jungle_sign
	1106: 16, // acacia_sign
	1107: 16, // cherry_sign
	1108: 16, // dark_oak_sign
	1109: 16, // pale_oak_sign
	1110: 16, // mangrove_sign
	1111: 16, // poplar_sign
	1112: 16, // bamboo_sign
	1113: 16, // crimson_sign
	1114: 16, // warped_sign
	1115: 16, // oak_hanging_sign
	1116: 16, // spruce_hanging_sign
	1117: 16, // birch_hanging_sign
	1118: 16, // jungle_hanging_sign
	1119: 16, // acacia_hanging_sign
	1120: 16, // cherry_hanging_sign
	1121: 16, // dark_oak_hanging_sign
	1122: 16, // pale_oak_hanging_sign
	1123: 16, // mangrove_hanging_sign
	1124: 16, // poplar_hanging_sign
	1125: 16, // bamboo_hanging_sign
	1126: 16, // crimson_hanging_sign
	1127: 16, // warped_hanging_sign
	1128: 16, // bucket
	1129: 1,  // water_bucket
	1130: 1,  // lava_bucket
	1131: 1,  // powder_snow_bucket
	1132: 16, // snowball
	1134: 1,  // milk_bucket
	1135: 1,  // pufferfish_bucket
	1136: 1,  // salmon_bucket
	1137: 1,  // cod_bucket
	1138: 1,  // tropical_fish_bucket
	1139: 1,  // axolotl_bucket
	1140: 1,  // sulfur_cube_bucket
	1141: 1,  // tadpole_bucket
	1148: 16, // egg
	1149: 16, // blue_egg
	1150: 16, // brown_egg
	1153: 1,  // bundle
	1154: 1,  // white_bundle
	1155: 1,  // orange_bundle
	1156: 1,  // magenta_bundle
	1157: 1,  // light_blue_bundle
	1158: 1,  // yellow_bundle
	1159: 1,  // lime_bundle
	1160: 1,  // pink_bundle
	1161: 1,  // gray_bundle
	1162: 1,  // light_gray_bundle
	1163: 1,  // cyan_bundle
	1164: 1,  // purple_bundle
	1165: 1,  // blue_bundle
	1166: 1,  // brown_bundle
	1167: 1,  // green_bundle
	1168: 1,  // red_bundle
	1169: 1,  // black_bundle
	1170: 16, // white_cushion
	1171: 16, // orange_cushion
	1172: 16, // magenta_cushion
	1173: 16, // light_blue_cushion
	1174: 16, // yellow_cushion
	1175: 16, // lime_cushion
	1176: 16, // pink_cushion
	1177: 16, // gray_cushion
	1178: 16, // light_gray_cushion
	1179: 16, // cyan_cushion
	1180: 16, // purple_cushion
	1181: 16, // blue_cushion
	1182: 16, // brown_cushion
	1183: 16, // green_cushion
	1184: 16, // red_cushion
	1185: 16, // black_cushion
	1186: 1,  // fishing_rod
	1188: 1,  // spyglass
	1218: 1,  // cake
	1219: 1,  // white_bed
	1220: 1,  // orange_bed
	1221: 1,  // magenta_bed
	1222: 1,  // light_blue_bed
	1223: 1,  // yellow_bed
	1224: 1,  // lime_bed
	1225: 1,  // pink_bed
	1226: 1,  // gray_bed
	1227: 1,  // light_gray_bed
	1228: 1,  // cyan_bed
	1229: 1,  // purple_bed
	1230: 1,  // blue_bed
	1231: 1,  // brown_bed
	1232: 1,  // green_bed
	1233: 1,  // red_bed
	1234: 1,  // black_bed
	1235: 16, // straw_bed
	1255: 1,  // shears
	1265: 16, // ender_pearl
	1271: 1,  // potion
	1371: 1,  // writable_book
	1372: 16, // written_book
	1374: 1,  // mace
	1395: 1,  // enchanted_book
	1402: 1,  // rabbit_stew
	1405: 16, // armor_stand
	1406: 1,  // copper_horse_armor
	1407: 1,  // iron_horse_armor
	1408: 1,  // golden_horse_armor
	1409: 1,  // diamond_horse_armor
	1410: 1,  // netherite_horse_armor
	1411: 1,  // leather_horse_armor
	1414: 1,  // command_block_minecart
	1417: 16, // white_banner
	1418: 16, // orange_banner
	1419: 16, // magenta_banner
	1420: 16, // light_blue_banner
	1421: 16, // yellow_banner
	1422: 16, // lime_banner
	1423: 16, // pink_banner
	1424: 16, // gray_banner
	1425: 16, // light_gray_banner
	1426: 16, // cyan_banner
	1427: 16, // purple_banner
	1428: 16, // blue_banner
	1429: 16, // brown_banner
	1430: 16, // green_banner
	1431: 16, // red_banner
	1432: 16, // black_banner
	1440: 1,  // beetroot_soup
	1442: 1,  // splash_potion
	1445: 1,  // lingering_potion
	1446: 1,  // shield
	1447: 1,  // wooden_spear
	1448: 1,  // stone_spear
	1449: 1,  // copper_spear
	1450: 1,  // iron_spear
	1451: 1,  // golden_spear
	1452: 1,  // diamond_spear
	1453: 1,  // netherite_spear
	1454: 1,  // totem_of_undying
	1458: 1,  // knowledge_book
	1459: 1,  // debug_stick
	1460: 1,  // music_disc_13
	1461: 1,  // music_disc_cat
	1462: 1,  // music_disc_blocks
	1463: 1,  // music_disc_bounce
	1464: 1,  // music_disc_chirp
	1465: 1,  // music_disc_creator
	1466: 1,  // music_disc_creator_music_box
	1467: 1,  // music_disc_far
	1468: 1,  // music_disc_lava_chicken
	1469: 1,  // music_disc_mall
	1470: 1,  // music_disc_mellohi
	1471: 1,  // music_disc_stal
	1472: 1,  // music_disc_strad
	1473: 1,  // music_disc_ward
	1474: 1,  // music_disc_11
	1475: 1,  // music_disc_wait
	1476: 1,  // music_disc_otherside
	1477: 1,  // music_disc_relic
	1478: 1,  // music_disc_5
	1479: 1,  // music_disc_pigstep
	1480: 1,  // music_disc_precipice
	1481: 1,  // music_disc_tears
	1483: 1,  // trident
	1485: 1,  // iron_nautilus_armor
	1486: 1,  // golden_nautilus_armor
	1487: 1,  // diamond_nautilus_armor
	1488: 1,  // netherite_nautilus_armor
	1489: 1,  // copper_nautilus_armor
	1491: 1,  // crossbow
	1492: 1,  // suspicious_stew
	1494: 1,  // flower_banner_pattern
	1495: 1,  // creeper_banner_pattern
	1496: 1,  // skull_banner_pattern
	1497: 1,  // mojang_banner_pattern
	1498: 1,  // globe_banner_pattern
	1499: 1,  // piglin_banner_pattern
	1500: 1,  // flow_banner_pattern
	1501: 1,  // guster_banner_pattern
	1502: 1,  // field_masoned_banner_pattern
	1503: 1,  // bordure_indented_banner_pattern
	1504: 1,  // goat_horn
	1533: 16, // honey_bottle
	1578: 1,  // brush
}

// armorPiece describes a wearable: which armor slot it goes in
// (0 head, 1 chest, 2 legs, 3 feet), its defense points and toughness.
type armorPiece struct {
	Slot      int
	Points    int
	Toughness float64
}

var armorInfo = map[int32]armorPiece{
	1001: {Slot: 0, Points: 2, Toughness: 0.0}, // turtle_helmet
	1068: {Slot: 0, Points: 1, Toughness: 0.0}, // leather_helmet
	1069: {Slot: 1, Points: 3, Toughness: 0.0}, // leather_chestplate
	1070: {Slot: 2, Points: 2, Toughness: 0.0}, // leather_leggings
	1071: {Slot: 3, Points: 1, Toughness: 0.0}, // leather_boots
	1072: {Slot: 0, Points: 2, Toughness: 0.0}, // copper_helmet
	1073: {Slot: 1, Points: 4, Toughness: 0.0}, // copper_chestplate
	1074: {Slot: 2, Points: 5, Toughness: 0.0}, // copper_leggings
	1075: {Slot: 3, Points: 1, Toughness: 0.0}, // copper_boots
	1076: {Slot: 0, Points: 2, Toughness: 0.0}, // chainmail_helmet
	1077: {Slot: 1, Points: 5, Toughness: 0.0}, // chainmail_chestplate
	1078: {Slot: 2, Points: 4, Toughness: 0.0}, // chainmail_leggings
	1079: {Slot: 3, Points: 1, Toughness: 0.0}, // chainmail_boots
	1080: {Slot: 0, Points: 2, Toughness: 0.0}, // iron_helmet
	1081: {Slot: 1, Points: 6, Toughness: 0.0}, // iron_chestplate
	1082: {Slot: 2, Points: 5, Toughness: 0.0}, // iron_leggings
	1083: {Slot: 3, Points: 2, Toughness: 0.0}, // iron_boots
	1084: {Slot: 0, Points: 3, Toughness: 2.0}, // diamond_helmet
	1085: {Slot: 1, Points: 8, Toughness: 2.0}, // diamond_chestplate
	1086: {Slot: 2, Points: 6, Toughness: 2.0}, // diamond_leggings
	1087: {Slot: 3, Points: 3, Toughness: 2.0}, // diamond_boots
	1088: {Slot: 0, Points: 2, Toughness: 0.0}, // golden_helmet
	1089: {Slot: 1, Points: 5, Toughness: 0.0}, // golden_chestplate
	1090: {Slot: 2, Points: 3, Toughness: 0.0}, // golden_leggings
	1091: {Slot: 3, Points: 1, Toughness: 0.0}, // golden_boots
	1092: {Slot: 0, Points: 3, Toughness: 3.0}, // netherite_helmet
	1093: {Slot: 1, Points: 8, Toughness: 3.0}, // netherite_chestplate
	1094: {Slot: 2, Points: 6, Toughness: 3.0}, // netherite_leggings
	1095: {Slot: 3, Points: 3, Toughness: 3.0}, // netherite_boots
}
