// Code generated by scripts/gen_durability.py — DO NOT EDIT.
// Source: PrismarineJS/minecraft-data data/pc/1.21.11/items.json
// (armor points/toughness are vanilla constants hand-coded in the script).

package server

// itemMaxDurability: item id -> max durability. An item is wearable-out
// iff it has an entry here.
var itemMaxDurability = map[int32]int{
	859:  25,   // carrot_on_a_stick
	860:  100,  // warped_fungus_on_a_stick
	862:  432,  // elytra
	887:  275,  // turtle_helmet
	890:  64,   // wolf_armor
	891:  64,   // flint_and_steel
	894:  384,  // bow
	911:  59,   // wooden_sword
	912:  59,   // wooden_shovel
	913:  59,   // wooden_pickaxe
	914:  59,   // wooden_axe
	915:  59,   // wooden_hoe
	916:  190,  // copper_sword
	917:  190,  // copper_shovel
	918:  190,  // copper_pickaxe
	919:  190,  // copper_axe
	920:  190,  // copper_hoe
	921:  131,  // stone_sword
	922:  131,  // stone_shovel
	923:  131,  // stone_pickaxe
	924:  131,  // stone_axe
	925:  131,  // stone_hoe
	926:  32,   // golden_sword
	927:  32,   // golden_shovel
	928:  32,   // golden_pickaxe
	929:  32,   // golden_axe
	930:  32,   // golden_hoe
	931:  250,  // iron_sword
	932:  250,  // iron_shovel
	933:  250,  // iron_pickaxe
	934:  250,  // iron_axe
	935:  250,  // iron_hoe
	936:  1561, // diamond_sword
	937:  1561, // diamond_shovel
	938:  1561, // diamond_pickaxe
	939:  1561, // diamond_axe
	940:  1561, // diamond_hoe
	941:  2031, // netherite_sword
	942:  2031, // netherite_shovel
	943:  2031, // netherite_pickaxe
	944:  2031, // netherite_axe
	945:  2031, // netherite_hoe
	954:  55,   // leather_helmet
	955:  80,   // leather_chestplate
	956:  75,   // leather_leggings
	957:  65,   // leather_boots
	958:  121,  // copper_helmet
	959:  176,  // copper_chestplate
	960:  165,  // copper_leggings
	961:  143,  // copper_boots
	962:  165,  // chainmail_helmet
	963:  240,  // chainmail_chestplate
	964:  225,  // chainmail_leggings
	965:  195,  // chainmail_boots
	966:  165,  // iron_helmet
	967:  240,  // iron_chestplate
	968:  225,  // iron_leggings
	969:  195,  // iron_boots
	970:  363,  // diamond_helmet
	971:  528,  // diamond_chestplate
	972:  495,  // diamond_leggings
	973:  429,  // diamond_boots
	974:  77,   // golden_helmet
	975:  112,  // golden_chestplate
	976:  105,  // golden_leggings
	977:  91,   // golden_boots
	978:  407,  // netherite_helmet
	979:  592,  // netherite_chestplate
	980:  555,  // netherite_leggings
	981:  481,  // netherite_boots
	1053: 64,   // fishing_rod
	1105: 238,  // shears
	1223: 500,  // mace
	1295: 336,  // shield
	1296: 59,   // wooden_spear
	1297: 131,  // stone_spear
	1298: 190,  // copper_spear
	1299: 250,  // iron_spear
	1300: 32,   // golden_spear
	1301: 1561, // diamond_spear
	1302: 2031, // netherite_spear
	1331: 250,  // trident
	1339: 465,  // crossbow
	1425: 64,   // brush
}

// itemStackSize: NON-BLOCK items whose max stack differs from 64.
var itemStackSize = map[int32]int{
	581:  1,  // shulker_box
	582:  1,  // white_shulker_box
	583:  1,  // orange_shulker_box
	584:  1,  // magenta_shulker_box
	585:  1,  // light_blue_shulker_box
	586:  1,  // yellow_shulker_box
	587:  1,  // lime_shulker_box
	588:  1,  // pink_shulker_box
	589:  1,  // gray_shulker_box
	590:  1,  // light_gray_shulker_box
	591:  1,  // cyan_shulker_box
	592:  1,  // purple_shulker_box
	593:  1,  // blue_shulker_box
	594:  1,  // brown_shulker_box
	595:  1,  // green_shulker_box
	596:  1,  // red_shulker_box
	597:  1,  // black_shulker_box
	837:  1,  // saddle
	838:  1,  // white_harness
	839:  1,  // orange_harness
	840:  1,  // magenta_harness
	841:  1,  // light_blue_harness
	842:  1,  // yellow_harness
	843:  1,  // lime_harness
	844:  1,  // pink_harness
	845:  1,  // gray_harness
	846:  1,  // light_gray_harness
	847:  1,  // cyan_harness
	848:  1,  // purple_harness
	849:  1,  // blue_harness
	850:  1,  // brown_harness
	851:  1,  // green_harness
	852:  1,  // red_harness
	853:  1,  // black_harness
	854:  1,  // minecart
	855:  1,  // chest_minecart
	856:  1,  // furnace_minecart
	857:  1,  // tnt_minecart
	858:  1,  // hopper_minecart
	859:  1,  // carrot_on_a_stick
	860:  1,  // warped_fungus_on_a_stick
	862:  1,  // elytra
	863:  1,  // oak_boat
	864:  1,  // oak_chest_boat
	865:  1,  // spruce_boat
	866:  1,  // spruce_chest_boat
	867:  1,  // birch_boat
	868:  1,  // birch_chest_boat
	869:  1,  // jungle_boat
	870:  1,  // jungle_chest_boat
	871:  1,  // acacia_boat
	872:  1,  // acacia_chest_boat
	873:  1,  // cherry_boat
	874:  1,  // cherry_chest_boat
	875:  1,  // dark_oak_boat
	876:  1,  // dark_oak_chest_boat
	877:  1,  // pale_oak_boat
	878:  1,  // pale_oak_chest_boat
	879:  1,  // mangrove_boat
	880:  1,  // mangrove_chest_boat
	881:  1,  // bamboo_raft
	882:  1,  // bamboo_chest_raft
	887:  1,  // turtle_helmet
	890:  1,  // wolf_armor
	891:  1,  // flint_and_steel
	894:  1,  // bow
	911:  1,  // wooden_sword
	912:  1,  // wooden_shovel
	913:  1,  // wooden_pickaxe
	914:  1,  // wooden_axe
	915:  1,  // wooden_hoe
	916:  1,  // copper_sword
	917:  1,  // copper_shovel
	918:  1,  // copper_pickaxe
	919:  1,  // copper_axe
	920:  1,  // copper_hoe
	921:  1,  // stone_sword
	922:  1,  // stone_shovel
	923:  1,  // stone_pickaxe
	924:  1,  // stone_axe
	925:  1,  // stone_hoe
	926:  1,  // golden_sword
	927:  1,  // golden_shovel
	928:  1,  // golden_pickaxe
	929:  1,  // golden_axe
	930:  1,  // golden_hoe
	931:  1,  // iron_sword
	932:  1,  // iron_shovel
	933:  1,  // iron_pickaxe
	934:  1,  // iron_axe
	935:  1,  // iron_hoe
	936:  1,  // diamond_sword
	937:  1,  // diamond_shovel
	938:  1,  // diamond_pickaxe
	939:  1,  // diamond_axe
	940:  1,  // diamond_hoe
	941:  1,  // netherite_sword
	942:  1,  // netherite_shovel
	943:  1,  // netherite_pickaxe
	944:  1,  // netherite_axe
	945:  1,  // netherite_hoe
	947:  1,  // mushroom_stew
	954:  1,  // leather_helmet
	955:  1,  // leather_chestplate
	956:  1,  // leather_leggings
	957:  1,  // leather_boots
	958:  1,  // copper_helmet
	959:  1,  // copper_chestplate
	960:  1,  // copper_leggings
	961:  1,  // copper_boots
	962:  1,  // chainmail_helmet
	963:  1,  // chainmail_chestplate
	964:  1,  // chainmail_leggings
	965:  1,  // chainmail_boots
	966:  1,  // iron_helmet
	967:  1,  // iron_chestplate
	968:  1,  // iron_leggings
	969:  1,  // iron_boots
	970:  1,  // diamond_helmet
	971:  1,  // diamond_chestplate
	972:  1,  // diamond_leggings
	973:  1,  // diamond_boots
	974:  1,  // golden_helmet
	975:  1,  // golden_chestplate
	976:  1,  // golden_leggings
	977:  1,  // golden_boots
	978:  1,  // netherite_helmet
	979:  1,  // netherite_chestplate
	980:  1,  // netherite_leggings
	981:  1,  // netherite_boots
	988:  16, // oak_sign
	989:  16, // spruce_sign
	990:  16, // birch_sign
	991:  16, // jungle_sign
	992:  16, // acacia_sign
	993:  16, // cherry_sign
	994:  16, // dark_oak_sign
	995:  16, // pale_oak_sign
	996:  16, // mangrove_sign
	997:  16, // bamboo_sign
	998:  16, // crimson_sign
	999:  16, // warped_sign
	1000: 16, // oak_hanging_sign
	1001: 16, // spruce_hanging_sign
	1002: 16, // birch_hanging_sign
	1003: 16, // jungle_hanging_sign
	1004: 16, // acacia_hanging_sign
	1005: 16, // cherry_hanging_sign
	1006: 16, // dark_oak_hanging_sign
	1007: 16, // pale_oak_hanging_sign
	1008: 16, // mangrove_hanging_sign
	1009: 16, // bamboo_hanging_sign
	1010: 16, // crimson_hanging_sign
	1011: 16, // warped_hanging_sign
	1012: 16, // bucket
	1013: 1,  // water_bucket
	1014: 1,  // lava_bucket
	1015: 1,  // powder_snow_bucket
	1016: 16, // snowball
	1018: 1,  // milk_bucket
	1019: 1,  // pufferfish_bucket
	1020: 1,  // salmon_bucket
	1021: 1,  // cod_bucket
	1022: 1,  // tropical_fish_bucket
	1023: 1,  // axolotl_bucket
	1024: 1,  // tadpole_bucket
	1031: 16, // egg
	1032: 16, // blue_egg
	1033: 16, // brown_egg
	1036: 1,  // bundle
	1037: 1,  // white_bundle
	1038: 1,  // orange_bundle
	1039: 1,  // magenta_bundle
	1040: 1,  // light_blue_bundle
	1041: 1,  // yellow_bundle
	1042: 1,  // lime_bundle
	1043: 1,  // pink_bundle
	1044: 1,  // gray_bundle
	1045: 1,  // light_gray_bundle
	1046: 1,  // cyan_bundle
	1047: 1,  // purple_bundle
	1048: 1,  // blue_bundle
	1049: 1,  // brown_bundle
	1050: 1,  // green_bundle
	1051: 1,  // red_bundle
	1052: 1,  // black_bundle
	1053: 1,  // fishing_rod
	1055: 1,  // spyglass
	1085: 1,  // cake
	1086: 1,  // white_bed
	1087: 1,  // orange_bed
	1088: 1,  // magenta_bed
	1089: 1,  // light_blue_bed
	1090: 1,  // yellow_bed
	1091: 1,  // lime_bed
	1092: 1,  // pink_bed
	1093: 1,  // gray_bed
	1094: 1,  // light_gray_bed
	1095: 1,  // cyan_bed
	1096: 1,  // purple_bed
	1097: 1,  // blue_bed
	1098: 1,  // brown_bed
	1099: 1,  // green_bed
	1100: 1,  // red_bed
	1101: 1,  // black_bed
	1105: 1,  // shears
	1115: 16, // ender_pearl
	1121: 1,  // potion
	1220: 1,  // writable_book
	1221: 16, // written_book
	1223: 1,  // mace
	1244: 1,  // enchanted_book
	1251: 1,  // rabbit_stew
	1254: 16, // armor_stand
	1255: 1,  // copper_horse_armor
	1256: 1,  // iron_horse_armor
	1257: 1,  // golden_horse_armor
	1258: 1,  // diamond_horse_armor
	1259: 1,  // netherite_horse_armor
	1260: 1,  // leather_horse_armor
	1263: 1,  // command_block_minecart
	1266: 16, // white_banner
	1267: 16, // orange_banner
	1268: 16, // magenta_banner
	1269: 16, // light_blue_banner
	1270: 16, // yellow_banner
	1271: 16, // lime_banner
	1272: 16, // pink_banner
	1273: 16, // gray_banner
	1274: 16, // light_gray_banner
	1275: 16, // cyan_banner
	1276: 16, // purple_banner
	1277: 16, // blue_banner
	1278: 16, // brown_banner
	1279: 16, // green_banner
	1280: 16, // red_banner
	1281: 16, // black_banner
	1289: 1,  // beetroot_soup
	1291: 1,  // splash_potion
	1294: 1,  // lingering_potion
	1295: 1,  // shield
	1296: 1,  // wooden_spear
	1297: 1,  // stone_spear
	1298: 1,  // copper_spear
	1299: 1,  // iron_spear
	1300: 1,  // golden_spear
	1301: 1,  // diamond_spear
	1302: 1,  // netherite_spear
	1303: 1,  // totem_of_undying
	1307: 1,  // knowledge_book
	1308: 1,  // debug_stick
	1309: 1,  // music_disc_13
	1310: 1,  // music_disc_cat
	1311: 1,  // music_disc_blocks
	1312: 1,  // music_disc_chirp
	1313: 1,  // music_disc_creator
	1314: 1,  // music_disc_creator_music_box
	1315: 1,  // music_disc_far
	1316: 1,  // music_disc_lava_chicken
	1317: 1,  // music_disc_mall
	1318: 1,  // music_disc_mellohi
	1319: 1,  // music_disc_stal
	1320: 1,  // music_disc_strad
	1321: 1,  // music_disc_ward
	1322: 1,  // music_disc_11
	1323: 1,  // music_disc_wait
	1324: 1,  // music_disc_otherside
	1325: 1,  // music_disc_relic
	1326: 1,  // music_disc_5
	1327: 1,  // music_disc_pigstep
	1328: 1,  // music_disc_precipice
	1329: 1,  // music_disc_tears
	1331: 1,  // trident
	1333: 1,  // iron_nautilus_armor
	1334: 1,  // golden_nautilus_armor
	1335: 1,  // diamond_nautilus_armor
	1336: 1,  // netherite_nautilus_armor
	1337: 1,  // copper_nautilus_armor
	1339: 1,  // crossbow
	1340: 1,  // suspicious_stew
	1342: 1,  // flower_banner_pattern
	1343: 1,  // creeper_banner_pattern
	1344: 1,  // skull_banner_pattern
	1345: 1,  // mojang_banner_pattern
	1346: 1,  // globe_banner_pattern
	1347: 1,  // piglin_banner_pattern
	1348: 1,  // flow_banner_pattern
	1349: 1,  // guster_banner_pattern
	1350: 1,  // field_masoned_banner_pattern
	1351: 1,  // bordure_indented_banner_pattern
	1352: 1,  // goat_horn
	1381: 16, // honey_bottle
	1425: 1,  // brush
}

// armorPiece describes a wearable: which armor slot it goes in
// (0 head, 1 chest, 2 legs, 3 feet), its defense points and toughness.
type armorPiece struct {
	Slot      int
	Points    int
	Toughness float64
}

var armorInfo = map[int32]armorPiece{
	887: {Slot: 0, Points: 2, Toughness: 0.0}, // turtle_helmet
	954: {Slot: 0, Points: 1, Toughness: 0.0}, // leather_helmet
	955: {Slot: 1, Points: 3, Toughness: 0.0}, // leather_chestplate
	956: {Slot: 2, Points: 2, Toughness: 0.0}, // leather_leggings
	957: {Slot: 3, Points: 1, Toughness: 0.0}, // leather_boots
	958: {Slot: 0, Points: 2, Toughness: 0.0}, // copper_helmet
	959: {Slot: 1, Points: 4, Toughness: 0.0}, // copper_chestplate
	960: {Slot: 2, Points: 5, Toughness: 0.0}, // copper_leggings
	961: {Slot: 3, Points: 1, Toughness: 0.0}, // copper_boots
	962: {Slot: 0, Points: 2, Toughness: 0.0}, // chainmail_helmet
	963: {Slot: 1, Points: 5, Toughness: 0.0}, // chainmail_chestplate
	964: {Slot: 2, Points: 4, Toughness: 0.0}, // chainmail_leggings
	965: {Slot: 3, Points: 1, Toughness: 0.0}, // chainmail_boots
	966: {Slot: 0, Points: 2, Toughness: 0.0}, // iron_helmet
	967: {Slot: 1, Points: 6, Toughness: 0.0}, // iron_chestplate
	968: {Slot: 2, Points: 5, Toughness: 0.0}, // iron_leggings
	969: {Slot: 3, Points: 2, Toughness: 0.0}, // iron_boots
	970: {Slot: 0, Points: 3, Toughness: 2.0}, // diamond_helmet
	971: {Slot: 1, Points: 8, Toughness: 2.0}, // diamond_chestplate
	972: {Slot: 2, Points: 6, Toughness: 2.0}, // diamond_leggings
	973: {Slot: 3, Points: 3, Toughness: 2.0}, // diamond_boots
	974: {Slot: 0, Points: 2, Toughness: 0.0}, // golden_helmet
	975: {Slot: 1, Points: 5, Toughness: 0.0}, // golden_chestplate
	976: {Slot: 2, Points: 3, Toughness: 0.0}, // golden_leggings
	977: {Slot: 3, Points: 1, Toughness: 0.0}, // golden_boots
	978: {Slot: 0, Points: 3, Toughness: 3.0}, // netherite_helmet
	979: {Slot: 1, Points: 8, Toughness: 3.0}, // netherite_chestplate
	980: {Slot: 2, Points: 6, Toughness: 3.0}, // netherite_leggings
	981: {Slot: 3, Points: 3, Toughness: 3.0}, // netherite_boots
}
