// Code generated by the note-instrument extraction tool from vanilla block data. DO NOT EDIT.

package server

import "testing"

// TestNoteInstrumentSpotChecks pins well-known block -> instrument
// mappings via each block's default state id (canonical 1.21.11).
func TestNoteInstrumentSpotChecks(t *testing.T) {
	cases := []struct {
		block string
		state uint32
		want  uint8
	}{
		{"stone", 1, 1},             // basedrum
		{"oak_planks", 15, 4},       // bass
		{"sand", 118, 2},            // snare
		{"glass", 562, 3},           // hat
		{"gold_block", 2137, 6},     // bell
		{"clay", 6745, 5},           // flute
		{"packed_ice", 12712, 8},    // chime
		{"white_wool", 2093, 7},     // guitar
		{"bone_block", 14647, 9},    // xylophone
		{"iron_block", 2138, 10},    // iron_xylophone
		{"soul_sand", 6797, 11},     // cow_bell
		{"pumpkin", 8131, 12},       // didgeridoo
		{"emerald_block", 9526, 13}, // bit
		{"hay_block", 12692, 14},    // banjo
		{"glowstone", 6815, 15},     // pling
		{"zombie_head", 10809, 16},  // zombie
		{"player_head", 10849, 22},  // custom_head
		{"dirt", 10, 0},             // harp
		{"grass_block", 9, 0},       // harp
	}
	for _, c := range cases {
		if got := noteInstrumentFor(c.state); got != c.want {
			t.Errorf("%s (state %d): got %d (%s), want %d (%s)",
				c.block, c.state, got, noteInstrumentNames[got],
				c.want, noteInstrumentNames[c.want])
		}
	}
}
