// Code generated by scripts/gen_numproviders.py from the vanilla datapack. DO NOT EDIT.

package server

// floatProviderDefs is the context_float_provider registry (canonical 26.3): id → JSON.
var floatProviderDefs = map[string]string{
	"minecraft:brewing/speed_default":           "1.0",
	"minecraft:cooking/fast_speed_multiplier":   "2.0",
	"minecraft:cooking/normal_speed_multiplier": "1.0",
	"minecraft:cooking/speed_default":           "{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_speed_multiplier\",\"on_true\":\"minecraft:cooking/fast_speed_multiplier\"}",
}

// intProviderDefs is the context_int_provider registry (canonical 26.3): id → JSON.
var intProviderDefs = map[string]string{
	"minecraft:brewing/uses_default":                      "20",
	"minecraft:compostable/always_add_one":                "1",
	"minecraft:compostable/low":                           "{\"type\":\"minecraft:number_dispatcher\",\"cases\":[{\"condition\":{\"type\":\"minecraft:match_block\",\"blocks\":\"minecraft:composter\",\"state\":{\"level\":\"0\"}},\"value\":1}],\"default\":{\"type\":\"minecraft:weighted_list\",\"distribution\":[{\"data\":1,\"weight\":30},{\"data\":0,\"weight\":70}]}}",
	"minecraft:compostable/low_medium":                    "{\"type\":\"minecraft:number_dispatcher\",\"cases\":[{\"condition\":{\"type\":\"minecraft:match_block\",\"blocks\":\"minecraft:composter\",\"state\":{\"level\":\"0\"}},\"value\":1}],\"default\":{\"type\":\"minecraft:weighted_list\",\"distribution\":[{\"data\":1,\"weight\":50},{\"data\":0,\"weight\":50}]}}",
	"minecraft:compostable/medium":                        "{\"type\":\"minecraft:number_dispatcher\",\"cases\":[{\"condition\":{\"type\":\"minecraft:match_block\",\"blocks\":\"minecraft:composter\",\"state\":{\"level\":\"0\"}},\"value\":1}],\"default\":{\"type\":\"minecraft:weighted_list\",\"distribution\":[{\"data\":1,\"weight\":65},{\"data\":0,\"weight\":35}]}}",
	"minecraft:compostable/medium_high":                   "{\"type\":\"minecraft:number_dispatcher\",\"cases\":[{\"condition\":{\"type\":\"minecraft:match_block\",\"blocks\":\"minecraft:composter\",\"state\":{\"level\":\"0\"}},\"value\":1}],\"default\":{\"type\":\"minecraft:weighted_list\",\"distribution\":[{\"data\":1,\"weight\":85},{\"data\":0,\"weight\":15}]}}",
	"minecraft:cooking/fast_burn_time_reduction_factor":   "2",
	"minecraft:cooking/normal_burn_time_reduction_factor": "1",
	"minecraft:cooking/time_bamboo":                       "{\"type\":\"minecraft:div\",\"left\":50,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_blaze_rod":                    "{\"type\":\"minecraft:div\",\"left\":2400,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_boats":                        "{\"type\":\"minecraft:div\",\"left\":1200,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_coal":                         "{\"type\":\"minecraft:div\",\"left\":1600,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_coal_block":                   "{\"type\":\"minecraft:div\",\"left\":16000,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_dried_kelp_block":             "{\"type\":\"minecraft:div\",\"left\":4001,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_dry_plants":                   "{\"type\":\"minecraft:div\",\"left\":100,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_hanging_signs":                "{\"type\":\"minecraft:div\",\"left\":800,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_lava_bucket":                  "{\"type\":\"minecraft:div\",\"left\":20000,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_roots":                        "{\"type\":\"minecraft:div\",\"left\":300,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wood_blocks":                  "{\"type\":\"minecraft:div\",\"left\":300,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wood_items_extra_small":       "{\"type\":\"minecraft:div\",\"left\":100,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wood_items_large":             "{\"type\":\"minecraft:div\",\"left\":200,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wood_items_small":             "{\"type\":\"minecraft:div\",\"left\":300,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wood_slabs":                   "{\"type\":\"minecraft:div\",\"left\":150,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wool":                         "{\"type\":\"minecraft:div\",\"left\":100,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wool_carpets":                 "{\"type\":\"minecraft:div\",\"left\":67,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
	"minecraft:cooking/time_wool_slabs":                   "{\"type\":\"minecraft:div\",\"left\":50,\"right\":{\"type\":\"minecraft:conditional\",\"condition\":\"minecraft:block/fast_cooking\",\"on_false\":\"minecraft:cooking/normal_burn_time_reduction_factor\",\"on_true\":\"minecraft:cooking/fast_burn_time_reduction_factor\"}}",
}

// predicateDefs is the predicate registry (canonical 26.3): id → JSON.
var predicateDefs = map[string]string{
	"minecraft:block/fast_cooking":  "{\"type\":\"minecraft:match_block\",\"blocks\":[\"minecraft:smoker\",\"minecraft:blast_furnace\"]}",
	"minecraft:tool/can_shear":      "{\"type\":\"minecraft:match_tool\",\"predicate\":{\"items\":\"minecraft:shears\"}}",
	"minecraft:tool/can_silk_touch": "{\"type\":\"minecraft:match_tool\",\"predicate\":{\"predicates\":{\"minecraft:enchantments\":[{\"enchantments\":\"minecraft:silk_touch\",\"levels\":{\"min\":1}}]}}}",
}
