// Code generated by scripts/gen_paintings.py; DO NOT EDIT.

package server

// paintingVariant is one placeable painting: its registry name and its
// size in blocks (the placement/survival math needs the footprint).
type paintingVariant struct {
	Name string
	W, H int
}

// paintingVariants lists the vanilla placeable painting variants
// (tags/painting_variant/placeable).
var paintingVariants = []paintingVariant{
	{"alban", 1, 1},
	{"aztec", 1, 1},
	{"aztec2", 1, 1},
	{"backyard", 3, 4},
	{"baroque", 2, 2},
	{"bomb", 1, 1},
	{"bouquet", 3, 3},
	{"burning_skull", 4, 4},
	{"bust", 2, 2},
	{"cavebird", 3, 3},
	{"changing", 4, 2},
	{"cotan", 3, 3},
	{"courbet", 2, 1},
	{"creebet", 2, 1},
	{"dennis", 3, 3},
	{"donkey_kong", 4, 3},
	{"endboss", 3, 3},
	{"fern", 3, 3},
	{"fighters", 4, 2},
	{"finding", 4, 2},
	{"graham", 1, 2},
	{"humble", 2, 2},
	{"kebab", 1, 1},
	{"lowmist", 4, 2},
	{"match", 2, 2},
	{"meditative", 1, 1},
	{"orb", 4, 4},
	{"owlemons", 3, 3},
	{"passage", 4, 2},
	{"pigscene", 4, 4},
	{"plant", 1, 1},
	{"pointer", 4, 4},
	{"pond", 3, 4},
	{"pool", 2, 1},
	{"prairie_ride", 1, 2},
	{"sea", 2, 1},
	{"skeleton", 4, 3},
	{"skull_and_roses", 2, 2},
	{"stage", 2, 2},
	{"sunflowers", 3, 3},
	{"sunset", 2, 1},
	{"tides", 3, 3},
	{"unpacked", 4, 4},
	{"void", 2, 2},
	{"wanderer", 1, 2},
	{"wasteland", 1, 1},
	{"wither", 2, 2},
}
