// Code generated by scripts/gen_signs.py; DO NOT EDIT.

package server

// Sign block kinds (state-range classification).
const (
	signStanding       = iota // rotation 0-15, on the ground
	signWall                  // facing, on a wall
	signHangingCeiling        // attached + rotation, under a block
	signHangingWall           // facing, bracket on a wall side
)

// signWallVariant maps a sign item's standing default state (what
// BlockForItem returns) to the same wood's wall-sign default state.
var signWallVariant = map[uint32]uint32{
	5231:  5651,  // acacia
	5423:  5699,  // bamboo
	5199:  5643,  // birch
	5263:  5659,  // cherry
	21441: 21505, // crimson
	5327:  5675,  // dark_oak
	5295:  5667,  // jungle
	5391:  5691,  // mangrove
	5135:  5627,  // oak
	5359:  5683,  // pale_oak
	5167:  5635,  // spruce
	21473: 21513, // warped
}

// hangingWallVariant maps a hanging-sign item's ceiling default state to
// the same wood's wall-hanging default state.
var hangingWallVariant = map[uint32]uint32{
	5931: 6499, // acacia
	6443: 6563, // bamboo
	5867: 6491, // birch
	5995: 6507, // cherry
	6251: 6547, // crimson
	6123: 6523, // dark_oak
	6059: 6515, // jungle
	6379: 6539, // mangrove
	5739: 6475, // oak
	6187: 6531, // pale_oak
	5803: 6483, // spruce
	6315: 6555, // warped
}

// signKindRanges classifies any sign block state (sorted by Min).
var signKindRanges = []struct {
	Min, Max uint32
	Kind     int
}{
	{5134, 5165, signStanding},       // oak
	{5166, 5197, signStanding},       // spruce
	{5198, 5229, signStanding},       // birch
	{5230, 5261, signStanding},       // acacia
	{5262, 5293, signStanding},       // cherry
	{5294, 5325, signStanding},       // jungle
	{5326, 5357, signStanding},       // dark_oak
	{5358, 5389, signStanding},       // pale_oak
	{5390, 5421, signStanding},       // mangrove
	{5422, 5453, signStanding},       // bamboo
	{5626, 5633, signWall},           // oak
	{5634, 5641, signWall},           // spruce
	{5642, 5649, signWall},           // birch
	{5650, 5657, signWall},           // acacia
	{5658, 5665, signWall},           // cherry
	{5666, 5673, signWall},           // jungle
	{5674, 5681, signWall},           // dark_oak
	{5682, 5689, signWall},           // pale_oak
	{5690, 5697, signWall},           // mangrove
	{5698, 5705, signWall},           // bamboo
	{5706, 5769, signHangingCeiling}, // oak
	{5770, 5833, signHangingCeiling}, // spruce
	{5834, 5897, signHangingCeiling}, // birch
	{5898, 5961, signHangingCeiling}, // acacia
	{5962, 6025, signHangingCeiling}, // cherry
	{6026, 6089, signHangingCeiling}, // jungle
	{6090, 6153, signHangingCeiling}, // dark_oak
	{6154, 6217, signHangingCeiling}, // pale_oak
	{6218, 6281, signHangingCeiling}, // crimson
	{6282, 6345, signHangingCeiling}, // warped
	{6346, 6409, signHangingCeiling}, // mangrove
	{6410, 6473, signHangingCeiling}, // bamboo
	{6474, 6481, signHangingWall},    // oak
	{6482, 6489, signHangingWall},    // spruce
	{6490, 6497, signHangingWall},    // birch
	{6498, 6505, signHangingWall},    // acacia
	{6506, 6513, signHangingWall},    // cherry
	{6514, 6521, signHangingWall},    // jungle
	{6522, 6529, signHangingWall},    // dark_oak
	{6530, 6537, signHangingWall},    // pale_oak
	{6538, 6545, signHangingWall},    // mangrove
	{6546, 6553, signHangingWall},    // crimson
	{6554, 6561, signHangingWall},    // warped
	{6562, 6569, signHangingWall},    // bamboo
	{21440, 21471, signStanding},     // crimson
	{21472, 21503, signStanding},     // warped
	{21504, 21511, signWall},         // crimson
	{21512, 21519, signWall},         // warped
}

// signKind classifies a block state as a sign kind; ok=false if not a sign.
func signKind(state uint32) (int, bool) {
	for _, r := range signKindRanges {
		if state >= r.Min && state <= r.Max {
			return r.Kind, true
		}
		if state < r.Min {
			break
		}
	}
	return 0, false
}
