// Code generated by scripts/gen_standing.py; DO NOT EDIT.

package server

// bannerWallVariant maps a banner item's standing default state to the
// same color's wall-banner default state.
var bannerWallVariant = map[uint32]uint32{
	12725: 12981, // white
	12741: 12985, // orange
	12757: 12989, // magenta
	12773: 12993, // light_blue
	12789: 12997, // yellow
	12805: 13001, // lime
	12821: 13005, // pink
	12837: 13009, // gray
	12853: 13013, // light_gray
	12869: 13017, // cyan
	12885: 13021, // purple
	12901: 13025, // blue
	12917: 13029, // brown
	12933: 13033, // green
	12949: 13037, // red
	12965: 13041, // black
}

// headWallVariant maps a mob head/skull item's standing default state to
// its wall variant. Heads need no support block (vanilla SkullBlock).
var headWallVariant = map[uint32]uint32{
	10889: 10906, // creeper_head
	10929: 10946, // dragon_head
	10969: 10986, // piglin_head
	10849: 10866, // player_head
	10729: 10746, // skeleton_skull
	10769: 10786, // wither_skeleton_skull
	10809: 10826, // zombie_head
}
