// Code generated from vanilla's block sound types (Blocks/SoundType). DO NOT EDIT.

package server

// blockSoundType names every block's sound type; a block absent here is stone.
var blockSoundType = map[string]string{
	"acacia_fence":                  "WOOD",
	"acacia_planks":                 "WOOD",
	"acacia_sapling":                "GRASS",
	"acacia_shelf":                  "SHELF",
	"acacia_slab":                   "WOOD",
	"acacia_wood":                   "WOOD",
	"activator_rail":                "METAL",
	"allium":                        "GRASS",
	"amethyst_block":                "AMETHYST",
	"amethyst_cluster":              "AMETHYST_CLUSTER",
	"ancient_debris":                "ANCIENT_DEBRIS",
	"anvil":                         "ANVIL",
	"azalea":                        "AZALEA",
	"azure_bluet":                   "GRASS",
	"bamboo":                        "BAMBOO",
	"bamboo_fence":                  "BAMBOO_WOOD",
	"bamboo_mosaic":                 "BAMBOO_WOOD",
	"bamboo_mosaic_slab":            "BAMBOO_WOOD",
	"bamboo_planks":                 "BAMBOO_WOOD",
	"bamboo_sapling":                "BAMBOO_SAPLING",
	"bamboo_shelf":                  "SHELF",
	"bamboo_slab":                   "BAMBOO_WOOD",
	"barrel":                        "WOOD",
	"basalt":                        "BASALT",
	"bee_nest":                      "WOOD",
	"beehive":                       "WOOD",
	"beetroots":                     "CROP",
	"bell":                          "ANVIL",
	"big_dripleaf":                  "BIG_DRIPLEAF",
	"big_dripleaf_stem":             "BIG_DRIPLEAF",
	"birch_fence":                   "WOOD",
	"birch_planks":                  "WOOD",
	"birch_sapling":                 "GRASS",
	"birch_shelf":                   "SHELF",
	"birch_slab":                    "WOOD",
	"birch_wood":                    "WOOD",
	"black_banner":                  "WOOD",
	"black_carpet":                  "WOOL",
	"black_concrete_powder":         "SAND",
	"black_stained_glass_pane":      "GLASS",
	"black_wall_banner":             "WOOD",
	"black_wool":                    "WOOL",
	"blue_banner":                   "WOOD",
	"blue_carpet":                   "WOOL",
	"blue_concrete_powder":          "SAND",
	"blue_ice":                      "GLASS",
	"blue_orchid":                   "GRASS",
	"blue_stained_glass_pane":       "GLASS",
	"blue_wall_banner":              "WOOD",
	"blue_wool":                     "WOOL",
	"bone_block":                    "BONE_BLOCK",
	"bookshelf":                     "WOOD",
	"brain_coral":                   "WET_GRASS",
	"brain_coral_block":             "CORAL_BLOCK",
	"brain_coral_fan":               "WET_GRASS",
	"brain_coral_wall_fan":          "WET_GRASS",
	"brown_banner":                  "WOOD",
	"brown_carpet":                  "WOOL",
	"brown_concrete_powder":         "SAND",
	"brown_mushroom":                "GRASS",
	"brown_mushroom_block":          "WOOD",
	"brown_stained_glass_pane":      "GLASS",
	"brown_wall_banner":             "WOOD",
	"brown_wool":                    "WOOL",
	"bubble_column":                 "EMPTY",
	"bubble_coral":                  "WET_GRASS",
	"bubble_coral_block":            "CORAL_BLOCK",
	"bubble_coral_fan":              "WET_GRASS",
	"bubble_coral_wall_fan":         "WET_GRASS",
	"budding_amethyst":              "AMETHYST",
	"bush":                          "GRASS",
	"cactus":                        "WOOL",
	"cactus_flower":                 "CACTUS_FLOWER",
	"cake":                          "WOOL",
	"calcite":                       "CALCITE",
	"campfire":                      "WOOD",
	"carrots":                       "CROP",
	"cartography_table":             "WOOD",
	"carved_pumpkin":                "WOOD",
	"cave_vines":                    "CAVE_VINES",
	"cave_vines_plant":              "CAVE_VINES",
	"cherry_fence":                  "CHERRY_WOOD",
	"cherry_leaves":                 "CHERRY_LEAVES",
	"cherry_planks":                 "CHERRY_WOOD",
	"cherry_sapling":                "CHERRY_SAPLING",
	"cherry_shelf":                  "SHELF",
	"cherry_slab":                   "CHERRY_WOOD",
	"cherry_wood":                   "CHERRY_WOOD",
	"chest":                         "WOOD",
	"chipped_anvil":                 "ANVIL",
	"chiseled_bookshelf":            "CHISELED_BOOKSHELF",
	"chiseled_deepslate":            "DEEPSLATE_BRICKS",
	"chiseled_nether_bricks":        "NETHER_BRICKS",
	"chiseled_resin_bricks":         "RESIN_BRICKS",
	"chorus_flower":                 "WOOD",
	"chorus_plant":                  "WOOD",
	"clay":                          "GRAVEL",
	"closed_eyeblossom":             "GRASS",
	"coarse_dirt":                   "GRAVEL",
	"cobweb":                        "COBWEB",
	"cocoa":                         "WOOD",
	"comparator":                    "STONE",
	"composter":                     "WOOD",
	"copper_block":                  "COPPER",
	"copper_bulb":                   "COPPER_BULB",
	"copper_chest":                  "COPPER",
	"copper_golem_statue":           "COPPER_GOLEM_STATUE",
	"copper_grate":                  "COPPER_GRATE",
	"copper_torch":                  "WOOD",
	"copper_wall_torch":             "WOOD",
	"cornflower":                    "GRASS",
	"cracked_nether_bricks":         "NETHER_BRICKS",
	"crafting_table":                "WOOD",
	"creaking_heart":                "CREAKING_HEART",
	"crimson_fence":                 "NETHER_WOOD",
	"crimson_fungus":                "FUNGUS",
	"crimson_hyphae":                "STEM",
	"crimson_nylium":                "NYLIUM",
	"crimson_planks":                "NETHER_WOOD",
	"crimson_roots":                 "ROOTS",
	"crimson_shelf":                 "SHELF",
	"crimson_slab":                  "NETHER_WOOD",
	"cyan_banner":                   "WOOD",
	"cyan_carpet":                   "WOOL",
	"cyan_concrete_powder":          "SAND",
	"cyan_stained_glass_pane":       "GLASS",
	"cyan_wall_banner":              "WOOD",
	"cyan_wool":                     "WOOL",
	"damaged_anvil":                 "ANVIL",
	"dandelion":                     "GRASS",
	"dark_oak_fence":                "WOOD",
	"dark_oak_planks":               "WOOD",
	"dark_oak_sapling":              "GRASS",
	"dark_oak_shelf":                "SHELF",
	"dark_oak_slab":                 "WOOD",
	"dark_oak_wood":                 "WOOD",
	"daylight_detector":             "WOOD",
	"dead_bush":                     "GRASS",
	"deepslate":                     "DEEPSLATE",
	"deepslate_bricks":              "DEEPSLATE_BRICKS",
	"deepslate_coal_ore":            "DEEPSLATE",
	"deepslate_copper_ore":          "DEEPSLATE",
	"deepslate_diamond_ore":         "DEEPSLATE",
	"deepslate_emerald_ore":         "DEEPSLATE",
	"deepslate_gold_ore":            "DEEPSLATE",
	"deepslate_iron_ore":            "DEEPSLATE",
	"deepslate_lapis_ore":           "DEEPSLATE",
	"deepslate_redstone_ore":        "DEEPSLATE",
	"deepslate_tiles":               "DEEPSLATE_TILES",
	"detector_rail":                 "METAL",
	"diamond_block":                 "METAL",
	"dirt":                          "GRAVEL",
	"dirt_path":                     "GRASS",
	"dried_ghast":                   "DRIED_GHAST",
	"dried_kelp_block":              "GRASS",
	"dripstone_block":               "DRIPSTONE_BLOCK",
	"emerald_block":                 "METAL",
	"end_portal_frame":              "GLASS",
	"end_rod":                       "WOOD",
	"farmland":                      "GRAVEL",
	"fern":                          "GRASS",
	"fire":                          "WOOL",
	"fire_coral":                    "WET_GRASS",
	"fire_coral_block":              "CORAL_BLOCK",
	"fire_coral_fan":                "WET_GRASS",
	"fire_coral_wall_fan":           "WET_GRASS",
	"firefly_bush":                  "SWEET_BERRY_BUSH",
	"fletching_table":               "WOOD",
	"flowering_azalea":              "FLOWERING_AZALEA",
	"frogspawn":                     "FROGSPAWN",
	"frosted_ice":                   "GLASS",
	"gilded_blackstone":             "GILDED_BLACKSTONE",
	"glass":                         "GLASS",
	"glass_pane":                    "GLASS",
	"glow_lichen":                   "GLOW_LICHEN",
	"glowstone":                     "GLASS",
	"gold_block":                    "METAL",
	"grass_block":                   "GRASS",
	"gravel":                        "GRAVEL",
	"gray_banner":                   "WOOD",
	"gray_carpet":                   "WOOL",
	"gray_concrete_powder":          "SAND",
	"gray_stained_glass_pane":       "GLASS",
	"gray_wall_banner":              "WOOD",
	"gray_wool":                     "WOOL",
	"green_banner":                  "WOOD",
	"green_carpet":                  "WOOL",
	"green_concrete_powder":         "SAND",
	"green_stained_glass_pane":      "GLASS",
	"green_wall_banner":             "WOOD",
	"green_wool":                    "WOOL",
	"grindstone":                    "STONE",
	"hanging_roots":                 "HANGING_ROOTS",
	"hay_block":                     "GRASS",
	"heavy_core":                    "HEAVY_CORE",
	"honey_block":                   "HONEY_BLOCK",
	"honeycomb_block":               "CORAL_BLOCK",
	"hopper":                        "METAL",
	"horn_coral":                    "WET_GRASS",
	"horn_coral_block":              "CORAL_BLOCK",
	"horn_coral_fan":                "WET_GRASS",
	"horn_coral_wall_fan":           "WET_GRASS",
	"ice":                           "GLASS",
	"infested_deepslate":            "DEEPSLATE",
	"iron_bars":                     "IRON",
	"iron_block":                    "IRON",
	"iron_chain":                    "CHAIN",
	"jack_o_lantern":                "WOOD",
	"jukebox":                       "WOOD",
	"jungle_fence":                  "WOOD",
	"jungle_planks":                 "WOOD",
	"jungle_sapling":                "GRASS",
	"jungle_shelf":                  "SHELF",
	"jungle_slab":                   "WOOD",
	"jungle_wood":                   "WOOD",
	"kelp":                          "WET_GRASS",
	"kelp_plant":                    "WET_GRASS",
	"ladder":                        "LADDER",
	"lantern":                       "LANTERN",
	"large_amethyst_bud":            "MEDIUM_AMETHYST_BUD",
	"large_fern":                    "GRASS",
	"lava":                          "EMPTY",
	"leaf_litter":                   "LEAF_LITTER",
	"lectern":                       "WOOD",
	"lever":                         "STONE",
	"light_blue_banner":             "WOOD",
	"light_blue_carpet":             "WOOL",
	"light_blue_concrete_powder":    "SAND",
	"light_blue_stained_glass_pane": "GLASS",
	"light_blue_wall_banner":        "WOOD",
	"light_blue_wool":               "WOOL",
	"light_gray_banner":             "WOOD",
	"light_gray_carpet":             "WOOL",
	"light_gray_concrete_powder":    "SAND",
	"light_gray_stained_glass_pane": "GLASS",
	"light_gray_wall_banner":        "WOOD",
	"light_gray_wool":               "WOOL",
	"lightning_rod":                 "COPPER",
	"lilac":                         "GRASS",
	"lily_of_the_valley":            "GRASS",
	"lily_pad":                      "LILY_PAD",
	"lime_banner":                   "WOOD",
	"lime_carpet":                   "WOOL",
	"lime_concrete_powder":          "SAND",
	"lime_stained_glass_pane":       "GLASS",
	"lime_wall_banner":              "WOOD",
	"lime_wool":                     "WOOL",
	"lodestone":                     "LODESTONE",
	"loom":                          "WOOD",
	"magenta_banner":                "WOOD",
	"magenta_carpet":                "WOOL",
	"magenta_concrete_powder":       "SAND",
	"magenta_stained_glass_pane":    "GLASS",
	"magenta_wall_banner":           "WOOD",
	"magenta_wool":                  "WOOL",
	"mangrove_fence":                "WOOD",
	"mangrove_planks":               "WOOD",
	"mangrove_propagule":            "GRASS",
	"mangrove_roots":                "MANGROVE_ROOTS",
	"mangrove_shelf":                "SHELF",
	"mangrove_slab":                 "WOOD",
	"mangrove_wood":                 "WOOD",
	"medium_amethyst_bud":           "LARGE_AMETHYST_BUD",
	"moss_block":                    "MOSS",
	"moss_carpet":                   "MOSS_CARPET",
	"mud":                           "MUD",
	"mud_brick_slab":                "MUD_BRICKS",
	"mud_bricks":                    "MUD_BRICKS",
	"muddy_mangrove_roots":          "MUDDY_MANGROVE_ROOTS",
	"mushroom_stem":                 "WOOD",
	"mycelium":                      "GRASS",
	"nether_brick_fence":            "NETHER_BRICKS",
	"nether_brick_slab":             "NETHER_BRICKS",
	"nether_bricks":                 "NETHER_BRICKS",
	"nether_gold_ore":               "NETHER_GOLD_ORE",
	"nether_portal":                 "GLASS",
	"nether_quartz_ore":             "NETHER_ORE",
	"nether_sprouts":                "NETHER_SPROUTS",
	"nether_wart":                   "NETHER_WART",
	"nether_wart_block":             "WART_BLOCK",
	"netherite_block":               "NETHERITE_BLOCK",
	"netherrack":                    "NETHERRACK",
	"note_block":                    "WOOD",
	"oak_fence":                     "WOOD",
	"oak_planks":                    "WOOD",
	"oak_sapling":                   "GRASS",
	"oak_shelf":                     "SHELF",
	"oak_slab":                      "WOOD",
	"oak_wood":                      "WOOD",
	"ochre_froglight":               "FROGLIGHT",
	"open_eyeblossom":               "GRASS",
	"orange_banner":                 "WOOD",
	"orange_carpet":                 "WOOL",
	"orange_concrete_powder":        "SAND",
	"orange_stained_glass_pane":     "GLASS",
	"orange_tulip":                  "GRASS",
	"orange_wall_banner":            "WOOD",
	"orange_wool":                   "WOOL",
	"oxeye_daisy":                   "GRASS",
	"packed_ice":                    "GLASS",
	"packed_mud":                    "PACKED_MUD",
	"pale_hanging_moss":             "MOSS_CARPET",
	"pale_moss_block":               "MOSS",
	"pale_moss_carpet":              "MOSS_CARPET",
	"pale_oak_fence":                "WOOD",
	"pale_oak_leaves":               "GRASS",
	"pale_oak_planks":               "WOOD",
	"pale_oak_sapling":              "GRASS",
	"pale_oak_shelf":                "SHELF",
	"pale_oak_slab":                 "WOOD",
	"pale_oak_wood":                 "WOOD",
	"pearlescent_froglight":         "FROGLIGHT",
	"peony":                         "GRASS",
	"pink_banner":                   "WOOD",
	"pink_carpet":                   "WOOL",
	"pink_concrete_powder":          "SAND",
	"pink_petals":                   "PINK_PETALS",
	"pink_stained_glass_pane":       "GLASS",
	"pink_tulip":                    "GRASS",
	"pink_wall_banner":              "WOOD",
	"pink_wool":                     "WOOL",
	"pitcher_crop":                  "CROP",
	"pitcher_plant":                 "CROP",
	"podzol":                        "GRAVEL",
	"pointed_dripstone":             "POINTED_DRIPSTONE",
	"polished_basalt":               "BASALT",
	"polished_deepslate":            "POLISHED_DEEPSLATE",
	"polished_tuff":                 "POLISHED_TUFF",
	"poppy":                         "GRASS",
	"potatoes":                      "CROP",
	"powder_snow":                   "POWDER_SNOW",
	"powered_rail":                  "METAL",
	"purple_banner":                 "WOOD",
	"purple_carpet":                 "WOOL",
	"purple_concrete_powder":        "SAND",
	"purple_stained_glass_pane":     "GLASS",
	"purple_wall_banner":            "WOOD",
	"purple_wool":                   "WOOL",
	"rail":                          "METAL",
	"red_banner":                    "WOOD",
	"red_carpet":                    "WOOL",
	"red_concrete_powder":           "SAND",
	"red_mushroom":                  "GRASS",
	"red_mushroom_block":            "WOOD",
	"red_nether_bricks":             "NETHER_BRICKS",
	"red_sand":                      "SAND",
	"red_stained_glass_pane":        "GLASS",
	"red_tulip":                     "GRASS",
	"red_wall_banner":               "WOOD",
	"red_wool":                      "WOOL",
	"redstone_block":                "METAL",
	"redstone_lamp":                 "GLASS",
	"redstone_torch":                "WOOD",
	"redstone_wall_torch":           "WOOD",
	"reinforced_deepslate":          "DEEPSLATE",
	"repeater":                      "STONE",
	"resin_block":                   "RESIN",
	"resin_brick_slab":              "RESIN_BRICKS",
	"resin_brick_wall":              "RESIN_BRICKS",
	"resin_bricks":                  "RESIN_BRICKS",
	"resin_clump":                   "RESIN",
	"rooted_dirt":                   "ROOTED_DIRT",
	"rose_bush":                     "GRASS",
	"sand":                          "SAND",
	"scaffolding":                   "SCAFFOLDING",
	"sculk":                         "SCULK",
	"sculk_catalyst":                "SCULK_CATALYST",
	"sculk_sensor":                  "SCULK_SENSOR",
	"sculk_shrieker":                "SCULK_SHRIEKER",
	"sculk_vein":                    "SCULK_VEIN",
	"sea_lantern":                   "GLASS",
	"sea_pickle":                    "SLIME_BLOCK",
	"seagrass":                      "WET_GRASS",
	"short_dry_grass":               "GRASS",
	"short_grass":                   "GRASS",
	"shroomlight":                   "SHROOMLIGHT",
	"slime_block":                   "SLIME_BLOCK",
	"small_amethyst_bud":            "SMALL_AMETHYST_BUD",
	"small_dripleaf":                "SMALL_DRIPLEAF",
	"smithing_table":                "WOOD",
	"sniffer_egg":                   "METAL",
	"snow":                          "SNOW",
	"snow_block":                    "SNOW",
	"soul_campfire":                 "WOOD",
	"soul_fire":                     "WOOL",
	"soul_lantern":                  "LANTERN",
	"soul_sand":                     "SOUL_SAND",
	"soul_soil":                     "SOUL_SOIL",
	"soul_torch":                    "WOOD",
	"soul_wall_torch":               "WOOD",
	"spawner":                       "SPAWNER",
	"sponge":                        "SPONGE",
	"spore_blossom":                 "SPORE_BLOSSOM",
	"spruce_fence":                  "WOOD",
	"spruce_planks":                 "WOOD",
	"spruce_sapling":                "GRASS",
	"spruce_shelf":                  "SHELF",
	"spruce_slab":                   "WOOD",
	"spruce_wood":                   "WOOD",
	"stripped_acacia_wood":          "WOOD",
	"stripped_birch_wood":           "WOOD",
	"stripped_cherry_wood":          "CHERRY_WOOD",
	"stripped_crimson_hyphae":       "STEM",
	"stripped_dark_oak_wood":        "WOOD",
	"stripped_jungle_wood":          "WOOD",
	"stripped_oak_wood":             "WOOD",
	"stripped_pale_oak_wood":        "WOOD",
	"stripped_spruce_wood":          "WOOD",
	"stripped_warped_hyphae":        "STEM",
	"sugar_cane":                    "GRASS",
	"sunflower":                     "GRASS",
	"suspicious_gravel":             "SUSPICIOUS_GRAVEL",
	"suspicious_sand":               "SUSPICIOUS_SAND",
	"sweet_berry_bush":              "SWEET_BERRY_BUSH",
	"tall_dry_grass":                "GRASS",
	"tall_grass":                    "GRASS",
	"tall_seagrass":                 "WET_GRASS",
	"target":                        "GRASS",
	"tnt":                           "GRASS",
	"torch":                         "WOOD",
	"torchflower":                   "GRASS",
	"torchflower_crop":              "CROP",
	"trapped_chest":                 "WOOD",
	"trial_spawner":                 "TRIAL_SPAWNER",
	"tripwire_hook":                 "WOOD",
	"tube_coral":                    "WET_GRASS",
	"tube_coral_block":              "CORAL_BLOCK",
	"tube_coral_fan":                "WET_GRASS",
	"tube_coral_wall_fan":           "WET_GRASS",
	"tuff":                          "TUFF",
	"tuff_bricks":                   "TUFF_BRICKS",
	"turtle_egg":                    "METAL",
	"twisting_vines":                "WEEPING_VINES",
	"twisting_vines_plant":          "WEEPING_VINES",
	"vault":                         "VAULT",
	"verdant_froglight":             "FROGLIGHT",
	"vine":                          "VINE",
	"wall_torch":                    "WOOD",
	"warped_fence":                  "NETHER_WOOD",
	"warped_fungus":                 "FUNGUS",
	"warped_hyphae":                 "STEM",
	"warped_nylium":                 "NYLIUM",
	"warped_planks":                 "NETHER_WOOD",
	"warped_roots":                  "ROOTS",
	"warped_shelf":                  "SHELF",
	"warped_slab":                   "NETHER_WOOD",
	"warped_wart_block":             "WART_BLOCK",
	"water":                         "EMPTY",
	"weeping_vines":                 "WEEPING_VINES",
	"weeping_vines_plant":           "WEEPING_VINES",
	"wet_sponge":                    "WET_SPONGE",
	"wheat":                         "CROP",
	"white_banner":                  "WOOD",
	"white_carpet":                  "WOOL",
	"white_concrete_powder":         "SAND",
	"white_stained_glass_pane":      "GLASS",
	"white_tulip":                   "GRASS",
	"white_wall_banner":             "WOOD",
	"white_wool":                    "WOOL",
	"wildflowers":                   "PINK_PETALS",
	"wither_rose":                   "GRASS",
	"yellow_banner":                 "WOOD",
	"yellow_carpet":                 "WOOL",
	"yellow_concrete_powder":        "SAND",
	"yellow_stained_glass_pane":     "GLASS",
	"yellow_wall_banner":            "WOOD",
	"yellow_wool":                   "WOOL",
}

// soundTypeSteps is each sound type's volume, pitch and step sound event.
var soundTypeSteps = map[string]stepSound{
	"AMETHYST":                 {1, 1, "minecraft:block.amethyst_block.step"},
	"AMETHYST_CLUSTER":         {1, 1, "minecraft:block.amethyst_cluster.step"},
	"ANCIENT_DEBRIS":           {1, 1, "minecraft:block.ancient_debris.step"},
	"ANVIL":                    {0.3, 1, "minecraft:block.anvil.step"},
	"AZALEA":                   {1, 1, "minecraft:block.azalea.step"},
	"AZALEA_LEAVES":            {1, 1, "minecraft:block.azalea_leaves.step"},
	"BAMBOO":                   {1, 1, "minecraft:block.bamboo.step"},
	"BAMBOO_SAPLING":           {1, 1, "minecraft:block.bamboo.step"},
	"BAMBOO_WOOD":              {1, 1, "minecraft:block.bamboo_wood.step"},
	"BAMBOO_WOOD_HANGING_SIGN": {1, 1, "minecraft:block.bamboo_wood_hanging_sign.step"},
	"BASALT":                   {1, 1, "minecraft:block.basalt.step"},
	"BIG_DRIPLEAF":             {1, 1, "minecraft:block.big_dripleaf.step"},
	"BONE_BLOCK":               {1, 1, "minecraft:block.bone_block.step"},
	"CACTUS_FLOWER":            {1, 1, "minecraft:intentionally_empty"},
	"CALCITE":                  {1, 1, "minecraft:block.calcite.step"},
	"CANDLE":                   {1, 1, "minecraft:block.candle.step"},
	"CAVE_VINES":               {1, 1, "minecraft:block.cave_vines.step"},
	"CHAIN":                    {1, 1, "minecraft:block.chain.step"},
	"CHERRY_LEAVES":            {1, 1, "minecraft:block.cherry_leaves.step"},
	"CHERRY_SAPLING":           {1, 1, "minecraft:block.cherry_sapling.step"},
	"CHERRY_WOOD":              {1, 1, "minecraft:block.cherry_wood.step"},
	"CHERRY_WOOD_HANGING_SIGN": {1, 1, "minecraft:block.cherry_wood_hanging_sign.step"},
	"CHISELED_BOOKSHELF":       {1, 1, "minecraft:block.chiseled_bookshelf.step"},
	"COBWEB":                   {1, 1, "minecraft:block.cobweb.step"},
	"COPPER":                   {1, 1, "minecraft:block.copper.step"},
	"COPPER_BULB":              {1, 1, "minecraft:block.copper_bulb.step"},
	"COPPER_GOLEM_STATUE":      {1, 1, "minecraft:block.copper_golem_statue.step"},
	"COPPER_GRATE":             {1, 1, "minecraft:block.copper_grate.step"},
	"CORAL_BLOCK":              {1, 1, "minecraft:block.coral_block.step"},
	"CREAKING_HEART":           {1, 1, "minecraft:block.creaking_heart.step"},
	"CROP":                     {1, 1, "minecraft:block.grass.step"},
	"DECORATED_POT":            {1, 1, "minecraft:block.decorated_pot.step"},
	"DECORATED_POT_CRACKED":    {1, 1, "minecraft:block.decorated_pot.step"},
	"DEEPSLATE":                {1, 1, "minecraft:block.deepslate.step"},
	"DEEPSLATE_BRICKS":         {1, 1, "minecraft:block.deepslate_bricks.step"},
	"DEEPSLATE_TILES":          {1, 1, "minecraft:block.deepslate_tiles.step"},
	"DRIED_GHAST":              {1, 1, "minecraft:block.dried_ghast.step"},
	"DRIPSTONE_BLOCK":          {1, 1, "minecraft:block.dripstone_block.step"},
	"EMPTY":                    {1, 1, "minecraft:intentionally_empty"},
	"FLOWERING_AZALEA":         {1, 1, "minecraft:block.flowering_azalea.step"},
	"FROGLIGHT":                {1, 1, "minecraft:block.froglight.step"},
	"FROGSPAWN":                {1, 1, "minecraft:block.frogspawn.step"},
	"FUNGUS":                   {1, 1, "minecraft:block.fungus.step"},
	"GILDED_BLACKSTONE":        {1, 1, "minecraft:block.gilded_blackstone.step"},
	"GLASS":                    {1, 1, "minecraft:block.glass.step"},
	"GLOW_LICHEN":              {1, 1, "minecraft:block.vine.step"},
	"GRASS":                    {1, 1, "minecraft:block.grass.step"},
	"GRAVEL":                   {1, 1, "minecraft:block.gravel.step"},
	"HANGING_ROOTS":            {1, 1, "minecraft:block.hanging_roots.step"},
	"HANGING_SIGN":             {1, 1, "minecraft:block.hanging_sign.step"},
	"HARD_CROP":                {1, 1, "minecraft:block.wood.step"},
	"HEAVY_CORE":               {1, 1, "minecraft:block.heavy_core.step"},
	"HONEY_BLOCK":              {1, 1, "minecraft:block.honey_block.step"},
	"IRON":                     {1, 1, "minecraft:block.iron.step"},
	"LADDER":                   {1, 1, "minecraft:block.ladder.step"},
	"LANTERN":                  {1, 1, "minecraft:block.lantern.step"},
	"LARGE_AMETHYST_BUD":       {1, 1, "minecraft:block.amethyst_cluster.step"},
	"LEAF_LITTER":              {1, 1, "minecraft:block.leaf_litter.step"},
	"LILY_PAD":                 {1, 1, "minecraft:block.big_dripleaf.step"},
	"LODESTONE":                {1, 1, "minecraft:block.lodestone.step"},
	"MANGROVE_ROOTS":           {1, 1, "minecraft:block.mangrove_roots.step"},
	"MEDIUM_AMETHYST_BUD":      {1, 1, "minecraft:block.amethyst_cluster.step"},
	"METAL":                    {1, 1.5, "minecraft:block.metal.step"},
	"MOSS":                     {1, 1, "minecraft:block.moss.step"},
	"MOSS_CARPET":              {1, 1, "minecraft:block.moss_carpet.step"},
	"MUD":                      {1, 1, "minecraft:block.mud.step"},
	"MUDDY_MANGROVE_ROOTS":     {1, 1, "minecraft:block.muddy_mangrove_roots.step"},
	"MUD_BRICKS":               {1, 1, "minecraft:block.mud_bricks.step"},
	"NETHERITE_BLOCK":          {1, 1, "minecraft:block.netherite_block.step"},
	"NETHERRACK":               {1, 1, "minecraft:block.netherrack.step"},
	"NETHER_BRICKS":            {1, 1, "minecraft:block.nether_bricks.step"},
	"NETHER_GOLD_ORE":          {1, 1, "minecraft:block.nether_gold_ore.step"},
	"NETHER_ORE":               {1, 1, "minecraft:block.nether_ore.step"},
	"NETHER_SPROUTS":           {1, 1, "minecraft:block.nether_sprouts.step"},
	"NETHER_WART":              {1, 1, "minecraft:block.stone.step"},
	"NETHER_WOOD":              {1, 1, "minecraft:block.nether_wood.step"},
	"NETHER_WOOD_HANGING_SIGN": {1, 1, "minecraft:block.nether_wood_hanging_sign.step"},
	"NYLIUM":                   {1, 1, "minecraft:block.nylium.step"},
	"PACKED_MUD":               {1, 1, "minecraft:block.packed_mud.step"},
	"PINK_PETALS":              {1, 1, "minecraft:block.pink_petals.step"},
	"POINTED_DRIPSTONE":        {1, 1, "minecraft:block.pointed_dripstone.step"},
	"POLISHED_DEEPSLATE":       {1, 1, "minecraft:block.polished_deepslate.step"},
	"POLISHED_TUFF":            {1, 1, "minecraft:block.polished_tuff.step"},
	"POWDER_SNOW":              {1, 1, "minecraft:block.powder_snow.step"},
	"RESIN":                    {1, 1, "minecraft:block.resin.step"},
	"RESIN_BRICKS":             {1, 1, "minecraft:block.resin_bricks.step"},
	"ROOTED_DIRT":              {1, 1, "minecraft:block.rooted_dirt.step"},
	"ROOTS":                    {1, 1, "minecraft:block.roots.step"},
	"SAND":                     {1, 1, "minecraft:block.sand.step"},
	"SCAFFOLDING":              {1, 1, "minecraft:block.scaffolding.step"},
	"SCULK":                    {1, 1, "minecraft:block.sculk.step"},
	"SCULK_CATALYST":           {1, 1, "minecraft:block.sculk_catalyst.step"},
	"SCULK_SENSOR":             {1, 1, "minecraft:block.sculk_sensor.step"},
	"SCULK_SHRIEKER":           {1, 1, "minecraft:block.sculk_shrieker.step"},
	"SCULK_VEIN":               {1, 1, "minecraft:block.sculk_vein.step"},
	"SHELF":                    {1, 1, "minecraft:block.shelf.step"},
	"SHROOMLIGHT":              {1, 1, "minecraft:block.shroomlight.step"},
	"SLIME_BLOCK":              {1, 1, "minecraft:block.slime_block.step"},
	"SMALL_AMETHYST_BUD":       {1, 1, "minecraft:block.amethyst_cluster.step"},
	"SMALL_DRIPLEAF":           {1, 1, "minecraft:block.small_dripleaf.step"},
	"SNOW":                     {1, 1, "minecraft:block.snow.step"},
	"SOUL_SAND":                {1, 1, "minecraft:block.soul_sand.step"},
	"SOUL_SOIL":                {1, 1, "minecraft:block.soul_soil.step"},
	"SPAWNER":                  {1, 1, "minecraft:block.spawner.step"},
	"SPONGE":                   {1, 1, "minecraft:block.sponge.step"},
	"SPORE_BLOSSOM":            {1, 1, "minecraft:block.spore_blossom.step"},
	"STEM":                     {1, 1, "minecraft:block.stem.step"},
	"STONE":                    {1, 1, "minecraft:block.stone.step"},
	"SUSPICIOUS_GRAVEL":        {1, 1, "minecraft:block.suspicious_gravel.step"},
	"SUSPICIOUS_SAND":          {1, 1, "minecraft:block.suspicious_sand.step"},
	"SWEET_BERRY_BUSH":         {1, 1, "minecraft:block.grass.step"},
	"TRIAL_SPAWNER":            {1, 1, "minecraft:block.trial_spawner.step"},
	"TUFF":                     {1, 1, "minecraft:block.tuff.step"},
	"TUFF_BRICKS":              {1, 1, "minecraft:block.tuff_bricks.step"},
	"TWISTING_VINES":           {1, 0.5, "minecraft:block.weeping_vines.step"},
	"VAULT":                    {1, 1, "minecraft:block.vault.step"},
	"VINE":                     {1, 1, "minecraft:block.vine.step"},
	"WART_BLOCK":               {1, 1, "minecraft:block.wart_block.step"},
	"WEEPING_VINES":            {1, 1, "minecraft:block.weeping_vines.step"},
	"WET_GRASS":                {1, 1, "minecraft:block.wet_grass.step"},
	"WET_SPONGE":               {1, 1, "minecraft:block.wet_sponge.step"},
	"WOOD":                     {1, 1, "minecraft:block.wood.step"},
	"WOOL":                     {1, 1, "minecraft:block.wool.step"},
}

// soundTypePlaces is each sound type's place sound event. Its volume and
// pitch are the same pair soundTypeSteps carries — BlockItem.place scales
// them, it does not keep its own.
var soundTypePlaces = map[string]string{
	"AMETHYST":                 "minecraft:block.amethyst_block.place",
	"AMETHYST_CLUSTER":         "minecraft:block.amethyst_cluster.place",
	"ANCIENT_DEBRIS":           "minecraft:block.ancient_debris.place",
	"ANVIL":                    "minecraft:block.anvil.place",
	"AZALEA":                   "minecraft:block.azalea.place",
	"AZALEA_LEAVES":            "minecraft:block.azalea_leaves.place",
	"BAMBOO":                   "minecraft:block.bamboo.place",
	"BAMBOO_SAPLING":           "minecraft:block.bamboo_sapling.place",
	"BAMBOO_WOOD":              "minecraft:block.bamboo_wood.place",
	"BAMBOO_WOOD_HANGING_SIGN": "minecraft:block.bamboo_wood_hanging_sign.place",
	"BASALT":                   "minecraft:block.basalt.place",
	"BIG_DRIPLEAF":             "minecraft:block.big_dripleaf.place",
	"BONE_BLOCK":               "minecraft:block.bone_block.place",
	"CACTUS_FLOWER":            "minecraft:block.cactus_flower.place",
	"CALCITE":                  "minecraft:block.calcite.place",
	"CANDLE":                   "minecraft:block.candle.place",
	"CAVE_VINES":               "minecraft:block.cave_vines.place",
	"CHAIN":                    "minecraft:block.chain.place",
	"CHERRY_LEAVES":            "minecraft:block.cherry_leaves.place",
	"CHERRY_SAPLING":           "minecraft:block.cherry_sapling.place",
	"CHERRY_WOOD":              "minecraft:block.cherry_wood.place",
	"CHERRY_WOOD_HANGING_SIGN": "minecraft:block.cherry_wood_hanging_sign.place",
	"CHISELED_BOOKSHELF":       "minecraft:block.chiseled_bookshelf.place",
	"COBWEB":                   "minecraft:block.cobweb.place",
	"COPPER":                   "minecraft:block.copper.place",
	"COPPER_BULB":              "minecraft:block.copper_bulb.place",
	"COPPER_GOLEM_STATUE":      "minecraft:block.copper_golem_statue.place",
	"COPPER_GRATE":             "minecraft:block.copper_grate.place",
	"CORAL_BLOCK":              "minecraft:block.coral_block.place",
	"CREAKING_HEART":           "minecraft:block.creaking_heart.place",
	"CROP":                     "minecraft:item.crop.plant",
	"DECORATED_POT":            "minecraft:block.decorated_pot.place",
	"DECORATED_POT_CRACKED":    "minecraft:block.decorated_pot.place",
	"DEEPSLATE":                "minecraft:block.deepslate.place",
	"DEEPSLATE_BRICKS":         "minecraft:block.deepslate_bricks.place",
	"DEEPSLATE_TILES":          "minecraft:block.deepslate_tiles.place",
	"DRIED_GHAST":              "minecraft:intentionally_empty",
	"DRIPSTONE_BLOCK":          "minecraft:block.dripstone_block.place",
	"EMPTY":                    "minecraft:intentionally_empty",
	"FLOWERING_AZALEA":         "minecraft:block.flowering_azalea.place",
	"FROGLIGHT":                "minecraft:block.froglight.place",
	"FROGSPAWN":                "minecraft:block.frogspawn.place",
	"FUNGUS":                   "minecraft:block.fungus.place",
	"GILDED_BLACKSTONE":        "minecraft:block.gilded_blackstone.place",
	"GLASS":                    "minecraft:block.glass.place",
	"GLOW_LICHEN":              "minecraft:block.grass.place",
	"GRASS":                    "minecraft:block.grass.place",
	"GRAVEL":                   "minecraft:block.gravel.place",
	"HANGING_ROOTS":            "minecraft:block.hanging_roots.place",
	"HANGING_SIGN":             "minecraft:block.hanging_sign.place",
	"HARD_CROP":                "minecraft:item.crop.plant",
	"HEAVY_CORE":               "minecraft:block.heavy_core.place",
	"HONEY_BLOCK":              "minecraft:block.honey_block.place",
	"IRON":                     "minecraft:block.iron.place",
	"LADDER":                   "minecraft:block.ladder.place",
	"LANTERN":                  "minecraft:block.lantern.place",
	"LARGE_AMETHYST_BUD":       "minecraft:block.large_amethyst_bud.place",
	"LEAF_LITTER":              "minecraft:block.leaf_litter.place",
	"LILY_PAD":                 "minecraft:block.lily_pad.place",
	"LODESTONE":                "minecraft:block.lodestone.place",
	"MANGROVE_ROOTS":           "minecraft:block.mangrove_roots.place",
	"MEDIUM_AMETHYST_BUD":      "minecraft:block.medium_amethyst_bud.place",
	"METAL":                    "minecraft:block.metal.place",
	"MOSS":                     "minecraft:block.moss.place",
	"MOSS_CARPET":              "minecraft:block.moss_carpet.place",
	"MUD":                      "minecraft:block.mud.place",
	"MUDDY_MANGROVE_ROOTS":     "minecraft:block.muddy_mangrove_roots.place",
	"MUD_BRICKS":               "minecraft:block.mud_bricks.place",
	"NETHERITE_BLOCK":          "minecraft:block.netherite_block.place",
	"NETHERRACK":               "minecraft:block.netherrack.place",
	"NETHER_BRICKS":            "minecraft:block.nether_bricks.place",
	"NETHER_GOLD_ORE":          "minecraft:block.nether_gold_ore.place",
	"NETHER_ORE":               "minecraft:block.nether_ore.place",
	"NETHER_SPROUTS":           "minecraft:block.nether_sprouts.place",
	"NETHER_WART":              "minecraft:item.nether_wart.plant",
	"NETHER_WOOD":              "minecraft:block.nether_wood.place",
	"NETHER_WOOD_HANGING_SIGN": "minecraft:block.nether_wood_hanging_sign.place",
	"NYLIUM":                   "minecraft:block.nylium.place",
	"PACKED_MUD":               "minecraft:block.packed_mud.place",
	"PINK_PETALS":              "minecraft:block.pink_petals.place",
	"POINTED_DRIPSTONE":        "minecraft:block.pointed_dripstone.place",
	"POLISHED_DEEPSLATE":       "minecraft:block.polished_deepslate.place",
	"POLISHED_TUFF":            "minecraft:block.polished_tuff.place",
	"POWDER_SNOW":              "minecraft:block.powder_snow.place",
	"RESIN":                    "minecraft:block.resin.place",
	"RESIN_BRICKS":             "minecraft:block.resin_bricks.place",
	"ROOTED_DIRT":              "minecraft:block.rooted_dirt.place",
	"ROOTS":                    "minecraft:block.roots.place",
	"SAND":                     "minecraft:block.sand.place",
	"SCAFFOLDING":              "minecraft:block.scaffolding.place",
	"SCULK":                    "minecraft:block.sculk.place",
	"SCULK_CATALYST":           "minecraft:block.sculk_catalyst.place",
	"SCULK_SENSOR":             "minecraft:block.sculk_sensor.place",
	"SCULK_SHRIEKER":           "minecraft:block.sculk_shrieker.place",
	"SCULK_VEIN":               "minecraft:block.sculk_vein.place",
	"SHELF":                    "minecraft:block.shelf.place",
	"SHROOMLIGHT":              "minecraft:block.shroomlight.place",
	"SLIME_BLOCK":              "minecraft:block.slime_block.place",
	"SMALL_AMETHYST_BUD":       "minecraft:block.small_amethyst_bud.place",
	"SMALL_DRIPLEAF":           "minecraft:block.small_dripleaf.place",
	"SNOW":                     "minecraft:block.snow.place",
	"SOUL_SAND":                "minecraft:block.soul_sand.place",
	"SOUL_SOIL":                "minecraft:block.soul_soil.place",
	"SPAWNER":                  "minecraft:block.spawner.place",
	"SPONGE":                   "minecraft:block.sponge.place",
	"SPORE_BLOSSOM":            "minecraft:block.spore_blossom.place",
	"STEM":                     "minecraft:block.stem.place",
	"STONE":                    "minecraft:block.stone.place",
	"SUSPICIOUS_GRAVEL":        "minecraft:block.suspicious_gravel.place",
	"SUSPICIOUS_SAND":          "minecraft:block.suspicious_sand.place",
	"SWEET_BERRY_BUSH":         "minecraft:block.sweet_berry_bush.place",
	"TRIAL_SPAWNER":            "minecraft:block.trial_spawner.place",
	"TUFF":                     "minecraft:block.tuff.place",
	"TUFF_BRICKS":              "minecraft:block.tuff_bricks.place",
	"TWISTING_VINES":           "minecraft:block.weeping_vines.place",
	"VAULT":                    "minecraft:block.vault.place",
	"VINE":                     "minecraft:block.vine.place",
	"WART_BLOCK":               "minecraft:block.wart_block.place",
	"WEEPING_VINES":            "minecraft:block.weeping_vines.place",
	"WET_GRASS":                "minecraft:block.wet_grass.place",
	"WET_SPONGE":               "minecraft:block.wet_sponge.place",
	"WOOD":                     "minecraft:block.wood.place",
	"WOOL":                     "minecraft:block.wool.place",
}
