// Code generated by scripts/gen_villager_trades.py. DO NOT EDIT.
// Merchant trades read from the vanilla 26.3 data: villager_trade,
// trade_set and the villager_trade tags.

package server

// vTrade is one listing: the wanted item×count (the cost that demand and
// reputation move) → the given item×count, with a use limit before it locks
// and the trade-XP it grants the villager.
type vTrade struct {
	inItem, inCount, outItem, outCount, maxUses, xp int32
	// kind is vTradeFixed for a plain offer, or one of the rolled kinds
	// below, whose result is built when the villager unlocks the level.
	kind int32
	// aux is 1 + the row's index into the side table its kind uses (0 =
	// none): villagerMapListings for a map, villagerStewListings for a stew,
	// villagerPotionPools for a potion. For an enchanted book it is 1 when
	// the listing's double_trade_price_enchantments applies.
	aux int32
	// The listing's additional_wants (0 = none): the second cost, never
	// adjusted by demand or reputation.
	c2Item, c2Count int32
	// mult100 is the listing's reputation_discount — vanilla
	// MerchantOffer.priceMultiplier — in hundredths. It scales both the
	// demand markup and the reputation discount.
	mult100 int32
	// forTypes is the merchant_predicate: a bitmask of the villager types
	// (villagerType*) the listing is offered to, 0 = any.
	forTypes int32
}

const (
	vTradeFixed         int32 = 0 // no given_item_modifier
	vTradeEnchantedGear int32 = 1 // enchant_with_levels 5..19 from #on_traded_equipment
	vTradeTreasureMap   int32 = 2 // exploration_map
	vTradeDyedArmor     int32 = 3 // set_random_dyes
	vTradeStew          int32 = 4 // set_stew_effect
	vTradePotion        int32 = 5 // set_potion / set_random_potion
	vTradeEnchantedBook int32 = 6 // enchant_randomly from #tradeable
)

// vMapListing is an exploration_map's destination: the structure the map
// points at, the decoration that marks it, and the search radius in chunks.
type vMapListing struct {
	dest          string
	decor, radius int32
}

var villagerMapListings = []vMapListing{
	{"village_taiga", 31, 100},
	{"swamp_hut", 33, 100},
	{"village_snowy", 30, 100},
	{"village_savanna", 29, 100},
	{"village_plains", 28, 100},
	{"jungle_pyramid", 32, 100},
	{"village_desert", 27, 100},
	{"monument", 9, 100},
	{"trial_chambers", 34, 100},
	{"mansion", 8, 100},
}

// vStewEffect is one set_stew_effect entry: the vanilla effect name and its
// duration in ticks.
type vStewEffect struct {
	effect string
	ticks  int
}

// villagerStewListings is each stew listing's effects; the roll picks one.
var villagerStewListings = [][]vStewEffect{
	{{"night_vision", 100}, {"jump_boost", 160}, {"weakness", 140}, {"blindness", 120}, {"poison", 280}, {"saturation", 7}},
}

// villagerPotionPools is each potion listing's candidates by vanilla name
// (set_potion: one; set_random_potion: the options tag); the roll picks one.
var villagerPotionPools = [][]string{
	{"wind_charged", "oozing", "infested", "weaving", "night_vision", "long_night_vision", "invisibility", "long_invisibility", "fire_resistance", "long_fire_resistance", "leaping", "long_leaping", "strong_leaping", "slowness", "long_slowness", "strong_slowness", "turtle_master", "long_turtle_master", "strong_turtle_master", "swiftness", "long_swiftness", "strong_swiftness", "water_breathing", "long_water_breathing", "healing", "strong_healing", "harming", "strong_harming", "poison", "long_poison", "strong_poison", "regeneration", "long_regeneration", "strong_regeneration", "strength", "long_strength", "strong_strength", "weakness", "long_weakness", "slow_falling", "long_slow_falling"},
	{"long_invisibility"},
}

// set_random_dyes' number_of_dyes: base + binomial(trials, chance).
const (
	dyedArmorBaseDyes  = 1
	dyedArmorDyeTrials = 2
	dyedArmorDyeChance = 0.75
)

// profession names by tachyne index (persisted: order is fixed).
var professionNames = []string{
	"farmer",
	"fisherman",
	"shepherd",
	"fletcher",
	"librarian",
	"cartographer",
	"cleric",
	"armorer",
	"weaponsmith",
	"toolsmith",
	"mason",
	"butcher",
	"leatherworker",
}

// villagerTradeAmount[profession][level] is the trade_set's amount: how
// many offers a villager draws when it reaches that level.
var villagerTradeAmount = map[int]map[int]int{
	0:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // farmer
	1:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // fisherman
	2:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // shepherd
	3:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // fletcher
	4:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 3}, // librarian
	5:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // cartographer
	6:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // cleric
	7:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // armorer
	8:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // weaponsmith
	9:  {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // toolsmith
	10: {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // mason
	11: {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // butcher
	12: {1: 2, 2: 2, 3: 2, 4: 2, 5: 2}, // leatherworker
}

// villagerTrades[profession][level 1..5] = the listings that level draws from.
var villagerTrades = map[int]map[int][]vTrade{
	0: { // farmer
		1: {
			{itemByName["wheat"], 20, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["potato"], 26, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["carrot"], 22, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["beetroot"], 15, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["bread"], 6, 16, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["pumpkin"], 6, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["pumpkin_pie"], 4, 12, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["apple"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["emerald"], 3, itemByName["cookie"], 18, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["melon"], 4, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["emerald"], 3, itemByName["cake"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["suspicious_stew"], 1, 12, 15, vTradeStew, 1, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 3, itemByName["golden_carrot"], 3, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 4, itemByName["glistering_melon_slice"], 3, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	1: { // fisherman
		1: {
			{itemByName["string"], 20, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["coal"], 10, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["cod"], 6, itemByName["cooked_cod"], 6, 16, 1, vTradeFixed, 0, itemByName["emerald"], 1, 5, 0},
			{itemByName["emerald"], 3, itemByName["cod_bucket"], 1, 16, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["cod"], 15, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["salmon"], 6, itemByName["cooked_salmon"], 6, 16, 5, vTradeFixed, 0, itemByName["emerald"], 1, 5, 0},
			{itemByName["emerald"], 2, itemByName["campfire"], 1, 12, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["salmon"], 13, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["fishing_rod"], 1, 3, 10, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
		4: {
			{itemByName["tropical_fish"], 6, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["pufferfish"], 4, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["oak_boat"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 4},
			{itemByName["spruce_boat"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 80},
			{itemByName["jungle_boat"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 3},
			{itemByName["acacia_boat"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 8},
			{itemByName["dark_oak_boat"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 32},
		},
	},
	2: { // shepherd
		1: {
			{itemByName["white_wool"], 18, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["brown_wool"], 18, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["gray_wool"], 18, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["black_wool"], 18, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 2, itemByName["shears"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["white_dye"], 12, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["gray_dye"], 12, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["black_dye"], 12, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["light_blue_dye"], 12, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["lime_dye"], 12, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["white_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["orange_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["magenta_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_blue_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["yellow_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["lime_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["pink_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["gray_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_gray_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cyan_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["purple_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["blue_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["brown_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["green_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["red_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["black_wool"], 1, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["white_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["orange_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["magenta_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_blue_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["yellow_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["lime_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["pink_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["gray_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_gray_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cyan_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["purple_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["blue_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["brown_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["green_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["red_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["black_carpet"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["yellow_dye"], 12, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["light_gray_dye"], 12, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["orange_dye"], 12, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["red_dye"], 12, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["pink_dye"], 12, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["white_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["orange_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["magenta_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["light_blue_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["yellow_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["lime_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["pink_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["gray_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["light_gray_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["cyan_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["purple_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["blue_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["brown_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["green_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["red_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["black_bed"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["brown_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["purple_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["blue_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["green_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["magenta_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["cyan_dye"], 12, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["white_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["orange_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["magenta_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["light_blue_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["yellow_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["lime_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["pink_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["gray_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["light_gray_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["cyan_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["purple_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["blue_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["brown_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["green_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["red_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["black_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 2, itemByName["painting"], 3, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	3: { // fletcher
		1: {
			{itemByName["stick"], 32, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["arrow"], 16, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["gravel"], 10, itemByName["flint"], 10, 12, 1, vTradeFixed, 0, itemByName["emerald"], 1, 5, 0},
		},
		2: {
			{itemByName["flint"], 26, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 2, itemByName["bow"], 1, 12, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["string"], 14, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["crossbow"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["feather"], 24, itemByName["emerald"], 1, 16, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 2, itemByName["bow"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["tripwire_hook"], 8, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["crossbow"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 2, itemByName["tipped_arrow"], 5, 12, 30, vTradePotion, 1, itemByName["arrow"], 5, 5, 0},
		},
	},
	4: { // librarian
		1: {
			{itemByName["paper"], 24, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 0, itemByName["enchanted_book"], 1, 12, 1, vTradeEnchantedBook, 1, itemByName["book"], 1, 20, 0},
			{itemByName["emerald"], 9, itemByName["bookshelf"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["book"], 4, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 0, itemByName["enchanted_book"], 1, 12, 5, vTradeEnchantedBook, 1, itemByName["book"], 1, 20, 0},
			{itemByName["emerald"], 1, itemByName["lantern"], 1, 12, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["ink_sac"], 5, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 0, itemByName["enchanted_book"], 1, 12, 10, vTradeEnchantedBook, 1, itemByName["book"], 1, 20, 0},
			{itemByName["emerald"], 1, itemByName["glass"], 4, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["writable_book"], 2, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 0, itemByName["enchanted_book"], 1, 12, 15, vTradeEnchantedBook, 1, itemByName["book"], 1, 20, 0},
			{itemByName["emerald"], 5, itemByName["clock"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 4, itemByName["compass"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 3, itemByName["yellow_candle"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["red_candle"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	5: { // cartographer
		1: {
			{itemByName["paper"], 24, itemByName["emerald"], 1, 12, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 7, itemByName["map"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["glass_pane"], 11, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 8, itemByName["taiga_village_map"], 1, 12, 5, vTradeTreasureMap, 1, itemByName["compass"], 1, 20, 52},
			{itemByName["emerald"], 8, itemByName["swamp_hut_map"], 1, 12, 5, vTradeTreasureMap, 2, itemByName["compass"], 1, 20, 82},
			{itemByName["emerald"], 8, itemByName["snowy_village_map"], 1, 12, 5, vTradeTreasureMap, 3, itemByName["compass"], 1, 20, 96},
			{itemByName["emerald"], 8, itemByName["savanna_village_map"], 1, 12, 5, vTradeTreasureMap, 4, itemByName["compass"], 1, 20, 7},
			{itemByName["emerald"], 8, itemByName["plains_village_map"], 1, 12, 5, vTradeTreasureMap, 5, itemByName["compass"], 1, 20, 89},
			{itemByName["emerald"], 8, itemByName["jungle_pyramid_map"], 1, 12, 5, vTradeTreasureMap, 6, itemByName["compass"], 1, 20, 41},
			{itemByName["emerald"], 8, itemByName["desert_village_map"], 1, 12, 5, vTradeTreasureMap, 7, itemByName["compass"], 1, 20, 10},
		},
		3: {
			{itemByName["compass"], 1, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 13, itemByName["ocean_monument_map"], 1, 12, 10, vTradeTreasureMap, 8, itemByName["compass"], 1, 20, 0},
			{itemByName["emerald"], 12, itemByName["buried_trial_chambers_map"], 1, 12, 10, vTradeTreasureMap, 9, itemByName["compass"], 1, 20, 0},
		},
		4: {
			{itemByName["emerald"], 7, itemByName["item_frame"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 2, itemByName["white_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 20},
			{itemByName["emerald"], 2, itemByName["orange_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 9},
			{itemByName["emerald"], 2, itemByName["magenta_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 8},
			{itemByName["emerald"], 2, itemByName["blue_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 80},
			{itemByName["emerald"], 2, itemByName["light_blue_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 48},
			{itemByName["emerald"], 2, itemByName["yellow_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 6},
			{itemByName["emerald"], 2, itemByName["lime_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 65},
			{itemByName["emerald"], 2, itemByName["pink_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 68},
			{itemByName["emerald"], 2, itemByName["gray_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 1},
			{itemByName["emerald"], 2, itemByName["cyan_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 17},
			{itemByName["emerald"], 2, itemByName["purple_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 96},
			{itemByName["emerald"], 2, itemByName["brown_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 6},
			{itemByName["emerald"], 2, itemByName["green_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 11},
			{itemByName["emerald"], 2, itemByName["red_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 24},
			{itemByName["emerald"], 2, itemByName["black_banner"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 32},
		},
		5: {
			{itemByName["emerald"], 8, itemByName["globe_banner_pattern"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 14, itemByName["woodland_mansion_map"], 1, 12, 30, vTradeTreasureMap, 10, itemByName["compass"], 1, 20, 0},
		},
	},
	6: { // cleric
		1: {
			{itemByName["rotten_flesh"], 32, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["redstone"], 2, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["gold_ingot"], 3, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["lapis_lazuli"], 1, 12, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["rabbit_foot"], 2, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 4, itemByName["glowstone"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["turtle_scute"], 4, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["glass_bottle"], 9, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 5, itemByName["ender_pearl"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["nether_wart"], 22, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["experience_bottle"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	7: { // armorer
		1: {
			{itemByName["coal"], 15, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 7, itemByName["iron_leggings"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 4, itemByName["iron_boots"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 5, itemByName["iron_helmet"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 9, itemByName["iron_chestplate"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
		},
		2: {
			{itemByName["iron_ingot"], 4, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 36, itemByName["bell"], 1, 12, 5, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 1, itemByName["chainmail_boots"], 1, 12, 5, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 3, itemByName["chainmail_leggings"], 1, 12, 5, vTradeFixed, 0, 0, 0, 20, 0},
		},
		3: {
			{itemByName["lava_bucket"], 1, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["chainmail_helmet"], 1, 12, 10, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 4, itemByName["chainmail_chestplate"], 1, 12, 10, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 5, itemByName["shield"], 1, 12, 10, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["diamond"], 1, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["emerald"], 14, itemByName["diamond_leggings"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 8, itemByName["diamond_boots"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
		5: {
			{itemByName["emerald"], 8, itemByName["diamond_helmet"], 1, 3, 30, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 16, itemByName["diamond_chestplate"], 1, 3, 30, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
	},
	8: { // weaponsmith
		1: {
			{itemByName["coal"], 15, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["iron_axe"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 2, itemByName["iron_sword"], 1, 12, 1, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
		2: {
			{itemByName["iron_ingot"], 4, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 36, itemByName["bell"], 1, 12, 5, vTradeFixed, 0, 0, 0, 20, 0},
		},
		3: {
			{itemByName["flint"], 24, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["emerald"], 12, itemByName["diamond_axe"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["diamond"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 8, itemByName["diamond_sword"], 1, 3, 30, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
	},
	9: { // toolsmith
		1: {
			{itemByName["coal"], 15, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["stone_axe"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 1, itemByName["stone_shovel"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 1, itemByName["stone_pickaxe"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 1, itemByName["stone_hoe"], 1, 12, 1, vTradeFixed, 0, 0, 0, 20, 0},
		},
		2: {
			{itemByName["iron_ingot"], 4, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 36, itemByName["bell"], 1, 12, 5, vTradeFixed, 0, 0, 0, 20, 0},
		},
		3: {
			{itemByName["flint"], 30, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["iron_axe"], 1, 3, 10, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 2, itemByName["iron_shovel"], 1, 3, 10, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 3, itemByName["iron_pickaxe"], 1, 3, 10, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 4, itemByName["diamond_hoe"], 1, 3, 10, vTradeFixed, 0, 0, 0, 20, 0},
		},
		4: {
			{itemByName["emerald"], 12, itemByName["diamond_axe"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 5, itemByName["diamond_shovel"], 1, 3, 15, vTradeEnchantedGear, 0, 0, 0, 20, 0},
			{itemByName["diamond"], 1, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 13, itemByName["diamond_pickaxe"], 1, 3, 30, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		},
	},
	10: { // mason
		1: {
			{itemByName["clay_ball"], 10, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["brick"], 10, 16, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["stone"], 20, itemByName["emerald"], 1, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["chiseled_stone_bricks"], 4, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["granite"], 16, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["andesite"], 16, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["diorite"], 16, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["dripstone_block"], 4, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["polished_andesite"], 4, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["polished_diorite"], 4, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["polished_granite"], 4, 16, 10, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["quartz"], 12, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["white_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["orange_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["magenta_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_blue_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["yellow_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["lime_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["pink_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["gray_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_gray_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cyan_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["purple_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["blue_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["brown_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["green_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["red_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["black_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["white_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["orange_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["magenta_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_blue_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["yellow_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["lime_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["pink_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["gray_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["light_gray_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cyan_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["purple_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["blue_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["brown_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["green_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["red_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["black_glazed_terracotta"], 1, 12, 15, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["emerald"], 1, itemByName["quartz_pillar"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["quartz_block"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	11: { // butcher
		1: {
			{itemByName["chicken"], 14, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["porkchop"], 7, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["rabbit"], 4, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["rabbit_stew"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		},
		2: {
			{itemByName["coal"], 15, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cooked_porkchop"], 5, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 1, itemByName["cooked_chicken"], 8, 16, 5, vTradeFixed, 0, 0, 0, 5, 0},
		},
		3: {
			{itemByName["mutton"], 7, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["beef"], 10, itemByName["emerald"], 1, 16, 20, vTradeFixed, 0, 0, 0, 5, 0},
		},
		4: {
			{itemByName["dried_kelp_block"], 10, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
		5: {
			{itemByName["sweet_berries"], 10, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
		},
	},
	12: { // leatherworker
		1: {
			{itemByName["leather"], 6, itemByName["emerald"], 1, 16, 2, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 3, itemByName["leather_leggings"], 1, 12, 1, vTradeDyedArmor, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 7, itemByName["leather_chestplate"], 1, 12, 1, vTradeDyedArmor, 0, 0, 0, 20, 0},
		},
		2: {
			{itemByName["flint"], 26, itemByName["emerald"], 1, 12, 10, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 5, itemByName["leather_helmet"], 1, 12, 5, vTradeDyedArmor, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 4, itemByName["leather_boots"], 1, 12, 5, vTradeDyedArmor, 0, 0, 0, 20, 0},
		},
		3: {
			{itemByName["rabbit_hide"], 9, itemByName["emerald"], 1, 12, 20, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 7, itemByName["leather_chestplate"], 1, 12, 1, vTradeDyedArmor, 0, 0, 0, 20, 0},
		},
		4: {
			{itemByName["turtle_scute"], 4, itemByName["emerald"], 1, 12, 30, vTradeFixed, 0, 0, 0, 5, 0},
			{itemByName["emerald"], 6, itemByName["leather_horse_armor"], 1, 12, 15, vTradeDyedArmor, 0, 0, 0, 20, 0},
		},
		5: {
			{itemByName["emerald"], 6, itemByName["saddle"], 1, 12, 30, vTradeFixed, 0, 0, 0, 20, 0},
			{itemByName["emerald"], 5, itemByName["leather_helmet"], 1, 12, 5, vTradeDyedArmor, 0, 0, 0, 20, 0},
		},
	},
}

// vTradeSet is a trade_set: draw amount offers from trades.
type vTradeSet struct {
	amount int
	trades []vTrade
}

// traderTradeSets is the wandering trader's pools, in the order
// WanderingTrader.updateTrades adds them: buying, uncommon, common.
var traderTradeSets = []vTradeSet{
	{2, []vTrade{
		{itemByName["water_bucket"], 1, itemByName["emerald"], 2, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["milk_bucket"], 1, itemByName["emerald"], 2, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["fermented_spider_eye"], 1, itemByName["emerald"], 3, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["baked_potato"], 4, itemByName["emerald"], 1, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["hay_block"], 1, itemByName["emerald"], 1, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
	}},
	{2, []vTrade{
		{itemByName["emerald"], 1, itemByName["packed_ice"], 1, 6, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 6, itemByName["blue_ice"], 1, 6, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["gunpowder"], 4, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["podzol"], 3, 6, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["acacia_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["birch_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["dark_oak_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["jungle_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["oak_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["spruce_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["cherry_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["mangrove_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pale_oak_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["poplar_log"], 8, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["iron_pickaxe"], 1, 1, 1, vTradeEnchantedGear, 0, 0, 0, 20, 0},
		{itemByName["emerald"], 5, itemByName["potion"], 1, 1, 1, vTradePotion, 2, 0, 0, 5, 0},
	}},
	{5, []vTrade{
		{itemByName["emerald"], 1, itemByName["white_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["orange_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["magenta_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["light_blue_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["yellow_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["lime_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pink_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["gray_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["light_gray_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["cyan_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["purple_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["blue_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["brown_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["green_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["red_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["black_dye"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["tropical_fish_bucket"], 1, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["pufferfish_bucket"], 1, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 2, itemByName["sea_pickle"], 1, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 4, itemByName["slime_ball"], 1, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 2, itemByName["glowstone"], 1, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["nautilus_shell"], 1, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["fern"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["sugar_cane"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pumpkin"], 1, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["kelp"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["cactus"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["dandelion"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["poppy"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["blue_orchid"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["allium"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["azure_bluet"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["red_tulip"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["orange_tulip"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["white_tulip"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pink_tulip"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["oxeye_daisy"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["cornflower"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["lily_of_the_valley"], 1, 7, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["open_eyeblossom"], 1, 7, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["wheat_seeds"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["beetroot_seeds"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pumpkin_seeds"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["melon_seeds"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["acacia_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["birch_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["dark_oak_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["jungle_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["oak_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["spruce_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["cherry_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["pale_oak_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["mangrove_propagule"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 5, itemByName["poplar_sapling"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["brain_coral_block"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["bubble_coral_block"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["fire_coral_block"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["horn_coral_block"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["tube_coral_block"], 1, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["vine"], 3, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pale_hanging_moss"], 3, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["brown_mushroom"], 3, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["red_mushroom"], 3, 4, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["lily_pad"], 5, 2, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["small_dripleaf"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["sand"], 8, 8, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["red_sand"], 4, 6, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pointed_dripstone"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["sulfur_spike"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["rooted_dirt"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["moss_block"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["pale_moss_block"], 2, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["wildflowers"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["tall_dry_grass"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 3, itemByName["firefly_bush"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 2, itemByName["golden_dandelion"], 1, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["name_tag"], 1, 5, 1, vTradeFixed, 0, 0, 0, 5, 0},
		{itemByName["emerald"], 1, itemByName["shelf_mushroom"], 3, 12, 1, vTradeFixed, 0, 0, 0, 5, 0},
	}},
}
