// Code generated by scripts/gen_flammable.py. DO NOT EDIT.
// Fire flammability (ignite/burn odds) transcribed from vanilla's
// 1.21.5 FireBlock.setFlammable registrations, mapped to block-state id
// ranges via Mojang's datagen block report.

package worldgen

// flammable is one contiguous block-state id range with its fire odds.
type flammable struct{ lo, hi, ignite, burn uint32 }

// flammableRanges is sorted by lo for binary search (see Flammability).
var flammableRanges = []flammable{
	{15, 15, 5, 20},         // oak_planks
	{16, 16, 5, 20},         // spruce_planks
	{17, 17, 5, 20},         // birch_planks
	{18, 18, 5, 20},         // jungle_planks
	{19, 19, 5, 20},         // acacia_planks
	{20, 20, 5, 20},         // cherry_planks
	{21, 21, 5, 20},         // dark_oak_planks
	{22, 24, 5, 5},          // pale_oak_wood
	{25, 25, 5, 20},         // pale_oak_planks
	{26, 26, 5, 20},         // mangrove_planks
	{27, 27, 5, 20},         // bamboo_planks
	{28, 28, 5, 20},         // bamboo_mosaic
	{136, 138, 5, 5},        // oak_log
	{139, 141, 5, 5},        // spruce_log
	{142, 144, 5, 5},        // birch_log
	{145, 147, 5, 5},        // jungle_log
	{148, 150, 5, 5},        // acacia_log
	{151, 153, 5, 5},        // cherry_log
	{154, 156, 5, 5},        // dark_oak_log
	{157, 159, 5, 5},        // pale_oak_log
	{160, 162, 5, 5},        // mangrove_log
	{163, 164, 5, 20},       // mangrove_roots
	{168, 170, 5, 5},        // bamboo_block
	{171, 173, 5, 5},        // stripped_spruce_log
	{174, 176, 5, 5},        // stripped_birch_log
	{177, 179, 5, 5},        // stripped_jungle_log
	{180, 182, 5, 5},        // stripped_acacia_log
	{183, 185, 5, 5},        // stripped_cherry_log
	{186, 188, 5, 5},        // stripped_dark_oak_log
	{189, 191, 5, 5},        // stripped_pale_oak_log
	{192, 194, 5, 5},        // stripped_oak_log
	{195, 197, 5, 5},        // stripped_mangrove_log
	{198, 200, 5, 5},        // stripped_bamboo_block
	{201, 203, 5, 5},        // oak_wood
	{204, 206, 5, 5},        // spruce_wood
	{207, 209, 5, 5},        // birch_wood
	{210, 212, 5, 5},        // jungle_wood
	{213, 215, 5, 5},        // acacia_wood
	{216, 218, 5, 5},        // cherry_wood
	{219, 221, 5, 5},        // dark_oak_wood
	{222, 224, 5, 5},        // mangrove_wood
	{225, 227, 5, 5},        // stripped_oak_wood
	{228, 230, 5, 5},        // stripped_spruce_wood
	{231, 233, 5, 5},        // stripped_birch_wood
	{234, 236, 5, 5},        // stripped_jungle_wood
	{237, 239, 5, 5},        // stripped_acacia_wood
	{240, 242, 5, 5},        // stripped_cherry_wood
	{243, 245, 5, 5},        // stripped_dark_oak_wood
	{246, 248, 5, 5},        // stripped_pale_oak_wood
	{249, 251, 5, 5},        // stripped_mangrove_wood
	{252, 279, 30, 60},      // oak_leaves
	{280, 307, 30, 60},      // spruce_leaves
	{308, 335, 30, 60},      // birch_leaves
	{336, 363, 30, 60},      // jungle_leaves
	{364, 391, 30, 60},      // acacia_leaves
	{392, 419, 30, 60},      // cherry_leaves
	{420, 447, 30, 60},      // dark_oak_leaves
	{448, 475, 30, 60},      // pale_oak_leaves
	{476, 503, 30, 60},      // mangrove_leaves
	{504, 531, 30, 60},      // azalea_leaves
	{532, 559, 30, 60},      // flowering_azalea_leaves
	{2048, 2048, 60, 100},   // short_grass
	{2049, 2049, 60, 100},   // fern
	{2050, 2050, 60, 100},   // dead_bush
	{2051, 2051, 60, 100},   // bush
	{2052, 2052, 60, 100},   // short_dry_grass
	{2053, 2053, 60, 100},   // tall_dry_grass
	{2093, 2093, 30, 60},    // white_wool
	{2094, 2094, 30, 60},    // orange_wool
	{2095, 2095, 30, 60},    // magenta_wool
	{2096, 2096, 30, 60},    // light_blue_wool
	{2097, 2097, 30, 60},    // yellow_wool
	{2098, 2098, 30, 60},    // lime_wool
	{2099, 2099, 30, 60},    // pink_wool
	{2100, 2100, 30, 60},    // gray_wool
	{2101, 2101, 30, 60},    // light_gray_wool
	{2102, 2102, 30, 60},    // cyan_wool
	{2103, 2103, 30, 60},    // purple_wool
	{2104, 2104, 30, 60},    // blue_wool
	{2105, 2105, 30, 60},    // brown_wool
	{2106, 2106, 30, 60},    // green_wool
	{2107, 2107, 30, 60},    // red_wool
	{2108, 2108, 30, 60},    // black_wool
	{2121, 2121, 60, 100},   // dandelion
	{2122, 2122, 60, 100},   // torchflower
	{2123, 2123, 60, 100},   // poppy
	{2124, 2124, 60, 100},   // blue_orchid
	{2125, 2125, 60, 100},   // allium
	{2126, 2126, 60, 100},   // azure_bluet
	{2127, 2127, 60, 100},   // red_tulip
	{2128, 2128, 60, 100},   // orange_tulip
	{2129, 2129, 60, 100},   // white_tulip
	{2130, 2130, 60, 100},   // pink_tulip
	{2131, 2131, 60, 100},   // oxeye_daisy
	{2132, 2132, 60, 100},   // cornflower
	{2133, 2133, 60, 100},   // wither_rose
	{2134, 2134, 60, 100},   // lily_of_the_valley
	{2140, 2141, 15, 100},   // tnt
	{2142, 2142, 30, 20},    // bookshelf
	{3706, 3785, 5, 20},     // oak_stairs
	{6744, 6744, 60, 100},   // cactus_flower
	{6764, 6795, 5, 20},     // oak_fence
	{8157, 8188, 15, 100},   // vine
	{8189, 8316, 15, 100},   // glow_lichen
	{8445, 8476, 5, 20},     // oak_fence_gate
	{9527, 9606, 5, 20},     // spruce_stairs
	{9607, 9686, 5, 20},     // birch_stairs
	{9687, 9766, 5, 20},     // jungle_stairs
	{11770, 11849, 5, 20},   // acacia_stairs
	{11850, 11929, 5, 20},   // cherry_stairs
	{11930, 12009, 5, 20},   // dark_oak_stairs
	{12010, 12089, 5, 20},   // pale_oak_stairs
	{12090, 12169, 5, 20},   // mangrove_stairs
	{12170, 12249, 5, 20},   // bamboo_stairs
	{12250, 12329, 5, 20},   // bamboo_mosaic_stairs
	{12691, 12693, 60, 20},  // hay_block
	{12694, 12694, 60, 20},  // white_carpet
	{12695, 12695, 60, 20},  // orange_carpet
	{12696, 12696, 60, 20},  // magenta_carpet
	{12697, 12697, 60, 20},  // light_blue_carpet
	{12698, 12698, 60, 20},  // yellow_carpet
	{12699, 12699, 60, 20},  // lime_carpet
	{12700, 12700, 60, 20},  // pink_carpet
	{12701, 12701, 60, 20},  // gray_carpet
	{12702, 12702, 60, 20},  // light_gray_carpet
	{12703, 12703, 60, 20},  // cyan_carpet
	{12704, 12704, 60, 20},  // purple_carpet
	{12705, 12705, 60, 20},  // blue_carpet
	{12706, 12706, 60, 20},  // brown_carpet
	{12707, 12707, 60, 20},  // green_carpet
	{12708, 12708, 60, 20},  // red_carpet
	{12709, 12709, 60, 20},  // black_carpet
	{12711, 12711, 5, 5},    // coal_block
	{12713, 12714, 60, 100}, // sunflower
	{12715, 12716, 60, 100}, // lilac
	{12717, 12718, 60, 100}, // rose_bush
	{12719, 12720, 60, 100}, // peony
	{12721, 12722, 60, 100}, // tall_grass
	{12723, 12724, 60, 100}, // large_fern
	{13128, 13133, 5, 20},   // oak_slab
	{13134, 13139, 5, 20},   // spruce_slab
	{13140, 13145, 5, 20},   // birch_slab
	{13146, 13151, 5, 20},   // jungle_slab
	{13152, 13157, 5, 20},   // acacia_slab
	{13158, 13163, 5, 20},   // cherry_slab
	{13164, 13169, 5, 20},   // dark_oak_slab
	{13170, 13175, 5, 20},   // pale_oak_slab
	{13176, 13181, 5, 20},   // mangrove_slab
	{13182, 13187, 5, 20},   // bamboo_slab
	{13188, 13193, 5, 20},   // bamboo_mosaic_slab
	{13282, 13313, 5, 20},   // spruce_fence_gate
	{13314, 13345, 5, 20},   // birch_fence_gate
	{13346, 13377, 5, 20},   // jungle_fence_gate
	{13378, 13409, 5, 20},   // acacia_fence_gate
	{13410, 13441, 5, 20},   // cherry_fence_gate
	{13442, 13473, 5, 20},   // dark_oak_fence_gate
	{13474, 13505, 5, 20},   // pale_oak_fence_gate
	{13506, 13537, 5, 20},   // mangrove_fence_gate
	{13538, 13569, 5, 20},   // bamboo_fence_gate
	{13570, 13601, 5, 20},   // spruce_fence
	{13602, 13633, 5, 20},   // birch_fence
	{13634, 13665, 5, 20},   // jungle_fence
	{13666, 13697, 5, 20},   // acacia_fence
	{13698, 13729, 5, 20},   // cherry_fence
	{13730, 13761, 5, 20},   // dark_oak_fence
	{13762, 13793, 5, 20},   // pale_oak_fence
	{13794, 13825, 5, 20},   // mangrove_fence
	{13826, 13857, 5, 20},   // bamboo_fence
	{14607, 14608, 60, 100}, // pitcher_plant
	{14887, 14887, 30, 60},  // dried_kelp_block
	{15077, 15088, 60, 60},  // bamboo
	{20504, 20535, 60, 60},  // scaffolding
	{20582, 20597, 30, 20},  // lectern
	{20739, 20742, 60, 100}, // sweet_berry_bush
	{21541, 21549, 5, 20},   // composter
	{21550, 21565, 15, 20},  // target
	{21566, 21589, 30, 20},  // bee_nest
	{21590, 21613, 5, 20},   // beehive
	{27554, 27605, 15, 60},  // cave_vines
	{27606, 27607, 15, 60},  // cave_vines_plant
	{27608, 27608, 60, 100}, // spore_blossom
	{27609, 27609, 30, 60},  // azalea
	{27610, 27610, 30, 60},  // flowering_azalea
	{27612, 27627, 60, 100}, // pink_petals
	{27628, 27643, 60, 100}, // wildflowers
	{27644, 27659, 60, 100}, // leaf_litter
	{27661, 27692, 60, 100}, // big_dripleaf
	{27693, 27700, 60, 100}, // big_dripleaf_stem
	{27701, 27716, 60, 100}, // small_dripleaf
	{27717, 27718, 30, 60},  // hanging_roots
	{29501, 29501, 5, 100},  // pale_moss_block
	{29502, 29663, 5, 100},  // pale_moss_carpet
	{29664, 29665, 5, 100},  // pale_hanging_moss
	{29666, 29666, 60, 100}, // open_eyeblossom
	{29667, 29667, 60, 100}, // closed_eyeblossom
	{29670, 29670, 60, 100}, // firefly_bush
}

// Flammability returns a block state's fire ignite odds (chance the block
// catches from a neighbouring fire) and burn odds (chance an adjacent fire
// consumes it), both 0 for non-flammable blocks. Mirrors FireBlock's
// igniteOdds/burnOdds maps.
func Flammability(state uint32) (ignite, burn uint32) {
	lo, hi := 0, len(flammableRanges)-1
	for lo <= hi {
		mid := (lo + hi) / 2
		r := flammableRanges[mid]
		switch {
		case state < r.lo:
			hi = mid - 1
		case state > r.hi:
			lo = mid + 1
		default:
			return r.ignite, r.burn
		}
	}
	return 0, 0
}
