// Code generated by scripts/gen_flammable.py. DO NOT EDIT.
// Fire flammability (ignite/burn odds) transcribed from vanilla's
// 1.21.5 FireBlock.setFlammable registrations, mapped to block-state id
// ranges via Mojang's datagen block report.

package worldgen

// flammable is one contiguous block-state id range with its fire odds.
type flammable struct{ lo, hi, ignite, burn uint32 }

// flammableRanges is sorted by lo for binary search (see Flammability).
var flammableRanges = []flammable{
	{15, 15, 5, 20},         // oak_planks
	{16, 16, 5, 20},         // spruce_planks
	{17, 17, 5, 20},         // birch_planks
	{18, 18, 5, 20},         // jungle_planks
	{19, 19, 5, 20},         // acacia_planks
	{20, 20, 5, 20},         // cherry_planks
	{21, 21, 5, 20},         // dark_oak_planks
	{22, 24, 5, 5},          // pale_oak_wood
	{25, 25, 5, 20},         // pale_oak_planks
	{26, 26, 5, 20},         // mangrove_planks
	{28, 28, 5, 20},         // bamboo_planks
	{29, 29, 5, 20},         // bamboo_mosaic
	{139, 141, 5, 5},        // oak_log
	{142, 144, 5, 5},        // spruce_log
	{145, 147, 5, 5},        // birch_log
	{148, 150, 5, 5},        // jungle_log
	{151, 153, 5, 5},        // acacia_log
	{154, 156, 5, 5},        // cherry_log
	{157, 159, 5, 5},        // dark_oak_log
	{160, 162, 5, 5},        // pale_oak_log
	{163, 165, 5, 5},        // mangrove_log
	{169, 170, 5, 20},       // mangrove_roots
	{174, 176, 5, 5},        // bamboo_block
	{177, 179, 5, 5},        // stripped_spruce_log
	{180, 182, 5, 5},        // stripped_birch_log
	{183, 185, 5, 5},        // stripped_jungle_log
	{186, 188, 5, 5},        // stripped_acacia_log
	{189, 191, 5, 5},        // stripped_cherry_log
	{192, 194, 5, 5},        // stripped_dark_oak_log
	{195, 197, 5, 5},        // stripped_pale_oak_log
	{198, 200, 5, 5},        // stripped_oak_log
	{201, 203, 5, 5},        // stripped_mangrove_log
	{207, 209, 5, 5},        // stripped_bamboo_block
	{210, 212, 5, 5},        // oak_wood
	{213, 215, 5, 5},        // spruce_wood
	{216, 218, 5, 5},        // birch_wood
	{219, 221, 5, 5},        // jungle_wood
	{222, 224, 5, 5},        // acacia_wood
	{225, 227, 5, 5},        // cherry_wood
	{228, 230, 5, 5},        // dark_oak_wood
	{231, 233, 5, 5},        // mangrove_wood
	{237, 239, 5, 5},        // stripped_oak_wood
	{240, 242, 5, 5},        // stripped_spruce_wood
	{243, 245, 5, 5},        // stripped_birch_wood
	{246, 248, 5, 5},        // stripped_jungle_wood
	{249, 251, 5, 5},        // stripped_acacia_wood
	{252, 254, 5, 5},        // stripped_cherry_wood
	{255, 257, 5, 5},        // stripped_dark_oak_wood
	{258, 260, 5, 5},        // stripped_pale_oak_wood
	{261, 263, 5, 5},        // stripped_mangrove_wood
	{267, 294, 30, 60},      // oak_leaves
	{295, 322, 30, 60},      // spruce_leaves
	{323, 350, 30, 60},      // birch_leaves
	{351, 378, 30, 60},      // jungle_leaves
	{379, 406, 30, 60},      // acacia_leaves
	{407, 434, 30, 60},      // cherry_leaves
	{435, 462, 30, 60},      // dark_oak_leaves
	{463, 490, 30, 60},      // pale_oak_leaves
	{491, 518, 30, 60},      // mangrove_leaves
	{603, 630, 30, 60},      // azalea_leaves
	{631, 658, 30, 60},      // flowering_azalea_leaves
	{2363, 2363, 60, 100},   // short_grass
	{2364, 2364, 60, 100},   // fern
	{2365, 2365, 60, 100},   // dead_bush
	{2366, 2366, 60, 100},   // bush
	{2368, 2368, 60, 100},   // short_dry_grass
	{2369, 2369, 60, 100},   // tall_dry_grass
	{2409, 2409, 30, 60},    // white_wool
	{2410, 2410, 30, 60},    // orange_wool
	{2411, 2411, 30, 60},    // magenta_wool
	{2412, 2412, 30, 60},    // light_blue_wool
	{2413, 2413, 30, 60},    // yellow_wool
	{2414, 2414, 30, 60},    // lime_wool
	{2415, 2415, 30, 60},    // pink_wool
	{2416, 2416, 30, 60},    // gray_wool
	{2417, 2417, 30, 60},    // light_gray_wool
	{2418, 2418, 30, 60},    // cyan_wool
	{2419, 2419, 30, 60},    // purple_wool
	{2420, 2420, 30, 60},    // blue_wool
	{2421, 2421, 30, 60},    // brown_wool
	{2422, 2422, 30, 60},    // green_wool
	{2423, 2423, 30, 60},    // red_wool
	{2424, 2424, 30, 60},    // black_wool
	{3813, 3813, 60, 100},   // dandelion
	{3815, 3815, 60, 100},   // torchflower
	{3816, 3816, 60, 100},   // poppy
	{3817, 3817, 60, 100},   // blue_orchid
	{3818, 3818, 60, 100},   // allium
	{3819, 3819, 60, 100},   // azure_bluet
	{3820, 3820, 60, 100},   // red_tulip
	{3821, 3821, 60, 100},   // orange_tulip
	{3822, 3822, 60, 100},   // white_tulip
	{3823, 3823, 60, 100},   // pink_tulip
	{3824, 3824, 60, 100},   // oxeye_daisy
	{3825, 3825, 60, 100},   // cornflower
	{3826, 3826, 60, 100},   // wither_rose
	{3827, 3827, 60, 100},   // lily_of_the_valley
	{3833, 3834, 15, 100},   // tnt
	{3835, 3835, 30, 20},    // bookshelf
	{5463, 5542, 5, 20},     // oak_stairs
	{8615, 8615, 60, 100},   // cactus_flower
	{8635, 8666, 5, 20},     // oak_fence
	{10092, 10123, 15, 100}, // vine
	{10124, 10251, 15, 100}, // glow_lichen
	{10380, 10411, 5, 20},   // oak_fence_gate
	{11470, 11549, 5, 20},   // spruce_stairs
	{11550, 11629, 5, 20},   // birch_stairs
	{11630, 11709, 5, 20},   // jungle_stairs
	{13739, 13818, 5, 20},   // acacia_stairs
	{13819, 13898, 5, 20},   // cherry_stairs
	{13899, 13978, 5, 20},   // dark_oak_stairs
	{13979, 14058, 5, 20},   // pale_oak_stairs
	{14059, 14138, 5, 20},   // mangrove_stairs
	{14219, 14298, 5, 20},   // bamboo_stairs
	{14299, 14378, 5, 20},   // bamboo_mosaic_stairs
	{14740, 14742, 60, 20},  // hay_block
	{14743, 14743, 60, 20},  // white_carpet
	{14744, 14744, 60, 20},  // orange_carpet
	{14745, 14745, 60, 20},  // magenta_carpet
	{14746, 14746, 60, 20},  // light_blue_carpet
	{14747, 14747, 60, 20},  // yellow_carpet
	{14748, 14748, 60, 20},  // lime_carpet
	{14749, 14749, 60, 20},  // pink_carpet
	{14750, 14750, 60, 20},  // gray_carpet
	{14751, 14751, 60, 20},  // light_gray_carpet
	{14752, 14752, 60, 20},  // cyan_carpet
	{14753, 14753, 60, 20},  // purple_carpet
	{14754, 14754, 60, 20},  // blue_carpet
	{14755, 14755, 60, 20},  // brown_carpet
	{14756, 14756, 60, 20},  // green_carpet
	{14757, 14757, 60, 20},  // red_carpet
	{14758, 14758, 60, 20},  // black_carpet
	{14760, 14760, 5, 5},    // coal_block
	{14762, 14763, 60, 100}, // sunflower
	{14764, 14765, 60, 100}, // lilac
	{14766, 14767, 60, 100}, // rose_bush
	{14768, 14769, 60, 100}, // peony
	{14770, 14771, 60, 100}, // tall_grass
	{14772, 14773, 60, 100}, // large_fern
	{15177, 15182, 5, 20},   // oak_slab
	{15183, 15188, 5, 20},   // spruce_slab
	{15189, 15194, 5, 20},   // birch_slab
	{15195, 15200, 5, 20},   // jungle_slab
	{15201, 15206, 5, 20},   // acacia_slab
	{15207, 15212, 5, 20},   // cherry_slab
	{15213, 15218, 5, 20},   // dark_oak_slab
	{15219, 15224, 5, 20},   // pale_oak_slab
	{15225, 15230, 5, 20},   // mangrove_slab
	{15237, 15242, 5, 20},   // bamboo_slab
	{15243, 15248, 5, 20},   // bamboo_mosaic_slab
	{15331, 15362, 5, 20},   // spruce_fence_gate
	{15363, 15394, 5, 20},   // birch_fence_gate
	{15395, 15426, 5, 20},   // jungle_fence_gate
	{15427, 15458, 5, 20},   // acacia_fence_gate
	{15459, 15490, 5, 20},   // cherry_fence_gate
	{15491, 15522, 5, 20},   // dark_oak_fence_gate
	{15523, 15554, 5, 20},   // pale_oak_fence_gate
	{15555, 15586, 5, 20},   // mangrove_fence_gate
	{15619, 15650, 5, 20},   // bamboo_fence_gate
	{15651, 15682, 5, 20},   // spruce_fence
	{15683, 15714, 5, 20},   // birch_fence
	{15715, 15746, 5, 20},   // jungle_fence
	{15747, 15778, 5, 20},   // acacia_fence
	{15779, 15810, 5, 20},   // cherry_fence
	{15811, 15842, 5, 20},   // dark_oak_fence
	{15843, 15874, 5, 20},   // pale_oak_fence
	{15875, 15906, 5, 20},   // mangrove_fence
	{15939, 15970, 5, 20},   // bamboo_fence
	{16790, 16791, 60, 100}, // pitcher_plant
	{18446, 18446, 30, 60},  // dried_kelp_block
	{18636, 18647, 60, 60},  // bamboo
	{24063, 24094, 60, 60},  // scaffolding
	{24141, 24156, 30, 20},  // lectern
	{24298, 24301, 60, 100}, // sweet_berry_bush
	{25100, 25108, 5, 20},   // composter
	{25109, 25124, 15, 20},  // target
	{25125, 25148, 30, 20},  // bee_nest
	{25149, 25172, 5, 20},   // beehive
	{33606, 33657, 15, 60},  // cave_vines
	{33658, 33659, 15, 60},  // cave_vines_plant
	{33660, 33660, 60, 100}, // spore_blossom
	{33661, 33661, 30, 60},  // azalea
	{33662, 33662, 30, 60},  // flowering_azalea
	{33664, 33679, 60, 100}, // pink_petals
	{33680, 33695, 60, 100}, // wildflowers
	{33696, 33711, 60, 100}, // leaf_litter
	{33713, 33744, 60, 100}, // big_dripleaf
	{33745, 33752, 60, 100}, // big_dripleaf_stem
	{33753, 33768, 60, 100}, // small_dripleaf
	{33769, 33770, 30, 60},  // hanging_roots
	{35553, 35553, 5, 100},  // pale_moss_block
	{35554, 35715, 5, 100},  // pale_moss_carpet
	{35716, 35717, 5, 100},  // pale_hanging_moss
	{35718, 35718, 60, 100}, // open_eyeblossom
	{35719, 35719, 60, 100}, // closed_eyeblossom
	{35722, 35722, 60, 100}, // firefly_bush
}

// Flammability returns a block state's fire ignite odds (chance the block
// catches from a neighbouring fire) and burn odds (chance an adjacent fire
// consumes it), both 0 for non-flammable blocks. Mirrors FireBlock's
// igniteOdds/burnOdds maps.
func Flammability(state uint32) (ignite, burn uint32) {
	lo, hi := 0, len(flammableRanges)-1
	for lo <= hi {
		mid := (lo + hi) / 2
		r := flammableRanges[mid]
		switch {
		case state < r.lo:
			hi = mid - 1
		case state > r.hi:
			lo = mid + 1
		default:
			return r.ignite, r.burn
		}
	}
	return 0, 0
}
