// Code generated by scripts/gen_ignited.py; DO NOT EDIT.

package worldgen

// ignitedRanges lists, as sorted inclusive state-id runs, the states of the
// 366 blocks vanilla registers ignitedByLava, taken from the game itself.
var ignitedRanges = []struct{ Min, Max uint32 }{
	{15, 29},
	{139, 170},
	{174, 658},
	{680, 2301},
	{2363, 2369},
	{2409, 3800},
	{3833, 4923},
	{5463, 5566},
	{6866, 6866},
	{6891, 7306},
	{7415, 8014},
	{8143, 8414},
	{8431, 8438},
	{8529, 8550},
	{8615, 8615},
	{8633, 8666},
	{8784, 9487},
	{9500, 9691},
	{10092, 10411},
	{11470, 11709},
	{12974, 12997},
	{13046, 13077},
	{13739, 14378},
	{14743, 14758},
	{14762, 15093},
	{15177, 15248},
	{15331, 16610},
	{16790, 16791},
	{18635, 18647},
	{24095, 24110},
	{24127, 24128},
	{24141, 24157},
	{24234, 24297},
	{25100, 25108},
	{25125, 25172},
	{33769, 33770},
	{35553, 35717},
	{35722, 35722},
}

// IgnitedByLava is BlockStateBase.ignitedByLava: lava's random tick may
// set fire beside this block.
func IgnitedByLava(state uint32) bool {
	lo, hi := 0, len(ignitedRanges)-1
	for lo <= hi {
		mid := (lo + hi) / 2
		r := ignitedRanges[mid]
		switch {
		case state < r.Min:
			hi = mid - 1
		case state > r.Max:
			lo = mid + 1
		default:
			return true
		}
	}
	return false
}
