// Code generated by scripts/gen_light.py; DO NOT EDIT.

package worldgen

// lightRanges maps block-state ID ranges to the light level they emit, sorted
// by lo and non-overlapping so LightEmission can binary-search them.
var lightRanges = []struct {
	lo, hi uint32
	lvl    uint8
}{
	{102, 117, 15},     // lava
	{2135, 2135, 1},    // brown_mushroom
	{3169, 3169, 14},   // torch
	{3170, 3173, 14},   // wall_torch
	{3174, 3685, 15},   // fire
	{3686, 3686, 10},   // soul_fire
	{6684, 6685, 7},    // redstone_torch
	{6686, 6693, 7},    // redstone_wall_torch
	{6805, 6805, 10},   // soul_torch
	{6806, 6809, 10},   // soul_wall_torch
	{6810, 6810, 14},   // copper_torch
	{6811, 6814, 14},   // copper_wall_torch
	{6815, 6815, 15},   // glowstone
	{6816, 6817, 11},   // nether_portal
	{6822, 6825, 15},   // jack_o_lantern
	{9250, 9250, 7},    // enchanting_table
	{9251, 9258, 1},    // brewing_stand
	{9263, 9263, 15},   // lava_cauldron
	{9267, 9267, 15},   // end_portal
	{9268, 9275, 1},    // end_portal_frame
	{9277, 9277, 1},    // dragon_egg
	{9374, 9381, 7},    // ender_chest
	{9779, 9779, 15},   // beacon
	{12333, 12364, 15}, // light
	{12690, 12690, 15}, // sea_lantern
	{14434, 14439, 14}, // end_rod
	{14614, 14614, 15}, // end_gateway
	{14643, 14643, 3},  // magma_block
	{15065, 15072, 6},  // sea_pickle
	{15074, 15075, 15}, // conduit
	{20635, 20638, 15}, // lantern
	{20639, 20642, 10}, // soul_lantern
	{20643, 20646, 15}, // copper_lantern
	{20647, 20650, 15}, // exposed_copper_lantern
	{20651, 20654, 15}, // weathered_copper_lantern
	{20655, 20658, 15}, // oxidized_copper_lantern
	{20659, 20662, 15}, // waxed_copper_lantern
	{20663, 20666, 15}, // waxed_exposed_copper_lantern
	{20667, 20670, 15}, // waxed_weathered_copper_lantern
	{20671, 20674, 15}, // waxed_oxidized_copper_lantern
	{20675, 20706, 15}, // campfire
	{20707, 20738, 10}, // soul_campfire
	{20774, 20774, 15}, // shroomlight
	{21618, 21618, 10}, // crying_obsidian
	{23202, 23213, 5},  // amethyst_cluster
	{23214, 23225, 4},  // large_amethyst_bud
	{23226, 23237, 2},  // medium_amethyst_bud
	{23238, 23249, 1},  // small_amethyst_bud
	{24488, 24583, 1},  // sculk_sensor
	{24584, 24967, 1},  // calibrated_sculk_sensor
	{25097, 25098, 6},  // sculk_catalyst
	{29380, 29382, 15}, // ochre_froglight
	{29383, 29385, 15}, // verdant_froglight
	{29386, 29388, 15}, // pearlescent_froglight
	{29467, 29498, 6},  // vault
	{29670, 29670, 2},  // firefly_bush
}

// LightEmission returns the block-light level a state emits, 0 if it emits none.
func LightEmission(state uint32) uint8 {
	lo, hi := 0, len(lightRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		r := lightRanges[mid]
		switch {
		case state < r.lo:
			hi = mid
		case state > r.hi:
			lo = mid + 1
		default:
			return r.lvl
		}
	}
	return 0
}
