// Code generated by scripts/gen_light.py; DO NOT EDIT.

package worldgen

// lightRanges maps block-state ID ranges to the light level they emit, sorted
// by lo and non-overlapping so LightEmission can binary-search them.
//
// Light is per STATE, not per block: a furnace emits 13 only while lit, a
// candle 3/6/9/12 by how many are lit, a respawn anchor 3/7/11/15 by charge.
// So one block can contribute several ranges.
var lightRanges = []struct {
	lo, hi uint32
	lvl    uint8
}{
	{105, 120, 15},     // lava
	{3828, 3828, 1},    // brown_mushroom
	{4926, 4926, 14},   // torch
	{4927, 4930, 14},   // wall_torch
	{4931, 5442, 15},   // fire
	{5443, 5443, 10},   // soul_fire
	{6883, 6883, 13},   // furnace
	{6885, 6885, 13},   // furnace
	{6887, 6887, 13},   // furnace
	{6889, 6889, 13},   // furnace
	{8551, 8551, 9},    // redstone_ore
	{8553, 8553, 9},    // deepslate_redstone_ore
	{8555, 8555, 7},    // redstone_torch
	{8557, 8557, 7},    // redstone_wall_torch
	{8559, 8559, 7},    // redstone_wall_torch
	{8561, 8561, 7},    // redstone_wall_torch
	{8563, 8563, 7},    // redstone_wall_torch
	{8676, 8676, 10},   // soul_torch
	{8677, 8680, 10},   // soul_wall_torch
	{8681, 8681, 14},   // copper_torch
	{8682, 8685, 14},   // copper_wall_torch
	{8686, 8686, 15},   // glowstone
	{8687, 8688, 11},   // nether_portal
	{8693, 8696, 15},   // jack_o_lantern
	{10124, 10248, 7},  // glow_lichen
	{10250, 10250, 7},  // glow_lichen
	{11185, 11185, 7},  // enchanting_table
	{11186, 11193, 1},  // brewing_stand
	{11198, 11198, 15}, // lava_cauldron
	{11202, 11202, 15}, // end_portal
	{11203, 11210, 1},  // end_portal_frame
	{11212, 11212, 1},  // dragon_egg
	{11213, 11213, 15}, // redstone_lamp
	{11317, 11324, 7},  // ender_chest
	{11722, 11722, 15}, // beacon
	{14384, 14385, 1},  // light
	{14386, 14387, 2},  // light
	{14388, 14389, 3},  // light
	{14390, 14391, 4},  // light
	{14392, 14393, 5},  // light
	{14394, 14395, 6},  // light
	{14396, 14397, 7},  // light
	{14398, 14399, 8},  // light
	{14400, 14401, 9},  // light
	{14402, 14403, 10}, // light
	{14404, 14405, 11}, // light
	{14406, 14407, 12}, // light
	{14408, 14409, 13}, // light
	{14410, 14411, 14}, // light
	{14412, 14413, 15}, // light
	{14739, 14739, 15}, // sea_lantern
	{16611, 16616, 14}, // end_rod
	{16797, 16797, 15}, // end_gateway
	{16826, 16826, 3},  // magma_block
	{18624, 18624, 6},  // sea_pickle
	{18626, 18626, 9},  // sea_pickle
	{18628, 18628, 12}, // sea_pickle
	{18630, 18630, 15}, // sea_pickle
	{18633, 18634, 15}, // conduit
	{24111, 24111, 13}, // smoker
	{24113, 24113, 13}, // smoker
	{24115, 24115, 13}, // smoker
	{24117, 24117, 13}, // smoker
	{24119, 24119, 13}, // blast_furnace
	{24121, 24121, 13}, // blast_furnace
	{24123, 24123, 13}, // blast_furnace
	{24125, 24125, 13}, // blast_furnace
	{24194, 24197, 15}, // lantern
	{24198, 24201, 10}, // soul_lantern
	{24202, 24205, 15}, // copper_lantern
	{24206, 24209, 15}, // exposed_copper_lantern
	{24210, 24213, 15}, // weathered_copper_lantern
	{24214, 24217, 15}, // oxidized_copper_lantern
	{24218, 24221, 15}, // waxed_copper_lantern
	{24222, 24225, 15}, // waxed_exposed_copper_lantern
	{24226, 24229, 15}, // waxed_weathered_copper_lantern
	{24230, 24233, 15}, // waxed_oxidized_copper_lantern
	{24234, 24237, 15}, // campfire
	{24242, 24245, 15}, // campfire
	{24250, 24253, 15}, // campfire
	{24258, 24261, 15}, // campfire
	{24266, 24269, 10}, // soul_campfire
	{24274, 24277, 10}, // soul_campfire
	{24282, 24285, 10}, // soul_campfire
	{24290, 24293, 10}, // soul_campfire
	{24333, 24333, 15}, // shroomlight
	{25177, 25177, 10}, // crying_obsidian
	{25179, 25179, 3},  // respawn_anchor
	{25180, 25180, 7},  // respawn_anchor
	{25181, 25181, 11}, // respawn_anchor
	{25182, 25182, 15}, // respawn_anchor
	{26453, 26454, 3},  // candle
	{26457, 26458, 6},  // candle
	{26461, 26462, 9},  // candle
	{26465, 26466, 12}, // candle
	{26469, 26470, 3},  // white_candle
	{26473, 26474, 6},  // white_candle
	{26477, 26478, 9},  // white_candle
	{26481, 26482, 12}, // white_candle
	{26485, 26486, 3},  // orange_candle
	{26489, 26490, 6},  // orange_candle
	{26493, 26494, 9},  // orange_candle
	{26497, 26498, 12}, // orange_candle
	{26501, 26502, 3},  // magenta_candle
	{26505, 26506, 6},  // magenta_candle
	{26509, 26510, 9},  // magenta_candle
	{26513, 26514, 12}, // magenta_candle
	{26517, 26518, 3},  // light_blue_candle
	{26521, 26522, 6},  // light_blue_candle
	{26525, 26526, 9},  // light_blue_candle
	{26529, 26530, 12}, // light_blue_candle
	{26533, 26534, 3},  // yellow_candle
	{26537, 26538, 6},  // yellow_candle
	{26541, 26542, 9},  // yellow_candle
	{26545, 26546, 12}, // yellow_candle
	{26549, 26550, 3},  // lime_candle
	{26553, 26554, 6},  // lime_candle
	{26557, 26558, 9},  // lime_candle
	{26561, 26562, 12}, // lime_candle
	{26565, 26566, 3},  // pink_candle
	{26569, 26570, 6},  // pink_candle
	{26573, 26574, 9},  // pink_candle
	{26577, 26578, 12}, // pink_candle
	{26581, 26582, 3},  // gray_candle
	{26585, 26586, 6},  // gray_candle
	{26589, 26590, 9},  // gray_candle
	{26593, 26594, 12}, // gray_candle
	{26597, 26598, 3},  // light_gray_candle
	{26601, 26602, 6},  // light_gray_candle
	{26605, 26606, 9},  // light_gray_candle
	{26609, 26610, 12}, // light_gray_candle
	{26613, 26614, 3},  // cyan_candle
	{26617, 26618, 6},  // cyan_candle
	{26621, 26622, 9},  // cyan_candle
	{26625, 26626, 12}, // cyan_candle
	{26629, 26630, 3},  // purple_candle
	{26633, 26634, 6},  // purple_candle
	{26637, 26638, 9},  // purple_candle
	{26641, 26642, 12}, // purple_candle
	{26645, 26646, 3},  // blue_candle
	{26649, 26650, 6},  // blue_candle
	{26653, 26654, 9},  // blue_candle
	{26657, 26658, 12}, // blue_candle
	{26661, 26662, 3},  // brown_candle
	{26665, 26666, 6},  // brown_candle
	{26669, 26670, 9},  // brown_candle
	{26673, 26674, 12}, // brown_candle
	{26677, 26678, 3},  // green_candle
	{26681, 26682, 6},  // green_candle
	{26685, 26686, 9},  // green_candle
	{26689, 26690, 12}, // green_candle
	{26693, 26694, 3},  // red_candle
	{26697, 26698, 6},  // red_candle
	{26701, 26702, 9},  // red_candle
	{26705, 26706, 12}, // red_candle
	{26709, 26710, 3},  // black_candle
	{26713, 26714, 6},  // black_candle
	{26717, 26718, 9},  // black_candle
	{26721, 26722, 12}, // black_candle
	{26725, 26725, 3},  // candle_cake
	{26727, 26727, 3},  // white_candle_cake
	{26729, 26729, 3},  // orange_candle_cake
	{26731, 26731, 3},  // magenta_candle_cake
	{26733, 26733, 3},  // light_blue_candle_cake
	{26735, 26735, 3},  // yellow_candle_cake
	{26737, 26737, 3},  // lime_candle_cake
	{26739, 26739, 3},  // pink_candle_cake
	{26741, 26741, 3},  // gray_candle_cake
	{26743, 26743, 3},  // light_gray_candle_cake
	{26745, 26745, 3},  // cyan_candle_cake
	{26747, 26747, 3},  // purple_candle_cake
	{26749, 26749, 3},  // blue_candle_cake
	{26751, 26751, 3},  // brown_candle_cake
	{26753, 26753, 3},  // green_candle_cake
	{26755, 26755, 3},  // red_candle_cake
	{26757, 26757, 3},  // black_candle_cake
	{26761, 26772, 5},  // amethyst_cluster
	{26773, 26784, 4},  // large_amethyst_bud
	{26785, 26796, 2},  // medium_amethyst_bud
	{26797, 26808, 1},  // small_amethyst_bud
	{30520, 30615, 1},  // sculk_sensor
	{30616, 30999, 1},  // calibrated_sculk_sensor
	{31129, 31130, 6},  // sculk_catalyst
	{32893, 32894, 15}, // copper_bulb
	{32897, 32898, 12}, // exposed_copper_bulb
	{32901, 32902, 8},  // weathered_copper_bulb
	{32905, 32906, 4},  // oxidized_copper_bulb
	{32909, 32910, 15}, // waxed_copper_bulb
	{32913, 32914, 12}, // waxed_exposed_copper_bulb
	{32917, 32918, 8},  // waxed_weathered_copper_bulb
	{32921, 32922, 4},  // waxed_oxidized_copper_bulb
	{33606, 33606, 14}, // cave_vines
	{33608, 33608, 14}, // cave_vines
	{33610, 33610, 14}, // cave_vines
	{33612, 33612, 14}, // cave_vines
	{33614, 33614, 14}, // cave_vines
	{33616, 33616, 14}, // cave_vines
	{33618, 33618, 14}, // cave_vines
	{33620, 33620, 14}, // cave_vines
	{33622, 33622, 14}, // cave_vines
	{33624, 33624, 14}, // cave_vines
	{33626, 33626, 14}, // cave_vines
	{33628, 33628, 14}, // cave_vines
	{33630, 33630, 14}, // cave_vines
	{33632, 33632, 14}, // cave_vines
	{33634, 33634, 14}, // cave_vines
	{33636, 33636, 14}, // cave_vines
	{33638, 33638, 14}, // cave_vines
	{33640, 33640, 14}, // cave_vines
	{33642, 33642, 14}, // cave_vines
	{33644, 33644, 14}, // cave_vines
	{33646, 33646, 14}, // cave_vines
	{33648, 33648, 14}, // cave_vines
	{33650, 33650, 14}, // cave_vines
	{33652, 33652, 14}, // cave_vines
	{33654, 33654, 14}, // cave_vines
	{33656, 33656, 14}, // cave_vines
	{33658, 33658, 14}, // cave_vines_plant
	{35432, 35434, 15}, // ochre_froglight
	{35435, 35437, 15}, // verdant_froglight
	{35438, 35440, 15}, // pearlescent_froglight
	{35508, 35508, 4},  // trial_spawner
	{35509, 35511, 8},  // trial_spawner
	{35514, 35514, 4},  // trial_spawner
	{35515, 35517, 8},  // trial_spawner
	{35519, 35519, 6},  // vault
	{35520, 35522, 12}, // vault
	{35523, 35523, 6},  // vault
	{35524, 35526, 12}, // vault
	{35527, 35527, 6},  // vault
	{35528, 35530, 12}, // vault
	{35531, 35531, 6},  // vault
	{35532, 35534, 12}, // vault
	{35535, 35535, 6},  // vault
	{35536, 35538, 12}, // vault
	{35539, 35539, 6},  // vault
	{35540, 35542, 12}, // vault
	{35543, 35543, 6},  // vault
	{35544, 35546, 12}, // vault
	{35547, 35547, 6},  // vault
	{35548, 35550, 12}, // vault
	{35722, 35722, 2},  // firefly_bush
}

// LightEmission is the light level a block state emits (0 if none).
func LightEmission(state uint32) uint8 {
	lo, hi := 0, len(lightRanges)
	for lo < hi {
		mid := (lo + hi) / 2
		r := lightRanges[mid]
		switch {
		case state < r.lo:
			hi = mid
		case state > r.hi:
			lo = mid + 1
		default:
			return r.lvl
		}
	}
	return 0
}
