// Code generated by scripts/gen_tags.py from the vanilla datapack. DO NOT EDIT.

package worldgen

// blockTags are vanilla block tags (canonical 26.3), flattened.
var blockTags = map[string][]string{
	"buttons":                    {"oak_button", "spruce_button", "birch_button", "jungle_button", "acacia_button", "dark_oak_button", "pale_oak_button", "crimson_button", "warped_button", "mangrove_button", "bamboo_button", "cherry_button", "poplar_button", "stone_button", "polished_blackstone_button"},
	"fences":                     {"oak_fence", "acacia_fence", "dark_oak_fence", "pale_oak_fence", "spruce_fence", "birch_fence", "jungle_fence", "crimson_fence", "warped_fence", "mangrove_fence", "bamboo_fence", "cherry_fence", "poplar_fence", "nether_brick_fence"},
	"leaves":                     {"jungle_leaves", "oak_leaves", "spruce_leaves", "pale_oak_leaves", "dark_oak_leaves", "acacia_leaves", "birch_leaves", "azalea_leaves", "flowering_azalea_leaves", "mangrove_leaves", "cherry_leaves", "red_poplar_leaves", "orange_poplar_leaves", "yellow_poplar_leaves"},
	"pressure_plates":            {"light_weighted_pressure_plate", "heavy_weighted_pressure_plate", "oak_pressure_plate", "spruce_pressure_plate", "birch_pressure_plate", "jungle_pressure_plate", "acacia_pressure_plate", "dark_oak_pressure_plate", "pale_oak_pressure_plate", "crimson_pressure_plate", "warped_pressure_plate", "mangrove_pressure_plate", "bamboo_pressure_plate", "cherry_pressure_plate", "poplar_pressure_plate", "stone_pressure_plate", "polished_blackstone_pressure_plate"},
	"prevents_nearby_leaf_decay": {"dark_oak_log", "dark_oak_wood", "stripped_dark_oak_log", "stripped_dark_oak_wood", "pale_oak_log", "pale_oak_wood", "stripped_pale_oak_log", "stripped_pale_oak_wood", "oak_log", "oak_wood", "stripped_oak_log", "stripped_oak_wood", "acacia_log", "acacia_wood", "stripped_acacia_log", "stripped_acacia_wood", "birch_log", "birch_wood", "stripped_birch_log", "stripped_birch_wood", "jungle_log", "jungle_wood", "stripped_jungle_log", "stripped_jungle_wood", "spruce_log", "spruce_wood", "stripped_spruce_log", "stripped_spruce_wood", "mangrove_log", "mangrove_wood", "stripped_mangrove_log", "stripped_mangrove_wood", "cherry_log", "cherry_wood", "stripped_cherry_log", "stripped_cherry_wood", "poplar_log", "poplar_wood", "stripped_poplar_log", "stripped_poplar_wood", "crimson_stem", "stripped_crimson_stem", "crimson_hyphae", "stripped_crimson_hyphae", "warped_stem", "stripped_warped_stem", "warped_hyphae", "stripped_warped_hyphae"},
	"wooden_shelves":             {"acacia_shelf", "bamboo_shelf", "birch_shelf", "cherry_shelf", "crimson_shelf", "dark_oak_shelf", "jungle_shelf", "mangrove_shelf", "oak_shelf", "pale_oak_shelf", "spruce_shelf", "warped_shelf", "poplar_shelf"},
}

// itemTags are vanilla item tags (canonical 26.3), flattened.
var itemTags = map[string][]string{
	"boats":                 {"oak_boat", "spruce_boat", "birch_boat", "jungle_boat", "acacia_boat", "dark_oak_boat", "pale_oak_boat", "mangrove_boat", "bamboo_raft", "cherry_boat", "poplar_boat", "oak_chest_boat", "spruce_chest_boat", "birch_chest_boat", "jungle_chest_boat", "acacia_chest_boat", "dark_oak_chest_boat", "pale_oak_chest_boat", "mangrove_chest_boat", "bamboo_chest_raft", "cherry_chest_boat", "poplar_chest_boat"},
	"clonable_maps":         {"filled_map", "ocean_monument_map", "woodland_mansion_map", "buried_trial_chambers_map", "jungle_pyramid_map", "swamp_hut_map", "desert_village_map", "plains_village_map", "savanna_village_map", "snowy_village_map", "taiga_village_map", "buried_treasure_map", "buried_ancient_city_map", "buried_mineshaft_map", "desert_pyramid_map", "abandoned_camp_map", "warm_ocean_ruins_map"},
	"wooden_tool_materials": {"oak_planks", "spruce_planks", "birch_planks", "jungle_planks", "acacia_planks", "dark_oak_planks", "pale_oak_planks", "crimson_planks", "warped_planks", "mangrove_planks", "bamboo_planks", "cherry_planks", "poplar_planks"},
}
