// Code generated by scripts/gen_trees.py. DO NOT EDIT.

package worldgen

// TreeFeatures is every vanilla tree, by its feature name, carrying the
// parameters its trunk and foliage placers are configured with. The
// algorithms are in treeplacer.go / treefoliage.go; only the numbers are
// generated, so a species' proportions are vanilla's and not an estimate.
var TreeFeatures = map[string]*TreeConfig{
	"acacia":                {Log: 148, Leaves: 391, Trunk: TrunkForking, BaseHeight: 5, HeightRandA: 2, HeightB: 2, Foliage: FoliageAcacia, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, SizeLimit: 1, SizeLower: 0, SizeUpper: 2, DirtState: 10},
	"birch":                 {Log: 142, Leaves: 335, Trunk: TrunkStraight, BaseHeight: 5, HeightRandA: 2, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10},
	"birch_leaf_litter":     {Log: 142, Leaves: 335, Trunk: TrunkStraight, BaseHeight: 5, HeightRandA: 2, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10, LitterPasses: []LitterPass{{96, 4, 2, 3}, {150, 2, 2, 4}}},
	"cherry":                {Log: 151, Leaves: 419, Trunk: TrunkCherry, BaseHeight: 7, HeightRandA: 1, HeightB: 0, Foliage: FoliageCherry, RadiusMin: 4, RadiusMax: 4, OffsetMin: 0, OffsetMax: 0, FoliageH: 5, BranchCountMin: 1, BranchCountMax: 3, BranchHorizMin: 2, BranchHorizMax: 4, BranchStartMin: -4, BranchStartMax: -3, BranchEndMin: -1, BranchEndMax: 0, HangingLeavesChance: 0.16666667, HangingExtChance: 0.33333334, WideBottomHoleChance: 0.25, CornerHoleChance: 0.25, SizeLimit: 1, SizeLower: 0, SizeUpper: 2, DirtState: 10},
	"dark_oak":              {Log: 154, Leaves: 447, Trunk: TrunkDarkOak, BaseHeight: 6, HeightRandA: 2, HeightB: 1, Foliage: FoliageDarkOak, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, SizeThreeLayer: true, SizeLimit: 1, SizeLower: 0, SizeMiddle: 1, SizeUpperLimit: 1, SizeUpper: 2, DirtState: 10},
	"dark_oak_leaf_litter":  {Log: 154, Leaves: 447, Trunk: TrunkDarkOak, BaseHeight: 6, HeightRandA: 2, HeightB: 1, Foliage: FoliageDarkOak, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, SizeThreeLayer: true, SizeLimit: 1, SizeLower: 0, SizeMiddle: 1, SizeUpperLimit: 1, SizeUpper: 2, DirtState: 10, LitterPasses: []LitterPass{{96, 4, 2, 3}, {150, 2, 2, 4}}},
	"fancy_oak":             {Log: 136, Leaves: 279, Trunk: TrunkFancy, BaseHeight: 3, HeightRandA: 11, HeightB: 0, Foliage: FoliageFancy, RadiusMin: 2, RadiusMax: 2, OffsetMin: 4, OffsetMax: 4, FoliageH: 4, SizeLimit: 0, SizeLower: 0, SizeUpper: 0, MinClippedHeight: 4, DirtState: 10},
	"fancy_oak_leaf_litter": {Log: 136, Leaves: 279, Trunk: TrunkFancy, BaseHeight: 3, HeightRandA: 11, HeightB: 0, Foliage: FoliageFancy, RadiusMin: 2, RadiusMax: 2, OffsetMin: 4, OffsetMax: 4, FoliageH: 4, SizeLimit: 0, SizeLower: 0, SizeUpper: 0, MinClippedHeight: 4, DirtState: 10, LitterPasses: []LitterPass{{96, 4, 2, 3}, {150, 2, 2, 4}}},
	"jungle_bush":           {Log: 145, Leaves: 279, Trunk: TrunkStraight, BaseHeight: 1, HeightRandA: 0, HeightB: 0, Foliage: FoliageBush, RadiusMin: 2, RadiusMax: 2, OffsetMin: 1, OffsetMax: 1, FoliageH: 2, SizeLimit: 0, SizeLower: 0, SizeUpper: 0, DirtState: 10},
	"jungle_tree":           {Log: 145, Leaves: 363, Trunk: TrunkStraight, BaseHeight: 4, HeightRandA: 8, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, TrunkVine: true, LeaveVineProb: 0.25, CocoaProb: 0.2, DirtState: 10},
	"jungle_tree_no_vine":   {Log: 145, Leaves: 363, Trunk: TrunkStraight, BaseHeight: 4, HeightRandA: 8, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10},
	"mangrove":              {Log: 160, Leaves: 503, Trunk: TrunkUpwardsBranching, BaseHeight: 2, HeightRandA: 1, HeightB: 4, Foliage: FoliageRandomSpread, RadiusMin: 3, RadiusMax: 3, OffsetMin: 0, OffsetMax: 0, FoliageHMin: 2, FoliageHMax: 2, BranchProbability: 0.5, ExtraBranchStepsMin: 1, ExtraBranchStepsMax: 4, ExtraBranchLenMin: 0, ExtraBranchLenMax: 1, LeafPlacementAttempts: 70, SizeLimit: 2, SizeLower: 0, SizeUpper: 2, LeaveVineProb: 0.125, PropaguleProb: 0.14, PropaguleExclXZ: 1, PropaguleExclY: 0, PropaguleEmpty: 2, DirtState: 10},
	"mega_jungle_tree":      {Log: 145, Leaves: 363, Trunk: TrunkMegaJungle, BaseHeight: 10, HeightRandA: 2, HeightB: 19, Foliage: FoliageMegaJungle, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 2, SizeLimit: 1, SizeLower: 1, SizeUpper: 2, TrunkVine: true, LeaveVineProb: 0.25, DirtState: 10},
	"mega_pine":             {Log: 139, Leaves: 307, Trunk: TrunkGiant, BaseHeight: 13, HeightRandA: 2, HeightB: 14, Foliage: FoliageMegaPine, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, FoliageHMin: 3, FoliageHMax: 7, SizeLimit: 1, SizeLower: 1, SizeUpper: 2, AlterGround: true, DirtState: 10},
	"mega_spruce":           {Log: 139, Leaves: 307, Trunk: TrunkGiant, BaseHeight: 13, HeightRandA: 2, HeightB: 14, Foliage: FoliageMegaPine, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, FoliageHMin: 13, FoliageHMax: 17, SizeLimit: 1, SizeLower: 1, SizeUpper: 2, AlterGround: true, DirtState: 10},
	"oak":                   {Log: 136, Leaves: 279, Trunk: TrunkStraight, BaseHeight: 4, HeightRandA: 2, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10},
	"oak_leaf_litter":       {Log: 136, Leaves: 279, Trunk: TrunkStraight, BaseHeight: 4, HeightRandA: 2, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10, LitterPasses: []LitterPass{{96, 4, 2, 3}, {150, 2, 2, 4}}},
	"pale_oak":              {Log: 157, Leaves: 475, Trunk: TrunkDarkOak, BaseHeight: 6, HeightRandA: 2, HeightB: 1, Foliage: FoliageDarkOak, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, SizeThreeLayer: true, SizeLimit: 1, SizeLower: 0, SizeMiddle: 1, SizeUpperLimit: 1, SizeUpper: 2, PaleMossLeaves: 0.15, PaleMossTrunk: 0.4, PaleMossGround: 0.8, DirtState: 10},
	"pale_oak_bonemeal":     {Log: 157, Leaves: 475, Trunk: TrunkDarkOak, BaseHeight: 6, HeightRandA: 2, HeightB: 1, Foliage: FoliageDarkOak, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, SizeThreeLayer: true, SizeLimit: 1, SizeLower: 0, SizeMiddle: 1, SizeUpperLimit: 1, SizeUpper: 2, DirtState: 10},
	"pale_oak_creaking":     {Log: 157, Leaves: 475, Trunk: TrunkDarkOak, BaseHeight: 6, HeightRandA: 2, HeightB: 1, Foliage: FoliageDarkOak, RadiusMin: 0, RadiusMax: 0, OffsetMin: 0, OffsetMax: 0, SizeThreeLayer: true, SizeLimit: 1, SizeLower: 0, SizeMiddle: 1, SizeUpperLimit: 1, SizeUpper: 2, HeartProb: 1.0, PaleMossLeaves: 0.15, PaleMossTrunk: 0.4, PaleMossGround: 0.8, DirtState: 10},
	"pine":                  {Log: 139, Leaves: 307, Trunk: TrunkStraight, BaseHeight: 6, HeightRandA: 4, HeightB: 0, Foliage: FoliagePine, RadiusMin: 1, RadiusMax: 1, OffsetMin: 1, OffsetMax: 1, FoliageHMin: 3, FoliageHMax: 4, SizeLimit: 2, SizeLower: 0, SizeUpper: 2, DirtState: 10},
	"spruce":                {Log: 139, Leaves: 307, Trunk: TrunkStraight, BaseHeight: 5, HeightRandA: 2, HeightB: 1, Foliage: FoliageSpruce, RadiusMin: 2, RadiusMax: 3, OffsetMin: 0, OffsetMax: 2, TrunkHeightMin: 1, TrunkHeightMax: 2, SizeLimit: 2, SizeLower: 0, SizeUpper: 2, DirtState: 10},
	"super_birch_bees":      {Log: 142, Leaves: 335, Trunk: TrunkStraight, BaseHeight: 5, HeightRandA: 2, HeightB: 6, Foliage: FoliageBlob, RadiusMin: 2, RadiusMax: 2, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, DirtState: 10},
	"swamp_oak":             {Log: 136, Leaves: 279, Trunk: TrunkStraight, BaseHeight: 5, HeightRandA: 3, HeightB: 0, Foliage: FoliageBlob, RadiusMin: 3, RadiusMax: 3, OffsetMin: 0, OffsetMax: 0, FoliageH: 3, SizeLimit: 1, SizeLower: 0, SizeUpper: 1, LeaveVineProb: 0.25, DirtState: 10},
	"tall_mangrove":         {Log: 160, Leaves: 503, Trunk: TrunkUpwardsBranching, BaseHeight: 4, HeightRandA: 1, HeightB: 9, Foliage: FoliageRandomSpread, RadiusMin: 3, RadiusMax: 3, OffsetMin: 0, OffsetMax: 0, FoliageHMin: 2, FoliageHMax: 2, BranchProbability: 0.5, ExtraBranchStepsMin: 1, ExtraBranchStepsMax: 6, ExtraBranchLenMin: 0, ExtraBranchLenMax: 1, LeafPlacementAttempts: 70, SizeLimit: 3, SizeLower: 0, SizeUpper: 2, LeaveVineProb: 0.125, PropaguleProb: 0.14, PropaguleExclXZ: 1, PropaguleExclY: 0, PropaguleEmpty: 2, DirtState: 10},
}

// treeAliases are features that place an identical tree and differ only in
// decorators (bee nests, leaf litter).
var treeAliases = map[string]string{
	"birch_bees_0002":                 "birch",
	"birch_bees_0002_leaf_litter":     "birch_leaf_litter",
	"birch_bees_002":                  "birch",
	"birch_bees_005":                  "birch",
	"cherry_bees_005":                 "cherry",
	"fancy_oak_bees":                  "fancy_oak",
	"fancy_oak_bees_0002_leaf_litter": "fancy_oak_leaf_litter",
	"fancy_oak_bees_002":              "fancy_oak",
	"fancy_oak_bees_005":              "fancy_oak",
	"oak_bees_0002_leaf_litter":       "oak_leaf_litter",
	"oak_bees_002":                    "oak",
	"oak_bees_005":                    "oak",
	"super_birch_bees_0002":           "super_birch_bees",
}
