// tachyne-build assembles a custom tachyne world-engine binary with
// third-party plugins compiled in — the xcaddy model. Plugins are ordinary
// Go modules whose packages call plugin.Register from init; the builder
// generates a main package that blank-imports them and calls servercmd.Main,
// then runs the Go toolchain in a scratch workspace.
//
// Usage:
//
//	tachyne-build --with github.com/you/yourplugin
//	tachyne-build --with github.com/you/yourplugin@v1.2.0 \
//	              --with github.com/other/plugin=../local/checkout \
//	              --world v0.3.0 -o my-world
//
// --with module[@version][=replacement] selects a plugin (repeatable);
// a =replacement points at a local directory for plugins in development.
// --world pins the engine version (default latest; =path for a local
// engine checkout). Requires the Go toolchain.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
)

const engineModule = "github.com/tachyne/tachyne-world"

// withFlag collects repeated --with values.
type withFlag []string

func (w *withFlag) String() string     { return strings.Join(*w, ",") }
func (w *withFlag) Set(v string) error { *w = append(*w, v); return nil }

// pluginSpec is one parsed --with: module path, optional version, optional
// local replacement directory.
type pluginSpec struct {
	module, version, replace string
}

// parseWith splits module[@version][=replacement].
func parseWith(raw string) (pluginSpec, error) {
	spec := pluginSpec{}
	rest := raw
	if i := strings.Index(rest, "="); i >= 0 {
		spec.replace = rest[i+1:]
		rest = rest[:i]
	}
	if i := strings.Index(rest, "@"); i >= 0 {
		spec.version = rest[i+1:]
		rest = rest[:i]
	}
	spec.module = rest
	if spec.module == "" {
		return spec, fmt.Errorf("--with %q: empty module path", raw)
	}
	return spec, nil
}

// genMain is the generated entrypoint: the engine runner plus one blank
// import per plugin module.
func genMain(plugins []pluginSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by tachyne-build. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n", engineModule+"/servercmd")
	if len(plugins) > 0 {
		b.WriteString("\n")
		for _, p := range plugins {
			fmt.Fprintf(&b, "\t_ %q\n", p.module)
		}
	}
	b.WriteString(")\n\nfunc main() { servercmd.Main() }\n")
	return b.String()
}

func main() {
	log.SetFlags(0)
	var withs withFlag
	flag.Var(&withs, "with", "plugin module[@version][=local replacement dir] (repeatable)")
	world := flag.String("world", "", "engine version (e.g. v0.3.0 or a commit; default latest) or =path for a local checkout")
	output := flag.String("o", defaultOutput(), "output binary path")
	keep := flag.Bool("keep", false, "keep the build workspace (debugging)")
	flag.Parse()

	plugins := make([]pluginSpec, 0, len(withs))
	for _, raw := range withs {
		spec, err := parseWith(raw)
		if err != nil {
			log.Fatal(err)
		}
		plugins = append(plugins, spec)
	}

	out, err := filepath.Abs(*output)
	if err != nil {
		log.Fatal(err)
	}

	work, err := os.MkdirTemp("", "tachyne-build-*")
	if err != nil {
		log.Fatal(err)
	}
	if *keep {
		log.Printf("workspace: %s", work)
	} else {
		defer os.RemoveAll(work)
	}

	if err := os.WriteFile(filepath.Join(work, "main.go"), []byte(genMain(plugins)), 0o644); err != nil {
		log.Fatal(err)
	}

	run := func(args ...string) {
		cmd := exec.Command("go", args...)
		cmd.Dir = work
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
		if err := cmd.Run(); err != nil {
			log.Fatalf("go %s: %v", strings.Join(args, " "), err)
		}
	}

	run("mod", "init", "tachyne-custom-build")

	// Engine: a local checkout via replace, or a released/pseudo version.
	if strings.HasPrefix(*world, "=") {
		dir, err := filepath.Abs(strings.TrimPrefix(*world, "="))
		if err != nil {
			log.Fatal(err)
		}
		run("mod", "edit", "-require", engineModule+"@v0.0.0")
		run("mod", "edit", "-replace", engineModule+"="+dir)
	} else {
		v := *world
		if v == "" {
			v = "latest"
		}
		run("get", engineModule+"@"+v)
	}

	// Plugins: local replacements or fetched versions.
	for _, p := range plugins {
		if p.replace != "" {
			dir, err := filepath.Abs(p.replace)
			if err != nil {
				log.Fatal(err)
			}
			run("mod", "edit", "-require", p.module+"@v0.0.0")
			run("mod", "edit", "-replace", p.module+"="+dir)
			continue
		}
		v := p.version
		if v == "" {
			v = "latest"
		}
		run("get", p.module+"@"+v)
	}

	run("mod", "tidy")
	run("build", "-o", out, ".")
	log.Printf("built %s (%d plugin module(s))", out, len(plugins))
}

func defaultOutput() string {
	if runtime.GOOS == "windows" {
		return "tachyne-world.exe"
	}
	return "tachyne-world"
}
