#!/usr/bin/env python3
"""Generate internal/server/items_meta_gen.go from the local extract (scripts/extract):

- itemMaxDurability: item id -> max durability (tools, weapons, armor, ...)
- itemStackSize:     item id -> max stack size, only for non-block items whose
                     stackSize != 64 (tools 1, ender pearls 16, ...). Block
                     items get theirs from blocks.json via BlockForItem.
- armorInfo:         armor item id -> {slot, points, toughness} — armor points
                     are vanilla constants (not in minecraft-data), hand-coded
                     here by material.

Durability and stack size are the game's own answers (the MAX_DAMAGE and
MAX_STACK_SIZE item components), read by running it.

    python3 scripts/gen_durability.py [version]     # default: scripts/canon.py
"""

import canon
import json
import os
import sys

VER = sys.argv[1] if len(sys.argv) > 1 else canon.VERSION
EXTRACT = os.path.expanduser("~/vanilla/extract/%s.json" % VER)

# Vanilla armor points/toughness by material: (helmet, chest, leggings, boots).
ARMOR_POINTS = {
    "leather": (1, 3, 2, 1),
    "copper": (2, 4, 5, 1),
    "golden": (2, 5, 3, 1),
    "chainmail": (2, 5, 4, 1),
    "iron": (2, 6, 5, 2),
    "diamond": (3, 8, 6, 3),
    "netherite": (3, 8, 6, 3),
}
ARMOR_TOUGHNESS = {"diamond": 2.0, "netherite": 3.0}
PIECES = {"helmet": 0, "chestplate": 1, "leggings": 2, "boots": 3}


def main():
    items = json.load(open(EXTRACT))["items"]

    dur, stack, armor = [], [], []
    for it in items:
        iid, name = it["id"], it["name"]
        if it.get("maxDurability"):
            dur.append((iid, it["maxDurability"], name))
        if it.get("stackSize", 64) != 64:
            stack.append((iid, it["stackSize"], name))
        parts = name.rsplit("_", 1)
        if len(parts) == 2 and parts[1] in PIECES and parts[0] in ARMOR_POINTS:
            mat, piece = parts
            armor.append((iid, PIECES[piece], ARMOR_POINTS[mat][PIECES[piece]],
                          ARMOR_TOUGHNESS.get(mat, 0.0), name))
        elif name == "turtle_helmet":
            armor.append((iid, 0, 2, 0.0, name))

    out = [
        "// Code generated by scripts/gen_durability.py — DO NOT EDIT.",
        "// Source: the game's own item components, via scripts/extract.",
        "// (armor points/toughness are vanilla constants hand-coded in the script).",
        "",
        "package server",
        "",
        "// itemMaxDurability: item id -> max durability. An item is wearable-out",
        "// iff it has an entry here.",
        "var itemMaxDurability = map[int32]int{",
    ]
    for iid, d, name in sorted(dur):
        out.append(f"\t{iid}: {d}, // {name}")
    out += [
        "}",
        "",
        "// itemStackSize: NON-BLOCK items whose max stack differs from 64.",
        "var itemStackSize = map[int32]int{",
    ]
    for iid, sz, name in sorted(stack):
        out.append(f"\t{iid}: {sz}, // {name}")
    out += [
        "}",
        "",
        "// armorPiece describes a wearable: which armor slot it goes in",
        "// (0 head, 1 chest, 2 legs, 3 feet), its defense points and toughness.",
        "type armorPiece struct {",
        "\tSlot      int",
        "\tPoints    int",
        "\tToughness float64",
        "}",
        "",
        "var armorInfo = map[int32]armorPiece{",
    ]
    for iid, slot, pts, tough, name in sorted(armor):
        out.append(f"\t{iid}: {{Slot: {slot}, Points: {pts}, Toughness: {tough}}}, // {name}")
    out += ["}", ""]

    with open("internal/server/items_meta_gen.go", "w") as f:
        f.write("\n".join(out))
    print(f"wrote {len(dur)} durabilities, {len(stack)} stack sizes, {len(armor)} armor pieces")


if __name__ == "__main__":
    main()
