#!/usr/bin/env python3
"""Generate internal/server/collisionboxes_gen.go: the collision shape of
every block state that is neither empty nor the full cube, as its boxes
(VoxelShape.toAabbs under an empty collision context) — for the tests that
ask whether a box is clear of blocks (Level.noCollision), or whether a
shape meets a column (Shapes.joinIsNotEmpty).

Reads the runtime extract (scripts/extract, field collisionBoxes: null for
an empty or full shape, else [[minX, minY, minZ, maxX, maxY, maxZ], ...]).
The distinct shapes are listed once; consecutive states sharing a shape are
one run. Stdlib only.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import canon  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "collisionboxes_gen.go")


def main():
    ext = json.load(open(canon.extract()))
    shapes, index = [], {}
    runs = []
    for b in sorted(ext["blocks"], key=lambda b: b["minStateId"]):
        lo = b["minStateId"]
        for i, bx in enumerate(b["collisionBoxes"]):
            sid = lo + i
            if bx is None:
                continue
            key = json.dumps([[round(v, 6) for v in box] for box in bx])
            if key not in index:
                index[key] = len(shapes)
                shapes.append(json.loads(key))
            si = index[key]
            if runs and runs[-1][1] == sid - 1 and runs[-1][2] == si:
                runs[-1][1] = sid
            else:
                runs.append([sid, sid, si])

    def f(v):
        return repr(float(v))

    lines = [
        "// Code generated by scripts/gen_collisionboxes.py; DO NOT EDIT.",
        "",
        "package server",
        "",
        "// collisionShapes are the distinct partial collision shapes, each a",
        "// list of boxes [minX, minY, minZ, maxX, maxY, maxZ] in the cell.",
        "var collisionShapes = [...][]cbox{",
    ]
    for sh in shapes:
        lines.append("\t{" + ", ".join("{" + ", ".join(f(v) for v in box) + "}" for box in sh) + "},")
    lines.append("}")
    lines.append("")
    lines.append("// collisionShapeRuns maps state runs to their shape in collisionShapes,")
    lines.append("// ascending. States not listed are empty or the full cube.")
    lines.append("var collisionShapeRuns = [...]cshapeRun{")
    for lo, hi, si in runs:
        lines.append("\t{%d, %d, %d}," % (lo, hi, si))
    lines.append("}")
    open(OUT, "w").write("\n".join(lines) + "\n")
    print("%d shapes, %d runs -> %s" % (len(shapes), len(runs), OUT))


if __name__ == "__main__":
    main()
