#!/usr/bin/env python3
"""Regenerate internal/server/potions_gen.go — the potion table.

Vanilla's Potions registry is a list of MobEffectInstances in TICKS. Writing
the table by hand in whole seconds cost two potions their real length (strong
poison is 432 ticks, not 21 s; strong regeneration 450, not 22), and every
future value would round the same way, so both the durations and the labels
are taken from the game: the effects from Potions.java, the display name from
the jar's own en_us.json.

Needs the vanilla Potions.java on disk (set VANILLA_POTIONS) and the server
jar for the language file.

Run from the repo root:  python3 scripts/gen_potions.py

Stdlib only.
"""
import canon
import io
import json
import os
import re
import zipfile

VERSION = canon.DATA  # behaviour data: canon.py
JAR = os.path.expanduser(f"~/vanilla/server-{VERSION}.jar")
SRC = os.environ.get("VANILLA_POTIONS", os.path.join(canon.src(canon.DATA), "net/minecraft/world/item/alchemy/Potions.java"))

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "server", "potions_gen.go")

# The effect constants the engine already has, by vanilla name.
EFFECT_GO = {
    # Most names map straight across; the engine shortens a few.
    "SPEED": "effSpeed", "SLOWNESS": "effSlowness", "HASTE": "effHaste",
    "MINING_FATIGUE": "effMiningFatigue", "STRENGTH": "effStrength",
    "INSTANT_HEALTH": "effInstantHealth", "INSTANT_DAMAGE": "effInstantDamage",
    "JUMP_BOOST": "effJumpBoost", "NAUSEA": "effNausea",
    "REGENERATION": "effRegen", "RESISTANCE": "effResistance",
    "FIRE_RESISTANCE": "effFireRes", "WATER_BREATHING": "effWaterBreathing",
    "INVISIBILITY": "effInvisibility", "BLINDNESS": "effBlindness",
    "NIGHT_VISION": "effNightVision", "HUNGER": "effHunger",
    "WEAKNESS": "effWeakness", "POISON": "effPoison", "WITHER": "effWither",
    "HEALTH_BOOST": "effHealthBoost", "ABSORPTION": "effAbsorption",
    "SATURATION": "effSaturation", "GLOWING": "effGlowing",
    "LEVITATION": "effLevitation", "LUCK": "effLuck", "UNLUCK": "effUnluck",
    "SLOW_FALLING": "effSlowFalling", "CONDUIT_POWER": "effConduitPower",
    "DOLPHINS_GRACE": "effDolphinsGrace", "BAD_OMEN": "effBadOmen",
    "HERO_OF_THE_VILLAGE": "effHeroOfVillage", "DARKNESS": "effDarkness",
    "TRIAL_OMEN": "effTrialOmen", "RAID_OMEN": "effRaidOmen",
    "WIND_CHARGED": "effWindCharged", "WEAVING": "effWeaving",
    "OOZING": "effOozing", "INFESTED": "effInfested",
}


# The engine shortens two potion names; everything else is the registry name
# in camel case.
POTION_ALIAS = {"fire_resistance": "FireRes", "regeneration": "Regen"}


def go_const(registry_name):
    """"strong_night_vision" -> potStrongNightVision, with the two shortenings."""
    name = registry_name
    for long, short in POTION_ALIAS.items():
        if name == long:
            return "pot" + short
        for prefix in ("long_", "strong_"):
            if name == prefix + long:
                return "pot" + prefix[:-1].capitalize() + short
    return "pot" + "".join(p.capitalize() for p in name.split("_"))


def main():
    src = open(SRC).read()
    outer = zipfile.ZipFile(JAR)
    inner = [n for n in outer.namelist()
             if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    z = zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer
    lang = json.loads(z.read("assets/minecraft/lang/en_us.json"))

    reg = re.compile(r'Potions\.register\("([a-z_]+)",\s*new Potion\("([a-z_]+)"(.*?)\)\);')
    inst = re.compile(r"new MobEffectInstance\(MobEffects\.([A-Z_]+),\s*(\d+)(?:,\s*(\d+))?\)")

    rows = []
    for m in reg.finditer(src):
        name, base, rest = m.group(1), m.group(2), m.group(3)
        effects = []
        for e in inst.finditer(rest):
            go = EFFECT_GO.get(e.group(1))
            if go is None:
                raise SystemExit(f"{name}: no engine constant for MobEffects.{e.group(1)}")
            effects.append((go, int(e.group(3) or 0), int(e.group(2))))
        # "Potion of Night Vision" -> "Night Vision"; "Mundane Potion" -> "Mundane".
        text = lang.get(f"item.minecraft.potion.effect.{base}", "")
        if text.startswith("Potion of "):
            label = text[len("Potion of "):]
        elif text.endswith(" Potion"):
            label = text[:-len(" Potion")]
        else:
            label = text
        rows.append((name, label, effects))

    L = [
        "// Code generated by scripts/gen_potions.py. DO NOT EDIT.",
        "",
        "package server",
        "",
        "// potionDefs is vanilla's Potions registry: what each brew does, in the",
        "// TICKS vanilla stores (strong poison really is 432, not a round 21",
        "// seconds), and the name it wears in a tooltip.",
        "var potionDefs = map[int8]potionDef{",
    ]
    for name, label, effects in rows:
        if not effects:
            L.append(f'\t{go_const(name)}: {{label: "{label}"}},')
            continue
        body = ", ".join("{%s, %d, %d}" % e for e in effects)
        L.append(f'\t{go_const(name)}: {{"{label}", []potEffect{{{body}}}}},')
    L += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT}: {len(rows)} potions")


if __name__ == "__main__":
    main()
