#!/usr/bin/env python3
"""Generate internal/server/numproviders_gen.go — the vanilla registries a
number provider can name: context_float_provider, context_int_provider and
predicate, each entry as its datapack JSON.

/compute takes a provider by id (minecraft:cooking/time_coal) or inline; an
id resolves here, and an entry's own references (on_true, a predicate id)
resolve through the same tables. The JSON is kept as written and decoded by
the same reader as an inline provider, so there is one decoder, not two.

    python3 scripts/gen_numproviders.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "numproviders_gen.go")
z = canon.inner_jar()

REGISTRIES = (("context_float_provider", "floatProviderDefs"),
              ("context_int_provider", "intProviderDefs"),
              ("predicate", "predicateDefs"))

L = ["// Code generated by scripts/gen_numproviders.py from the vanilla datapack. DO NOT EDIT.",
     "",
     "package server",
     ""]
for reg, goname in REGISTRIES:
    pre = f"data/minecraft/{reg}/"
    names = sorted(n[len(pre):-len(".json")] for n in z.namelist() if n.startswith(pre) and n.endswith(".json"))
    L += [f"// {goname} is the {reg} registry (canonical {canon.VERSION}): id → JSON.",
          f"var {goname} = map[string]string{{"]
    for n in names:
        body = json.dumps(json.loads(z.read(pre + n + ".json")), separators=(",", ":"))
        L.append('\t"minecraft:%s": %s,' % (n, json.dumps(body)))
    L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {os.path.normpath(OUT)}")
