#!/usr/bin/env python3
"""Generate internal/worldgen/ignited_gen.go.

Vanilla's BlockStateBase.ignitedByLava — the flag LavaFluid.randomTick asks
of the blocks around a lava source before it lights a fire beside them. It is
a block property (Properties.ignitedByLava), set at registration, and it is
not the fire odds: wool, planks and logs have both, but a flag and a table
kept by different hands disagree at the edges, so the local extract (see
scripts/extract) asks the game for the flag itself.

    python3 scripts/gen_ignited.py [version]   # default: scripts/canon.py
"""
import canon
import json, os, subprocess, sys

VER = sys.argv[1] if len(sys.argv) > 1 else canon.VERSION
SRC = os.environ.get("EXTRACT_JSON") or os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "ignited_gen.go")

runs = []
count = 0
for b in json.load(open(SRC))["blocks"]:
    if "ignitedByLava" not in b:
        raise SystemExit("%s: no ignitedByLava — re-run scripts/extract" % b["name"])
    if not b["ignitedByLava"]:
        continue
    count += 1
    lo, hi = b["minStateId"], b["maxStateId"]
    if runs and runs[-1][1] == lo - 1:
        runs[-1][1] = hi
    else:
        runs.append([lo, hi])
runs.sort()

lines = [
    "// Code generated by scripts/gen_ignited.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    f"// ignitedRanges lists, as sorted inclusive state-id runs, the states of the",
    f"// {count} blocks vanilla registers ignitedByLava, taken from the game itself.",
    "var ignitedRanges = []struct{ Min, Max uint32 }{",
]
for lo, hi in runs:
    lines.append(f"\t{{{lo}, {hi}}},")
lines += [
    "}",
    "",
    "// IgnitedByLava is BlockStateBase.ignitedByLava: lava's random tick may",
    "// set fire beside this block.",
    "func IgnitedByLava(state uint32) bool {",
    "\tlo, hi := 0, len(ignitedRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := ignitedRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn true",
    "\t\t}",
    "\t}",
    "\treturn false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {count} blocks, {len(runs)} runs")
