#!/usr/bin/env python3
"""Generate internal/protocol/entityremap_gen.go: per-target-version entity-type ID
remap tables for the multi-version spawn_entity translation.

Like block-state IDs, entity-type IDs shift when newer versions add entities
earlier in the registry (1.21.9 adds entities → cow 28→29, player 148→151). We
send the canonical 1.21.5 (770) type ID in spawn_entity; a newer client decodes it
as a different entity (the "cows look totally wrong" bug). This emits, per client
protocol version, the type-ID remap for each entity whose ID moved.

Entity IDs are individual values (not ranges), so the table is a plain old→new map
per version, listing only the IDs that differ.

Run outside the sandbox (needs network):  python3 scripts/gen_entityremap.py
"""
import json, urllib.request, os

BASE = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/{}/entities.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "protocol", "entityremap_gen.go")

CANON = "1.21.5"
TARGETS = {771: "1.21.6", 772: "1.21.8", 773: "1.21.9", 774: "1.21.11"}


def load(ver):
    with urllib.request.urlopen(BASE.format(ver)) as r:
        return {e["name"]: e["id"] for e in json.load(r)}


canon = load(CANON)
tables = {}
for ver, dir in sorted(TARGETS.items()):
    tgt = load(dir)
    m = {canon[n]: tgt[n] for n in canon if n in tgt and canon[n] != tgt[n]}
    tables[ver] = m
    print(f"770->{ver} ({dir}): {len(m)} entity IDs remapped")

L = [
    "// Code generated by scripts/gen_entityremap.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// entityRemaps[clientProtocol] maps canonical 770 entity-type IDs to that",
    "// client version's IDs (only the IDs that differ; others pass through).",
    "var entityRemaps = map[int32]map[int32]int32{",
]
for ver in sorted(tables):
    pairs = ", ".join(f"{o}: {n}" for o, n in sorted(tables[ver].items()))
    L.append(f"\t{ver}: {{{pairs}}},")
L += [
    "}",
    "",
    "// RemapEntityType rewrites a canonical 770 entity-type ID to the client",
    "// protocol version's ID. Unlisted versions/IDs pass through unchanged.",
    "func RemapEntityType(version int32, id int32) int32 {",
    "\tif m := entityRemaps[version]; m != nil {",
    "\t\tif n, ok := m[id]; ok {",
    "\t\t\treturn n",
    "\t\t}",
    "\t}",
    "\treturn id",
    "}",
    "",
    "// HasEntityRemap reports whether a client version needs entity-type translation.",
    "func HasEntityRemap(version int32) bool { return len(entityRemaps[version]) > 0 }",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"wrote {OUT}")
