#!/usr/bin/env python3
"""Regenerate internal/server/stats_gen.go — statistics registry data in the
engine's canonical (1.21.11 / 774) id space.

Sources (local vanilla datagen reports, no network):
  ~/vanilla/reports/1.21.11/registries.json   custom_stat + block registries
  ~/vanilla/reports/1.21.11/blocks.json       per-block state-id ranges

Emits:
  - customStatID: custom stat name -> id (the award_stats `custom` type keys)
  - blockStatRanges: sorted (loState, hiState, blockRegID) so the mined-stat
    hook can turn a broken block STATE into its block REGISTRY id.

Run: python3 scripts/gen_stats.py
"""
import json
import os

REP = os.path.expanduser("~/vanilla/reports/1.21.11/")
OUT = "internal/server/stats_gen.go"

regs = json.load(open(REP + "registries.json"))
blocks = json.load(open(REP + "blocks.json"))

custom = {k.split(":")[1]: v["protocol_id"]
          for k, v in regs["minecraft:custom_stat"]["entries"].items()}
blockreg = {k: v["protocol_id"]
            for k, v in regs["minecraft:block"]["entries"].items()}

ranges = []
for name, b in blocks.items():
    ids = [s["id"] for s in b["states"]]
    ranges.append((min(ids), max(ids), blockreg[name]))
ranges.sort()

w = ["// Code generated by scripts/gen_stats.py. DO NOT EDIT.",
     "// Source: vanilla 1.21.11 datagen reports (registries + block states).",
     "",
     "package server",
     "",
     "// customStatID maps custom-stat names to canonical (774) registry ids.",
     "var customStatID = map[string]int32{"]
for name in sorted(custom):
    w.append(f"\t\"{name}\": {custom[name]},")
w += ["}", "",
      "// blockStatRanges maps block-STATE ranges to block-REGISTRY ids (both",
      "// canonical 774), sorted by lo for binary search — the mined stat is",
      "// keyed by block registry id but the engine sees broken states.",
      "var blockStatRanges = []blockStatRange{"]
for lo, hi, reg in ranges:
    w.append(f"\t{{{lo}, {hi}, {reg}}},")
w += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(w))
print(f"wrote {OUT}: {len(custom)} custom stats, {len(ranges)} block ranges")
