#!/usr/bin/env python3
"""Generate tachyne-common/protocol/entitynames_gen.go — the canonical
entity-type id of every entity, by name.

Hand-written tables in tachyne-common that need a particular entity (the
stand-ins for entities an older client lacks, the gateway's per-type
metadata fixes) name it and resolve the id here, so a canonical version
change regenerates this file instead of silently re-pointing every number.

    python3 scripts/gen_entitynames.py     # canonical version: canon.py
"""
import os

import canon
import vanillareport

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "entitynames_gen.go")

ents = vanillareport.registry(canon.VERSION, "entity_type")
if [e["id"] for e in ents] != list(range(len(ents))):
    raise SystemExit("entity ids are not dense from 0")

L = ["// Code generated by tachyne-world/scripts/gen_entitynames.py; DO NOT EDIT.",
     "",
     "package protocol",
     "",
     "// canonicalEntityIDs is every entity type's canonical (%s, protocol %d) id," % (canon.VERSION, canon.PROTOCOL),
     "// by name without the namespace. Code that needs an entity names it:",
     "// see CanonicalEntity.",
     "var canonicalEntityIDs = map[string]int32{"]
L += ['\t"%s": %d,' % (e["name"], e["id"]) for e in sorted(ents, key=lambda e: e["name"])]
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print("wrote %s: %d entity types" % (os.path.normpath(OUT), len(ents)))
