#!/usr/bin/env python3
"""Regenerate internal/protocol/registries_gen.go from misode/mcmeta.

Sources the ordered entry NAMES for each synchronized registry from the mcmeta
1.21.5 summary. Only names are needed: with the matching known pack advertised,
the client supplies the registry content (has_data=false), so we never embed
the NBT for most registries.

Run from the repo root. Needs network, so run OUTSIDE the sandbox:

    python3 scripts/gen_registries.py

Stdlib only.
"""
import json
import os
import urllib.request

SUMMARY = "https://raw.githubusercontent.com/misode/mcmeta/1.21.5-summary/registries/data.min.json"

# The registries vanilla synchronizes to the client during Configuration (1.21.5).
SYNCED = [
    "dimension_type", "painting_variant", "worldgen/biome",
    "wolf_variant", "wolf_sound_variant", "cat_variant", "frog_variant",
    "pig_variant", "cow_variant", "chicken_variant",
    "chat_type", "damage_type", "trim_pattern", "trim_material",
    "banner_pattern", "enchantment", "jukebox_song", "instrument",
]

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "protocol", "registries_gen.go")


def fetch_json(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.load(r)


def ns(n):
    return n if ":" in n else "minecraft:" + n


def entries_of(data, reg):
    v = data[reg]
    if isinstance(v, dict):  # {name: protocol_id}
        return [k for k, _ in sorted(v.items(), key=lambda kv: kv[1])]
    return list(v)  # already an ordered list


def main():
    data = fetch_json(SUMMARY)
    regs = []
    overworld_id = plains_id = -1
    for reg in SYNCED:
        names = [ns(e) for e in entries_of(data, reg)]
        if reg == "dimension_type":
            overworld_id = names.index("minecraft:overworld")
        if reg == "worldgen/biome":
            plains_id = names.index("minecraft:plains")
        regs.append((ns(reg), names))

    q = json.dumps  # ASCII identifiers -> valid Go string literal
    out = [
        "// Code generated by scripts/gen_registries.py from misode/mcmeta 1.21.5. DO NOT EDIT.",
        "",
        "package protocol",
        "",
        "// Registry is one synchronized registry sent during the Configuration state.",
        "// With the matching known pack advertised, entries carry no data — the client",
        "// uses its own built-in content, so only the ordered names are needed.",
        "type Registry struct {",
        "\tID      string",
        "\tEntries []string",
        "}",
        "",
        "// Network IDs (index within their registry) for entries we reference directly.",
        "const (",
        f"\tDimensionOverworldID = {overworld_id}",
        f"\tBiomePlainsID        = {plains_id}",
        ")",
        "",
        "// SyncedRegistries is the full set the client expects during Configuration.",
        "var SyncedRegistries = []Registry{",
    ]
    for rid, names in regs:
        out.append(f"\t{{ID: {q(rid)}, Entries: []string{{")
        for i in range(0, len(names), 4):
            out.append("\t\t" + ", ".join(q(n) for n in names[i:i + 4]) + ",")
        out.append("\t}},")
    out += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(regs)} registries, overworld={overworld_id} plains={plains_id}")


if __name__ == "__main__":
    main()
