#!/usr/bin/env python3
"""Generate internal/server/recipemeta_gen.go: what a data pack needs to know
about vanilla's stonecutting, smithing and brewing recipes to replace or
remove one by its id.

The engine's stonecutter, smithing table and brewing stand read tables keyed
by item (tachyne-common's protocol.StonecuttingRecipes / Smithing*, and the
brewing mixes in brewing.go). A pack's file at a vanilla recipe id takes that
recipe away, so the engine needs each recipe's id beside what it does:

  stonecutRowNames   the recipe id of each protocol.StonecuttingRecipes row
                     (same walk as gen_stonecutting.py: sorted recipe paths,
                     one row per ingredient item)
  vanillaSmithing    a smithing recipe's template and base items (a
                     transform's, or a trim's), by id
  vanillaBrewing     a brewing recipe's input item, input potion ("" = any)
                     and reagent items, by id

    python3 scripts/gen_recipemeta.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon
import vanillareport

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "recipemeta_gen.go")

item_id = {i["name"]: i["id"] for i in vanillareport.registry(canon.VERSION, "item")}
z = canon.inner_jar()


def ns(s):
    return s.removeprefix("minecraft:")


_tags = {}


def tag_items(tag):
    if tag in _tags:
        return _tags[tag]
    _tags[tag] = set()
    out = set()
    for v in json.loads(z.read("data/minecraft/tags/item/%s.json" % ns(tag)))["values"]:
        ref = v["id"] if isinstance(v, dict) else v
        if ref.startswith("#"):
            out |= tag_items(ref[1:])
        elif ns(ref) in item_id:
            out.add(item_id[ns(ref)])
    _tags[tag] = out
    return out


def items(ing):
    if ing is None:
        return []
    refs = ing if isinstance(ing, list) else [ing]
    out = set()
    for r in refs:
        if r.startswith("#"):
            out |= tag_items(r[1:])
        elif ns(r) in item_id:
            out.add(item_id[ns(r)])
    return sorted(out)


rows, smithing, brewing = [], [], []
prefix = "data/minecraft/recipe/"
for path in sorted(n for n in z.namelist() if n.startswith(prefix) and n.endswith(".json")):
    name = path[len(prefix):-len(".json")]
    r = json.loads(z.read(path))
    t = r.get("type")
    if t == "minecraft:stonecutting":
        result = ns(r["result"]["id"])
        if result not in item_id:
            continue
        ing = r["ingredient"]
        for n in ([ing] if isinstance(ing, str) else ing):
            if ns(n) in item_id:
                rows.append(name)
    elif t in ("minecraft:smithing_transform", "minecraft:smithing_trim"):
        smithing.append((name, t == "minecraft:smithing_trim", items(r.get("template")), items(r["base"])))
    elif t == "minecraft:brewing":
        inp = r["input"]
        pots = (inp.get("potion_contents") or {}).get("potions", "")
        if isinstance(pots, list):
            pots = pots[0] if len(pots) == 1 else ""
        in_items = items(inp["item"])
        brewing.append((name, in_items[0] if len(in_items) == 1 else 0, ns(pots), items(r["reagent"]["item"])))

L = [
    "// Code generated by scripts/gen_recipemeta.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// stonecutRowNames is the recipe id of each protocol.StonecuttingRecipes",
    "// row, in the same order.",
    "var stonecutRowNames = []string{",
]
for n in rows:
    L.append('\t"%s",' % n)
L += [
    "}",
    "",
    "// vanillaSmith is a vanilla smithing recipe's template and base items.",
    "type vanillaSmith struct {",
    "\ttrim      bool",
    "\ttemplates []int32",
    "\tbases     []int32",
    "}",
    "",
    "// vanillaSmithing are vanilla's smithing recipes by id.",
    "var vanillaSmithing = map[string]vanillaSmith{",
]
for n, trim, tmpl, base in smithing:
    L.append('\t"%s": {%s, []int32{%s}, []int32{%s}},' % (n, "true" if trim else "false",
                                                         ", ".join(map(str, tmpl)), ", ".join(map(str, base))))
L += [
    "}",
    "",
    "// vanillaBrew is a vanilla brewing recipe's input item, input potion",
    "// (\"\" = any) and reagent items.",
    "type vanillaBrew struct {",
    "\tin       int32",
    "\tpotion   string",
    "\treagents []int32",
    "}",
    "",
    "// vanillaBrewing are vanilla's brewing recipes by id.",
    "var vanillaBrewing = map[string]vanillaBrew{",
]
for n, inp, pot, reag in brewing:
    L.append('\t"%s": {%d, "%s", []int32{%s}},' % (n, inp, pot, ", ".join(map(str, reag))))
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print("wrote %s: %d stonecutter rows, %d smithing, %d brewing" % (os.path.normpath(OUT), len(rows), len(smithing), len(brewing)))
