#!/usr/bin/env python3
"""Regenerate ../tachyne-common/protocol/tags1215_gen.go — the vanilla 1.21.5 tag MANIFEST
(names only, no contents) sent to pre-26.x clients (proto 770-774).

Why names with empty contents: declaring the minecraft:enchantment registry
requires every tag its built-in data references (#minecraft:enchantable/*,
exclusive_set/*, …) to be PRESENT at registry freeze, but empty tags bind
fine. Legacy clients get the full 1.21.5 manifest so nothing can be missing;
real contents remain a 26.x-only feature (tags26x_gen.go).

Source: misode/mcmeta tag 1.21.5-summary, registries/data.min.json (the
`tag/<registry>` keys are the tag manifests). Stdlib only; needs network —
run OUTSIDE the sandbox:  python3 scripts/gen_tags1215.py
"""
import json
import urllib.request

URL = "https://raw.githubusercontent.com/misode/mcmeta/1.21.5-summary/registries/data.min.json"
OUT = "../tachyne-common/protocol/tags1215_gen.go"

# Datapack-only registries: absent at the client's config-time tag resolution,
# so sending them throws "Missing registry" (same class as tags26xSkip).
SKIP = {
    "tag/worldgen/flat_level_generator_preset",
    "tag/worldgen/structure",
    "tag/worldgen/world_preset",
}

data = json.load(urllib.request.urlopen(URL))

lines = [
    "// Code generated by scripts/gen_tags1215.py. DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// tags1215Data is every vanilla 1.21.5 tag NAME by registry (contents",
    "// intentionally empty — presence is what registry freeze validates).",
    "var tags1215Data = []tagReg26x{",
]
for key in sorted(k for k in data if k.startswith("tag/") and k not in SKIP):
    registry = "minecraft:" + key[len("tag/"):]
    lines.append(f'\t{{registry: "{registry}", tags: []tag26x{{')
    for name in data[key]:
        lines.append(f'\t\t{{name: "minecraft:{name}"}},')
    lines.append("\t}},")
lines += ["}", ""]

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {sum(len(data[k]) for k in data if k.startswith('tag/') and k not in SKIP)} tags")
