#!/usr/bin/env python3
"""Regenerate internal/server/deathmsgs_gen.go — the death messages.

Vanilla builds a death message from the DAMAGE TYPE, not from a separate
enum of causes: DamageSource.getLocalizedDeathMessage looks up
"death.attack." + type.msgId(), appends ".player" when nothing is directly to
blame but the victim was recently fighting, and ".item" when the killer's
weapon has a name. The type also carries a death_message_type that picks the
fall family or the bad-respawn-point link.

Keeping a hand-written switch beside that is how thirteen damage types ended
up reading "<name> died", so both halves are generated: the message id and
kind from the damage_type data, the ENGLISH TEXT from the jar's own
en_us.json, placeholders and all.

Reads the canonical server jar (data + assets) — no network.

Run from the repo root:  python3 scripts/gen_deathmsgs.py

Stdlib only.
"""
import canon
import io
import json
import os
import zipfile

VERSION = canon.DATA  # behaviour data: canon.py
JAR = os.path.expanduser(f"~/vanilla/server-{VERSION}.jar")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "server", "deathmsgs_gen.go")

KINDS = {"default": "deathMsgDefault",
         "fall_variants": "deathMsgFallVariants",
         "intentional_game_design": "deathMsgIntentional"}


def jars():
    """The server jar's built-in datapack + assets (nested in the launcher jar)."""
    outer = zipfile.ZipFile(JAR)
    inner = [n for n in outer.namelist()
             if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    return zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer


def camel(name):
    return "".join(p.capitalize() for p in name.split("_"))


def main():
    z = jars()
    pre = "data/minecraft/damage_type/"
    types = {}
    for p in sorted(z.namelist()):
        if p.startswith(pre) and p.endswith(".json") and "/" not in p[len(pre):]:
            name = p[len(pre):-len(".json")]
            types[name] = json.loads(z.read(p))

    lang = json.loads(z.read("assets/minecraft/lang/en_us.json"))
    msgs = {k: v for k, v in lang.items() if k.startswith("death.attack.")}

    for name, d in types.items():
        key = "death.attack." + d["message_id"]
        if key not in msgs and d.get("death_message_type", "default") == "default":
            raise SystemExit(f"{name}: no text for {key}")

    L = [
        "// Code generated by scripts/gen_deathmsgs.py. DO NOT EDIT.",
        "",
        "package server",
        "",
        "// deathMsgKind is DamageType.deathMessageType: which family of message a",
        "// death of this type reads from.",
        "type deathMsgKind uint8",
        "",
        "const (",
        "\tdeathMsgDefault      deathMsgKind = iota // death.attack.<id>[.player|.item]",
        "\tdeathMsgFallVariants                     // the \"doomed to fall\" family",
        "\tdeathMsgIntentional                      // the bad respawn point's link",
        ")",
        "",
        "// dmgTypeMsgID is DamageType.msgId — the death.attack.<id> family the",
        "// message comes from. Several damage types share one: a mob's bite, its",
        "// projectile, a llama's spit and a wind charge are all \"mob\".",
        "var dmgTypeMsgID = [...]string{",
    ]
    for name, d in types.items():
        L.append(f'\tdt{camel(name)}: "{d["message_id"]}",')
    L += [
        "}",
        "",
        "// dmgTypeDeathKind is the message family of each damage type; the types",
        "// absent from this table are deathMsgDefault.",
        "var dmgTypeDeathKind = [...]deathMsgKind{",
    ]
    for name, d in types.items():
        kind = d.get("death_message_type", "default")
        if kind != "default":
            L.append(f"\tdt{camel(name)}: {KINDS[kind]},")
    L += [
        "}",
        "",
        "// deathMsgText is the English of every death.attack.* string, vanilla's",
        "// own, with its %1$s (victim) / %2$s (killer) / %3$s (weapon) placeholders",
        "// left in place for deathMessage to fill.",
        "var deathMsgText = map[string]string{",
    ]
    for k in sorted(msgs):
        v = msgs[k].replace("\\", "\\\\").replace('"', '\\"')
        L.append(f'\t"{k}": "{v}",')
    L += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT}: {len(types)} damage types, {len(msgs)} messages")


if __name__ == "__main__":
    main()
