#!/usr/bin/env python3
"""Generate internal/worldgen/fluidfaces_gen.go: each block state's collision
cross-section on its six faces, for the fluid face test
(FlowingFluid.canPassThroughWall → Shapes.mergedFaceOccludes).

Reads the runtime extract (scripts/extract, field collisionFaces): per state,
null for an empty or full-block collision shape, otherwise per direction
(down, up, north, south, west, east) the face shape's boxes flattened onto
the face's two axes. Distinct face shapes are stored once; consecutive states
sharing all six are stored as one run.

Stdlib only.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import canon  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "fluidfaces_gen.go")


def main():
    ext = json.load(open(canon.extract()))
    shapes = {(): 0}  # face shape (tuple of rects) -> index; 0 = empty face
    order = [()]
    per_state = {}
    for b in ext["blocks"]:
        lo = b["minStateId"]
        for i, faces in enumerate(b["collisionFaces"]):
            if faces is None:
                continue
            idx = []
            for rects in faces:
                key = tuple(tuple(round(v, 6) for v in r) for r in sorted(rects))
                if key not in shapes:
                    shapes[key] = len(order)
                    order.append(key)
                idx.append(shapes[key])
            per_state[lo + i] = tuple(idx)
    runs = []
    for s in sorted(per_state):
        f = per_state[s]
        if runs and runs[-1][1] == s - 1 and runs[-1][2] == f:
            runs[-1][1] = s
        else:
            runs.append([s, s, f])
    with open(OUT, "w") as w:
        w.write("// Code generated by tachyne-world/scripts/gen_fluidfaces.py; DO NOT EDIT.\n\n")
        w.write("package worldgen\n\n")
        w.write(f"// {len(per_state)} states with a partial collision shape, {len(order) - 1} distinct faces, {len(runs)} runs.\n\n")
        w.write("var faceShapes = [][]faceRect{\n")
        for key in order:
            w.write("\t{" + ", ".join("{%s}" % ", ".join(repr(float(v)) for v in r) for r in key) + "},\n")
        w.write("}\n\n")
        w.write("var faceRuns = []faceRun{\n")
        for lo, hi, f in runs:
            w.write("\t{%d, %d, [6]uint16{%s}},\n" % (lo, hi, ", ".join(str(x) for x in f)))
        w.write("}\n")
    print(f"{len(per_state)} partial states, {len(order) - 1} faces, {len(runs)} runs -> {OUT}")


if __name__ == "__main__":
    main()
