#!/usr/bin/env python3
"""Generate internal/server/paintings_gen.go from the vanilla server jar.

Painting variants are a data-driven registry: per-variant width/height (in
blocks) live in data/minecraft/painting_variant/*.json and the subset a
player can place comes from tags/painting_variant/placeable.json. The engine
needs sizes for the placement/survival math; wire ids are the gateway's
concern (index into the synced registry list).

Reads the local jar (no network): ~/vanilla/server-1.21.11.jar
"""
import io, json, os, zipfile

SRC = os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "paintings_gen.go")

z = zipfile.ZipFile(SRC)
inner = [n for n in z.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
if inner:
    z = zipfile.ZipFile(io.BytesIO(z.read(inner[0])))

variants, placeable = {}, []
for n in z.namelist():
    if not n.endswith(".json"):
        continue
    if n.startswith("data/minecraft/painting_variant/"):
        d = json.loads(z.read(n))
        variants[n.split("/")[-1][:-5]] = (d.get("width", 1), d.get("height", 1))
    elif n == "data/minecraft/tags/painting_variant/placeable.json":
        placeable = [v.removeprefix("minecraft:") for v in json.loads(z.read(n))["values"]]

placeable.sort()
lines = [
    "// Code generated by scripts/gen_paintings.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// paintingVariant is one placeable painting: its registry name and its",
    "// size in blocks (the placement/survival math needs the footprint).",
    "type paintingVariant struct {",
    "\tName string",
    "\tW, H int",
    "}",
    "",
    "// paintingVariants lists the vanilla placeable painting variants",
    "// (tags/painting_variant/placeable).",
    "var paintingVariants = []paintingVariant{",
]
for name in placeable:
    w, h = variants[name]
    lines.append(f'\t{{"{name}", {w}, {h}}},')
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(placeable)} placeable of {len(variants)} variants")
