#!/usr/bin/env python3
"""Regenerate internal/server/itemnames_gen.go — item name → id for /give.
Source: vanilla's registries report for the canonical version, read through
scripts/vanillareport.py. Ids are the item registry's protocol ids.

    python3 scripts/gen_itemnames.py [version]     # default: scripts/canon.py
"""
import canon
import sys

import vanillareport

VER = sys.argv[1] if len(sys.argv) > 1 else canon.VERSION
OUT = "internal/server/itemnames_gen.go"

items = vanillareport.registry(VER, "item")
lines = [
    "// Code generated by scripts/gen_itemnames.py. DO NOT EDIT.",
    "",
    "package server",
    "",
    "// itemByName maps minecraft item names (no namespace) to 1.21.5 ids.",
    "var itemByName = map[string]int32{",
]
for e in items:
    lines.append(f'\t"{e["name"]}": {e["id"]},')
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(items)} items")
