#!/usr/bin/env python3
"""Generate internal/protocol/blockentities_gen.go.

Blocks like beds, chests, signs and banners render via a client-side block-entity
renderer: without a block entity present the client draws only the block outline
("wireframe"). Our chunk packets must therefore list the block entities in a chunk,
each as (packed XZ, Y, block_entity_type id, NBT). For rendering, empty NBT
(TAG_End) is enough — the type + position instantiate the renderer.

This bakes a block-state-range -> block_entity_type-id table. The type ids are the
block_entity_type registry order (a static registry the client always knows); the
block->type association is by name (beds, chest family, sign/hanging_sign, banner,
skull/head, shulker_box, and the rest of the tile-entity blocks).

CAUTION on sourcing: block_entity_type is a STATIC registry, so its network ids
are vanilla's REGISTRATION order (furnace=0, chest=1, ..., bed=25). mcmeta's
summary lists registries ALPHABETICALLY — using it here produced wrong ids. The
ViaVersion mappings list them in true network order; that's the source of truth.

Run outside the sandbox (needs network):  python3 scripts/gen_blockentities.py
"""
import json, urllib.request, os, subprocess

MD = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
VV = "https://raw.githubusercontent.com/ViaVersion/Mappings/main/mappings/mapping-1.21.11.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "blockentities_gen.go")

blocks = json.load(urllib.request.urlopen(MD))
betype = json.load(urllib.request.urlopen(VV))["blockentities"]  # network order
id_of = {name: i for i, name in enumerate(betype)}


def classify(n):
    """Map a block name to its block_entity_type name (or None if it has none)."""
    if n.endswith("_bed"):
        return "bed"
    if n == "chest":
        return "chest"
    if n == "trapped_chest":
        return "trapped_chest"
    if n == "ender_chest":
        return "ender_chest"
    if n == "barrel":
        return "barrel"
    if n.endswith("shulker_box"):  # shulker_box + <color>_shulker_box
        return "shulker_box"
    if n.endswith("_hanging_sign"):  # includes *_wall_hanging_sign
        return "hanging_sign"
    if n.endswith("_sign"):  # standing + wall signs
        return "sign"
    if n.endswith("_banner"):  # standing + wall banners
        return "banner"
    if (n.endswith("_skull") or n.endswith("_head")) and n != "piston_head":
        return "skull"
    if n in ("campfire", "soul_campfire"):
        return "campfire"
    if n in ("beehive", "bee_nest"):
        return "beehive"
    if n in ("suspicious_sand", "suspicious_gravel"):
        return "brushable_block"
    if n.endswith("command_block"):
        return "command_block"
    if n == "spawner":
        return "mob_spawner"
    exact = {
        "furnace", "blast_furnace", "smoker", "dispenser", "dropper", "hopper",
        "brewing_stand", "beacon", "bell", "conduit", "lectern", "enchanting_table",
        "jukebox", "comparator", "daylight_detector", "decorated_pot", "crafter",
        "chiseled_bookshelf", "trial_spawner", "vault", "sculk_sensor",
        "calibrated_sculk_sensor", "sculk_catalyst", "sculk_shrieker",
        "creaking_heart", "structure_block", "jigsaw",
    }
    if n in exact:
        return n
    return None


rows = []  # (min, max, type_id)
for b in blocks:
    be = classify(b["name"])
    if be is None:
        continue
    if be not in id_of:
        raise SystemExit(f"block_entity_type {be!r} (for {b['name']}) not in registry")
    rows.append((b["minStateId"], b["maxStateId"], id_of[be]))
rows.sort()

L = [
    "// Code generated by scripts/gen_blockentities.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// blockEntityRanges maps a block-state range to its block_entity_type network id",
    "// (block_entity_type registry order). Sorted by Min for binary search. Used to",
    "// list a chunk's block entities so beds/chests/signs render instead of showing",
    "// only their wireframe outline after the chunk (re)loads.",
    "var blockEntityRanges = []struct {",
    "\tMin, Max uint32",
    "\tType     int32",
    "}{",
]
for mn, mx, t in rows:
    L.append(f"\t{{{mn}, {mx}, {t}}},")
L += [
    "}",
    "",
    "// BlockEntityType returns the block_entity_type id for a block state and whether",
    "// the block has a block entity at all.",
    "func BlockEntityType(state uint32) (int32, bool) {",
    "\tlo, hi := 0, len(blockEntityRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := blockEntityRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.Type, true",
    "\t\t}",
    "\t}",
    "\treturn 0, false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(rows)} block-entity ranges")
