#!/usr/bin/env python3
"""Generate internal/server/enchantments_gen.go from the vanilla server jar.

Every enchantment definition (weight, level cap, cost curves, anvil cost),
its supported/primary item sets (item tags expanded to names), its exclusive
set, and the pool tags (in_enchanting_table, treasure, curse, tradeable,
on_random_loot, on_traded_equipment, on_mob_spawn_equipment) — the data
EnchantmentHelper and the loot/trade rollers select from. Ids follow the
engine's declared enchantment registry order (alphabetical).

Run: python3 scripts/gen_enchantments.py [path-to-server.jar]
"""
import io
import json
import os
import re
import subprocess
import sys
import zipfile

JAR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = "internal/server/enchantments_gen.go"


def load_jar(path):
    z = zipfile.ZipFile(path)
    inner = [n for n in z.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    if inner:
        z = zipfile.ZipFile(io.BytesIO(z.read(inner[0])))
    return z


def strip_ns(name):
    return name.split(":", 1)[1] if ":" in name else name


class Tags:
    def __init__(self, z):
        self.z, self.cache = z, {}

    def expand(self, tag, kind):
        tag = strip_ns(tag.lstrip("#"))
        key = (kind, tag)
        if key in self.cache:
            return self.cache[key]
        out = []
        try:
            d = json.loads(self.z.read(f"data/minecraft/tags/{kind}/{tag}.json"))
        except KeyError:
            self.cache[key] = out
            return out
        for v in d["values"]:
            v = v["id"] if isinstance(v, dict) else v
            if v.startswith("#"):
                out += self.expand(v, kind)
            else:
                out.append(strip_ns(v))
        self.cache[key] = out
        return out


def names_of(v, tags, kind):
    if v is None:
        return []
    vals = v if isinstance(v, list) else [v]
    out = []
    for x in vals:
        if x.startswith("#"):
            out += tags.expand(x, kind)
        else:
            out.append(strip_ns(x))
    seen, uniq = set(), []
    for n in out:
        if n not in seen:
            seen.add(n)
            uniq.append(n)
    return uniq


def declared_registry():
    mod = subprocess.check_output(
        ["go", "list", "-m", "-f", "{{.Dir}}", "github.com/tachyne/tachyne-common"], text=True).strip()
    src = open(os.path.join(mod, "protocol", "registries_gen.go")).read()
    m = re.search(r'ID: "minecraft:enchantment", Entries: \[\]string\{(.*?)\}\}', src, re.S)
    if not m:
        sys.exit("enchantment registry not found in tachyne-common registries_gen.go")
    return [strip_ns(x) for x in re.findall(r'"([a-z_:]+)"', m.group(1))]


def main():
    z = load_jar(JAR)
    tags = Tags(z)
    # The engine's declared enchantment registry (tachyne-common) is the id
    # order clients see; the jar can carry flagged extras (1.21.11 ships
    # "lunge" for the spear experiment) which are not in it and are skipped.
    names = declared_registry()
    have = {strip_ns(n[len("data/minecraft/enchantment/"):-5])
            for n in z.namelist()
            if n.startswith("data/minecraft/enchantment/") and n.endswith(".json")}
    missing = [n for n in names if n not in have]
    if missing:
        sys.exit(f"declared enchantments absent from the jar: {missing}")
    skipped = sorted(have - set(names))
    if skipped:
        print(f"skipping jar enchantments not in the declared registry: {skipped}")
    ids = {n: i for i, n in enumerate(names)}
    pools = {t: set(tags.expand(t, "enchantment")) for t in
             ["in_enchanting_table", "treasure", "curse", "tradeable", "on_random_loot",
              "on_traded_equipment", "on_mob_spawn_equipment", "double_trade_price"]}
    lines = ["// Code generated by scripts/gen_enchantments.py from the vanilla server jar; DO NOT EDIT.",
             "", "package server", "",
             "// enchDefs is every vanilla enchantment's definition, indexed by the engine's",
             "// declared registry id (alphabetical). Item sets are registry names, resolved",
             "// to ids at init (enchantengine.go).",
             "var enchDefs = [...]enchDef{"]
    for n in names:
        e = json.loads(z.read(f"data/minecraft/enchantment/{n}.json"))
        mn, mx = e["min_cost"], e["max_cost"]
        supp = names_of(e["supported_items"], tags, "item")
        prim = names_of(e.get("primary_items"), tags, "item")
        excl = [ids[x] for x in names_of(e.get("exclusive_set"), tags, "enchantment") if x in ids]
        flags = []
        for t, goname in [("in_enchanting_table", "enchInTable"), ("treasure", "enchTreasure"),
                          ("curse", "enchCurse"), ("tradeable", "enchTradeable"),
                          ("on_random_loot", "enchOnRandomLoot"),
                          ("on_traded_equipment", "enchOnTradedEquipment"),
                          ("on_mob_spawn_equipment", "enchOnMobEquipment"),
                          ("double_trade_price", "enchDoubleTradePrice")]:
            if n in pools[t]:
                flags.append(goname)
        q = lambda xs: "[]string{" + ", ".join(f'"{x}"' for x in xs) + "}"
        lines.append(f"\t{ids[n]}: {{name: \"{n}\", weight: {e['weight']}, maxLevel: {e['max_level']}, "
                     f"minBase: {mn['base']}, minPer: {mn['per_level_above_first']}, "
                     f"maxBase: {mx['base']}, maxPer: {mx['per_level_above_first']}, "
                     f"anvilCost: {e['anvil_cost']}, flags: {' | '.join(flags) or '0'},")
        lines.append(f"\t\tsupported: {q(supp)},")
        if prim:
            lines.append(f"\t\tprimary: {q(prim)},")
        if excl:
            lines.append(f"\t\texclusive: []int8{{{', '.join(str(x) for x in excl)}}},")
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    open(OUT, "w").write("\n".join(lines) + "\n")
    subprocess.run(["gofmt", "-w", OUT], check=True)
    print(f"wrote {OUT}: {len(names)} enchantments")


if __name__ == "__main__":
    main()
