#!/usr/bin/env python3
"""Regenerate internal/server/itemtags_gen.go — every item tag and the items
in it.

The item predicates of /execute if items, /clear and the slot sources
(ItemPredicateArgument: #minecraft:logs) and an item predicate's "items"
field take an item tag. The tags come from the canonical version's
built-in datapack; a tag may name other tags, so references are resolved
transitively, and an optional entry ({"id": …, "required": false}) is
kept when the item exists.

Reads the canonical version's server jar (canon.VERSION) — no network.

Run from the repo root:  python3 scripts/gen_itemtags.py

Stdlib only.
"""
import canon
import io
import json
import os
import subprocess
import zipfile

VERSION = canon.VERSION
JAR = os.path.expanduser(f"~/vanilla/server-{VERSION}.jar")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "server", "itemtags_gen.go")
PREFIX = "data/minecraft/tags/item/"


def datapack():
    """The server jar's built-in datapack (nested inside the launcher jar)."""
    outer = zipfile.ZipFile(JAR)
    inner = [n for n in outer.namelist()
             if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    return zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer


def entry_id(v):
    return v["id"] if isinstance(v, dict) else v


def main():
    z = datapack()
    raw = {}
    for path in z.namelist():
        if path.startswith(PREFIX) and path.endswith(".json"):
            name = "minecraft:" + path[len(PREFIX):-len(".json")]
            raw[name] = [entry_id(v) for v in json.loads(z.read(path))["values"]]

    def resolve(name, seen):
        out = []
        for v in raw.get(name, []):
            if v.startswith("#"):
                ref = v[1:]
                if ref not in seen:
                    for b in resolve(ref, seen | {ref}):
                        if b not in out:
                            out.append(b)
            elif v not in out:
                out.append(v)
        return out

    lines = [
        "// Code generated by scripts/gen_itemtags.py; DO NOT EDIT.",
        "",
        "package server",
        "",
        f"// itemTagMembers is every {VERSION} item tag with its items (bare",
        "// names), nested tags resolved.",
        "var itemTagMembers = map[string][]string{",
    ]
    for name in sorted(raw):
        items = []
        for b in resolve(name, {name}):
            bare = b[len("minecraft:"):] if b.startswith("minecraft:") else b
            if bare not in items:
                items.append(bare)
        members = ", ".join(json.dumps(b) for b in items)
        lines.append(f"\t{json.dumps(name)}: {{{members}}},")
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    subprocess.run(["gofmt", "-w", OUT], check=False)
    print(f"wrote {OUT}: {len(raw)} tags")


if __name__ == "__main__":
    main()
