#!/usr/bin/env python3
"""Generate internal/server/standing_gen.go: the standing→wall variant maps
for banners (16 colors) and mob heads/skulls (7 kinds) — the sign-style
placement family (16-way rotation on the ground, facing on a wall). Signs
have their own tables in signs_gen.go (they also carry the edit machinery).

Reads the local datagen report: ~/vanilla/reports/1.21.11/blocks.json
"""
import json, os

SRC = os.path.expanduser("~/vanilla/reports/1.21.11/blocks.json")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "standing_gen.go")

blocks = json.load(open(SRC))

def default(name):
    return [s["id"] for s in blocks[name]["states"] if s.get("default")][0]

colors = ["white", "orange", "magenta", "light_blue", "yellow", "lime", "pink",
          "gray", "light_gray", "cyan", "purple", "blue", "brown", "green", "red", "black"]
banners = [(default(f"minecraft:{c}_banner"), default(f"minecraft:{c}_wall_banner"), c) for c in colors]

heads = []
for n in sorted(blocks):
    short = n.removeprefix("minecraft:")
    if not (short.endswith("_head") or short.endswith("_skull")) or "wall" in short or "piston" in short:
        continue
    suffix = "_skull" if short.endswith("_skull") else "_head"
    wall = "minecraft:" + short.removesuffix(suffix) + "_wall" + suffix
    heads.append((default(n), default(wall), short))

lines = [
    "// Code generated by scripts/gen_standing.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// bannerWallVariant maps a banner item's standing default state to the",
    "// same color's wall-banner default state.",
    "var bannerWallVariant = map[uint32]uint32{",
]
for d, w, name in banners:
    lines.append(f"\t{d}: {w}, // {name}")
lines += [
    "}",
    "",
    "// headWallVariant maps a mob head/skull item's standing default state to",
    "// its wall variant. Heads need no support block (vanilla SkullBlock).",
    "var headWallVariant = map[uint32]uint32{",
]
for d, w, name in heads:
    lines.append(f"\t{d}: {w}, // {name}")
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(banners)} banners, {len(heads)} heads")
