#!/usr/bin/env python3
"""Generate internal/server/villager_trades_gen.go — the villager trade tables.

Facts matching vanilla 1.21.5's VillagerTrades.TRADES (the two
dominant ItemListing types: EmeraldForItems = villager buys N of an item for 1
emerald; ItemsForEmeralds = villager sells N items for C emeralds). Exotic
listings (enchanted books/items, treasure maps, suspicious stew, tipped arrows,
villager-type/biome-specific) are skipped for now — noted as follow-up. Item
names mapped to tachyne ids via the generated itemByName table.

Run locally (vanilla reference source + itemnames_gen.go on disk; set VANILLA_SRC)."""
import os
import re

SRC = os.environ.get("VANILLA_SRC", "")  # path to a vanilla VillagerTrades.java reference
NAMES = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "itemnames_gen.go")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "villager_trades_gen.go")

# Profession → tachyne index (order defines the generated enum).
PROFS = ["FARMER", "FISHERMAN", "SHEPHERD", "FLETCHER", "LIBRARIAN", "CARTOGRAPHER",
         "CLERIC", "ARMORER", "WEAPONSMITH", "TOOLSMITH", "MASON", "BUTCHER", "LEATHERWORKER"]


def load_item_ids():
    ids = {}
    for m in re.finditer(r'"([a-z0-9_]+)":\s*(\d+)', open(NAMES).read()):
        ids[m.group(1)] = int(m.group(2))
    return ids


def main():
    ids = load_item_ids()
    emerald = ids["emerald"]
    src = open(SRC).read()

    def item_id(enum):  # Items.WHEAT / Blocks.PUMPKIN → id
        name = enum.lower()
        return ids.get(name)

    # Per profession, isolate its put(...) region up to the next put or EOF.
    prof_re = {p: None for p in PROFS}
    puts = list(re.finditer(r"hashMap\.put\(VillagerProfession\.([A-Z_]+),", src))
    for i, m in enumerate(puts):
        p = m.group(1)
        if p not in prof_re:
            continue
        start = m.end()
        end = puts[i + 1].start() if i + 1 < len(puts) else len(src)
        prof_re[p] = src[start:end]

    efi = re.compile(r"new EmeraldForItems\((?:Items|Blocks)\.([A-Z_]+),\s*(\d+),\s*(\d+),\s*(\d+)\)")
    ife = re.compile(r"new ItemsForEmeralds\((?:new ItemStack\()?(?:Items|Blocks)\.([A-Z_]+)\)?,\s*([0-9.,fF ]+)\)")
    tier_re = re.compile(r"\(Object\)(\d),\s*\(Object\)new ItemListing\[\]\{")

    # profession-index → tier(1..5) → list of trades
    table = {}
    skipped = 0
    for p in PROFS:
        body = prof_re.get(p)
        if not body:
            continue
        pi = PROFS.index(p)
        table[pi] = {}
        # Split the body into tier segments by the "(Object)N, (Object)new ItemListing[]{" markers.
        marks = list(tier_re.finditer(body))
        for j, tm in enumerate(marks):
            tier = int(tm.group(1))
            seg_start = tm.end()
            seg_end = marks[j + 1].start() if j + 1 < len(marks) else len(body)
            seg = body[seg_start:seg_end]
            trades = []
            for m in efi.finditer(seg):
                iid = item_id(m.group(1))
                if iid is None:
                    continue
                price, maxu, xp = int(m.group(2)), int(m.group(3)), int(m.group(4))
                # villager BUYS: in = item×price → out = emerald×1
                trades.append((iid, price, emerald, 1, maxu, xp))
            for m in ife.finditer(seg):
                iid = item_id(m.group(1))
                if iid is None:
                    continue
                nums = [n for n in re.split(r"[,\s]+", m.group(2).replace("f", "").replace("F", "")) if n]
                vals = [float(n) for n in nums]
                if len(vals) < 3:
                    continue
                cost, count = int(vals[0]), int(vals[1])
                if len(vals) == 3:      # cost, count, xp — maxUses defaults 12
                    maxu, xp = 12, int(vals[2])
                else:                    # cost, count, maxUses, xp[, priceMult]
                    maxu, xp = int(vals[2]), int(vals[3])
                # villager SELLS: in = emerald×cost → out = item×count
                trades.append((emerald, cost, iid, count, maxu, xp))
            # count the exotic listings we skipped in this segment
            skipped += seg.count("new ") - len(efi.findall(seg)) - len(ife.findall(seg))
            if trades:
                table[pi][tier] = trades

    with open(OUT, "w") as f:
        f.write("// Code generated by scripts/gen_villager_trades.py. DO NOT EDIT.\n")
        f.write("// Villager trades transcribed from the vanilla 1.21.5 VillagerTrades.TRADES\n")
        f.write("// (EmeraldForItems + ItemsForEmeralds listings; exotic types omitted).\n\n")
        f.write("package server\n\n")
        f.write("// vTrade is one merchant offer: input item×count → output item×count, with a\n")
        f.write("// use limit before it locks and the trade-XP it grants the villager.\n")
        f.write("type vTrade struct{ inItem, inCount, outItem, outCount, maxUses, xp int32 }\n\n")
        f.write("// profession names by tachyne index (order matches the generator).\n")
        f.write("var professionNames = []string{\n")
        for p in PROFS:
            f.write(f'\t"{p.lower()}",\n')
        f.write("}\n\n")
        f.write("// villagerTrades[profession][tier 1..5] = the offers unlocked at that tier.\n")
        f.write("var villagerTrades = map[int]map[int][]vTrade{\n")
        for pi in sorted(table):
            f.write(f"\t{pi}: {{ // {PROFS[pi].lower()}\n")
            for tier in sorted(table[pi]):
                f.write(f"\t\t{tier}: {{")
                for (ii, ic, oi, oc, mu, xp) in table[pi][tier]:
                    f.write(f"{{{ii}, {ic}, {oi}, {oc}, {mu}, {xp}}}, ")
                f.write("},\n")
            f.write("\t},\n")
        f.write("}\n")
    n = sum(len(v) for pt in table.values() for v in pt.values())
    print(f"wrote {n} trades across {len(table)} professions to {OUT} (skipped ~{skipped} exotic listings)")


if __name__ == "__main__":
    main()
