#!/usr/bin/env python3
"""Generate internal/protocol/protomap_gen.go: per-step packet-ID remap tables for
the multi-version translation chain (770 canonical -> newer clients).

The translation seam composes single-version "steps". Each step renumbers packet
IDs between two adjacent protocol versions (IDs move around constantly between
versions; field layouts change far less often). This generator diffs minecraft-data
protocol.json for each adjacent pair and emits, per connection state and direction,
only the IDs that DIFFER (identity for the rest), plus the packets that have no
equivalent on the other side (dropped).

Body/field-layout changes are NOT handled here — those are hand-written rewriters
in the per-step Go files, applied on top of this ID remap.

Run outside the sandbox (needs network):  python3 scripts/gen_protomap.py
"""
import json, urllib.request, os

BASE = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/{}/protocol.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "protocol", "protomap_gen.go")

# protocol number -> minecraft-data version dir. Adjacent pairs become steps.
CHAIN = [(770, "1.21.5"), (771, "1.21.6"), (772, "1.21.8"), (773, "1.21.9"), (774, "1.21.11")]
STATES = ["login", "configuration", "play"]  # handshake/status are version-stable


def load(ver):
    with urllib.request.urlopen(BASE.format(ver)) as r:
        return json.load(r)


def idmap(p, state, d):
    """name -> id for a state+direction."""
    try:
        node = p[state][d]["types"]["packet"][1][0]["type"][1]["mappings"]
    except Exception:
        return {}
    return {name: int(k, 16) for k, name in node.items()}


protos = {ver: load(dir) for ver, dir in CHAIN}

steps = []  # (upper_proto, lower_proto, cbUp, cbDrop, sbDown, sbDrop)
for (lo, _), (hi, _) in zip(CHAIN, CHAIN[1:]):
    pa, pb = protos[lo], protos[hi]
    cbUp, cbDrop, sbDown, sbDrop = {}, {}, {}, {}
    for state in STATES:
        # clientbound (toClient): canonical lower id -> client upper id
        la, lb = idmap(pa, state, "toClient"), idmap(pb, state, "toClient")
        up, drop = {}, []
        for name, lid in la.items():
            if name in lb:
                if lb[name] != lid:
                    up[lid] = lb[name]
            else:
                drop.append(lid)  # removed in upper -> drop when sending to this client
        if up:
            cbUp[state] = up
        if drop:
            cbDrop[state] = sorted(drop)
        # serverbound (toServer): client upper id -> canonical lower id
        sa, sb = idmap(pa, state, "toServer"), idmap(pb, state, "toServer")
        down, sdrop = {}, []
        for name, uid in sb.items():
            if name in sa:
                if sa[name] != uid:
                    down[uid] = sa[name]
            else:
                sdrop.append(uid)  # new serverbound packet 770 never had -> drop on receive
        if down:
            sbDown[state] = down
        if sdrop:
            sbDrop[state] = sorted(sdrop)
    steps.append((hi, lo, cbUp, cbDrop, sbDown, sbDrop))


def gostate(s):
    return {"login": "StateLogin", "configuration": "StateConfiguration", "play": "StatePlay"}[s]


def emit_idmap(name, d):
    lines = [f"\t\t{name}: map[State]map[int32]int32{{"]
    for state, m in d.items():
        inner = ", ".join(f"{k}: {v}" for k, v in sorted(m.items()))
        lines.append(f"\t\t\t{gostate(state)}: {{{inner}}},")
    lines.append("\t\t},")
    return lines


def emit_dropmap(name, d):
    lines = [f"\t\t{name}: map[State]map[int32]bool{{"]
    for state, ids in d.items():
        inner = ", ".join(f"{i}: true" for i in ids)
        lines.append(f"\t\t\t{gostate(state)}: {{{inner}}},")
    lines.append("\t\t},")
    return lines


L = [
    "// Code generated by scripts/gen_protomap.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// protoSteps holds the packet-ID remap for each adjacent protocol step, keyed",
    "// by the UPPER protocol version. Maps list only IDs that differ between the two",
    "// versions (identity otherwise). See translate_chain.go for how steps compose.",
    "var protoSteps = map[int32]idRemap{",
]
for hi, lo, cbUp, cbDrop, sbDown, sbDrop in steps:
    L.append(f"\t{hi}: {{ // {lo} -> {hi}")
    L.append(f"\t\tlower: {lo}, upper: {hi},")
    if cbUp:
        L += emit_idmap("cbUp", cbUp)
    if cbDrop:
        L += emit_dropmap("cbDrop", cbDrop)
    if sbDown:
        L += emit_idmap("sbDown", sbDown)
    if sbDrop:
        L += emit_dropmap("sbDrop", sbDrop)
    L.append("\t},")
L += ["}", ""]

with open(OUT, "w") as f:
    f.write("\n".join(L))

# Report
print(f"wrote {OUT}")
for hi, lo, cbUp, cbDrop, sbDown, sbDrop in steps:
    cb = sum(len(v) for v in cbUp.values())
    sb = sum(len(v) for v in sbDown.values())
    print(f"  {lo}->{hi}: clientbound idΔ={cb}, serverbound idΔ={sb}, "
          f"cbDrop={sum(len(v) for v in cbDrop.values())}, sbDrop={sum(len(v) for v in sbDrop.values())}")
