#!/usr/bin/env python3
"""Generate internal/server/noteinstruments_gen.go — the instrument each block
gives a note block above it, by block-state range.

Two facts, both the canonical version's (scripts/canon.py):

  * the instrument names, in the order the note block's own `instrument`
    property lists them (the blocks report) — tachyne's internal index, where
    0 is harp;
  * each block's instrument, as the running game reports it (the extractor):
    BlockBehaviour.instrument(), a property of the block, so every state of a
    block has the same one.

Runs of consecutive states with the same instrument are merged, and harp
runs are left out: harp is the default on a lookup miss.

    python3 scripts/gen_noteinstruments.py     # canonical version: canon.py
"""
import json
import os

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "noteinstruments_gen.go")

names = json.load(open(canon.report("blocks.json")))["minecraft:note_block"]["properties"]["instrument"]
if names[0] != "harp":
    raise SystemExit("the note block's first instrument is %r, not harp" % names[0])
index = {n: i for i, n in enumerate(names)}

runs = []  # [base, count, instr]
for b in sorted(json.load(open(canon.extract()))["blocks"], key=lambda b: b["minStateId"]):
    instr = index[b["instrument"]]
    lo, n = b["minStateId"], b["maxStateId"] - b["minStateId"] + 1
    if runs and runs[-1][2] == instr and runs[-1][0] + runs[-1][1] == lo:
        runs[-1][1] += n
    else:
        runs.append([lo, n, instr])
runs = [r for r in runs if r[2] != 0]

L = ["// Code generated by scripts/gen_noteinstruments.py from vanilla block data. DO NOT EDIT.",
     "",
     "package server",
     "",
     "// noteInstrumentNames are the vanilla note-block instrument names by",
     "// tachyne's internal instrument index. The indexes are internal (not a",
     "// wire enum): 0 is always harp, the vanilla default; gateways and sound",
     "// lookups go through the names.",
     "var noteInstrumentNames = []string{"]
L += ['\t"%s",' % n for n in names]
L += ["}",
      "",
      "// noteInstrRange maps a contiguous run of block-state ids (canonical",
      "// %s) to an instrument index. States not covered by any range use" % canon.VERSION,
      "// the default instrument (0 = harp), so harp runs are omitted.",
      "type noteInstrRange struct {",
      "\tbase, count uint32",
      "\tinstr       uint8",
      "}",
      "",
      "var noteInstrumentRanges = []noteInstrRange{"]
L += ["\t{%d, %d, %d}," % tuple(r) for r in runs]
L += ["}",
      "",
      "// noteInstrumentFor returns the instrument index for a block state id;",
      "// 0 (harp, the vanilla default) on a lookup miss.",
      "func noteInstrumentFor(state uint32) uint8 {",
      "\tlo, hi := 0, len(noteInstrumentRanges)-1",
      "\tfor lo <= hi {",
      "\t\tmid := int(uint(lo+hi) >> 1)",
      "\t\tr := noteInstrumentRanges[mid]",
      "\t\tswitch {",
      "\t\tcase state < r.base:",
      "\t\t\thi = mid - 1",
      "\t\tcase state >= r.base+r.count:",
      "\t\t\tlo = mid + 1",
      "\t\tdefault:",
      "\t\t\treturn r.instr",
      "\t\t}",
      "\t}",
      "\treturn 0",
      "}",
      ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print("wrote %s: %d instruments, %d ranges" % (os.path.normpath(OUT), len(names), len(runs)))
