#!/usr/bin/env python3
"""Bake every biome's natural-spawn pools (data/minecraft/worldgen/biome/*.json
"spawners" + creature_spawn_probability) from the canonical server jar into
internal/server/spawnpools_gen.go. Facts only: the biome data is what
vanilla's NaturalSpawner draws from (MobSpawnSettings)."""
import io, json, os, sys, zipfile

JAR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "spawnpools_gen.go")

outer = zipfile.ZipFile(JAR)
inner = [n for n in outer.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
z = zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer

rows = []
for n in sorted(z.namelist()):
    if not (n.startswith("data/minecraft/worldgen/biome/") and n.endswith(".json")):
        continue
    b = json.loads(z.read(n))
    name = "minecraft:" + n.split("/")[-1][:-5]
    prob = b.get("creature_spawn_probability", 0.1)
    costs = []
    for et, c in sorted(b.get("spawn_costs", {}).items()):
        costs.append((et.removeprefix("minecraft:"), c["charge"], c["energy_budget"]))
    entries = []
    for cat, es in sorted(b.get("spawners", {}).items()):
        for e in es:
            entries.append((cat, e["type"].removeprefix("minecraft:"), e["weight"], e["minCount"], e["maxCount"]))
    rows.append((name, prob, entries, costs))

with open(OUT, "w") as f:
    f.write("// Code generated by scripts/gen_spawnpools.py from the canonical biome data; DO NOT EDIT.\n\n")
    f.write("package server\n\n")
    f.write("// biomeSpawnRow is one weighted spawner entry of a biome's MobSpawnSettings.\n")
    f.write("type biomeSpawnRow struct {\n\tcat, etype       string\n\tweight, min, max int\n}\n\n")
    f.write("// biomeSpawnDef is a biome's spawners and its creature-generation probability.\n")
    f.write("type biomeSpawnDef struct {\n\tprob  float32\n\trows  []biomeSpawnRow\n\tcosts []biomeSpawnCost\n}\n\n")
    f.write("// biomeSpawnCost is a MobSpawnCost: a species' charge and energy budget.\n")
    f.write("type biomeSpawnCost struct {\n\tetype          string\n\tcharge, budget float64\n}\n\n")
    f.write("var biomeSpawnDefs = map[string]biomeSpawnDef{\n")
    for name, prob, entries, costs in rows:
        f.write('\t"%s": {%g, []biomeSpawnRow{\n' % (name, prob))
        for cat, et, w, lo, hi in entries:
            f.write('\t\t{"%s", "%s", %d, %d, %d},\n' % (cat, et, w, lo, hi))
        if costs:
            f.write("\t}, []biomeSpawnCost{\n")
            for et, ch, bu in costs:
                f.write('\t\t{"%s", %g, %g},\n' % (et, ch, bu))
            f.write("\t}},\n")
        else:
            f.write("\t}, nil},\n")
    f.write("}\n")
print(f"wrote {OUT}: {len(rows)} biomes")
