#!/usr/bin/env python3
"""Generate internal/protocol/blockentities_gen.go.

Blocks like beds, chests, signs and banners render via a client-side block-entity
renderer: without a block entity present the client draws only the block outline
("wireframe"). Our chunk packets must therefore list the block entities in a chunk,
each as (packed XZ, Y, block_entity_type id, NBT). For rendering, empty NBT
(TAG_End) is enough — the type + position instantiate the renderer.

This bakes a block-state-range -> block_entity_type-id table.

The block -> type association comes from the game: the local extract asks each
block_entity_type which blocks it is valid for (see scripts/extract). The type
ids come from vanilla's registries report, which gives network order directly —
block_entity_type is a static registry, so its ids are REGISTRATION order, and
an alphabetical source once produced wrong ones here.

The association used to be guessed from block names, and the guess missed 12
blocks at 1.21.11 — among them end_portal and end_gateway, which draw ONLY
through their block entity (RenderShape.INVISIBLE), so a lit stronghold portal
or a post-dragon gateway reached clients with nothing to render; and every
weathered or waxed copper golem statue, where the list knew only the plain one.

    python3 scripts/gen_blockentities.py [version]     # default 1.21.11
"""
import json, os, subprocess, sys

import vanillareport

VER = sys.argv[1] if len(sys.argv) > 1 else "1.21.11"
EXTRACT = os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "blockentities_gen.go")

id_of = {e["name"]: e["id"] for e in vanillareport.registry(VER, "block_entity_type")}

# Left out deliberately. A moving_piston is the transient block a piston leaves
# while something travels; the engine animates that through its own attach frame
# rather than a chunk block entity, so it is not listed here.
SKIP = {"moving_piston"}

rows = []  # (min, max, type_id)
for b in json.load(open(EXTRACT))["blocks"]:
    be = b.get("blockEntityType")
    if be is None or b["name"] in SKIP:
        continue
    if be not in id_of:
        raise SystemExit(f"block_entity_type {be!r} (for {b['name']}) not in registry")
    rows.append((b["minStateId"], b["maxStateId"], id_of[be]))
rows.sort()

L = [
    "// Code generated by scripts/gen_blockentities.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// blockEntityRanges maps a block-state range to its block_entity_type network id",
    "// (block_entity_type registry order). Sorted by Min for binary search. Used to",
    "// list a chunk's block entities so beds/chests/signs render instead of showing",
    "// only their wireframe outline after the chunk (re)loads.",
    "var blockEntityRanges = []struct {",
    "\tMin, Max uint32",
    "\tType     int32",
    "}{",
]
for mn, mx, t in rows:
    L.append(f"\t{{{mn}, {mx}, {t}}},")
L += [
    "}",
    "",
    "// BlockEntityType returns the block_entity_type id for a block state and whether",
    "// the block has a block entity at all.",
    "func BlockEntityType(state uint32) (int32, bool) {",
    "\tlo, hi := 0, len(blockEntityRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := blockEntityRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.Type, true",
    "\t\t}",
    "\t}",
    "\treturn 0, false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(rows)} block-entity ranges")
