#!/usr/bin/env python3
"""Generate internal/server/vanillatags_gen.go — the vanilla pack's own tag
FILES (not their resolution) for the registries a data pack's tags are
applied to: item, block, entity_type, fluid and worldgen/biome.

A data pack's tag file merges onto the vanilla file of the same id the way
TagLoader merges every pack's file for an id, bottom to top, before any tag
is resolved — so a pack that adds one item to #minecraft:planks keeps the
planks vanilla lists, and a pack nesting #minecraft:logs sees its members.
That needs the vanilla entries as written (nested #tags and optional
entries kept), which is what this table holds; packtags.go resolves them.

Each entry is written as the file writes it: "minecraft:oak_log", a nested
"#minecraft:logs", and a trailing "?" for {"id": …, "required": false}.

    python3 scripts/gen_vanillatags.py     # canonical version: canon.py

Stdlib only; reads the canonical server jar, no network.
"""
import json
import os

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "vanillatags_gen.go")

REGISTRIES = ["item", "block", "entity_type", "fluid", "worldgen/biome"]


def entries(data):
    out = []
    for v in data.get("values", []):
        if isinstance(v, str):
            out.append(v)
        else:
            s = v["id"]
            if v.get("required", True) is False:
                s += "?"
            out.append(s)
    return out


def main():
    z = canon.inner_jar()
    names = z.namelist()
    tables = {r: {} for r in REGISTRIES}
    for n in sorted(names):
        if not n.startswith("data/") or not n.endswith(".json"):
            continue
        parts = n.split("/")
        if len(parts) < 5 or parts[2] != "tags":
            continue
        ns = parts[1]
        rest = "/".join(parts[3:])
        for reg in REGISTRIES:
            prefix = reg + "/"
            if rest.startswith(prefix):
                tid = ns + ":" + rest[len(prefix):-len(".json")]
                tables[reg][tid] = entries(json.loads(z.read(n)))
                break

    lines = [
        "// Code generated by scripts/gen_vanillatags.py from the vanilla datapack. DO NOT EDIT.",
        "",
        "package server",
        "",
        "// vanillaTagFiles is the vanilla pack's tag files for the registries a data",
        "// pack's tags apply to (canonical " + canon.VERSION + "), by registry and tag id: each",
        "// file's entries as written — an id, a nested #tag, a trailing ? for an",
        "// optional entry. Data pack files merge onto these (packtags.go).",
        "var vanillaTagFiles = map[string]map[string][]string{",
    ]
    for reg in REGISTRIES:
        lines.append("\t%s: {" % json.dumps(reg))
        for tid in sorted(tables[reg]):
            vals = ", ".join(json.dumps(v) for v in tables[reg][tid])
            lines.append("\t\t%s: {%s}," % (json.dumps(tid), vals))
        lines.append("\t},")
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s: %s" % (OUT, ", ".join("%s %d" % (r, len(tables[r])) for r in REGISTRIES)))


if __name__ == "__main__":
    main()
