#!/usr/bin/env python3
"""Generate internal/anvil/palette_gen.go — the reverse block-state table.

The Anvil world format stores block states by NAME + property map, while the
engine works in numeric canonical state ids. This emits the full reverse
table (state id -> block name + ordered property layout) from the vanilla
data-generator blocks.json report, so the Anvil exporter can reconstruct
every state's palette entry exactly.

Input: a local datagen report (blocks.json). No network needed.

  python3 scripts/gen_anvilpalette.py ~/vanilla/reports/1.21.11/blocks.json
"""
import json, os, sys

IN = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    "~/vanilla/reports/1.21.11/blocks.json")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "anvil",
                   "palette_gen.go")

blocks = json.load(open(IN))
rows = []
for name, b in blocks.items():
    states = b["states"]
    ids = [s["id"] for s in states]
    base, top = min(ids), max(ids)
    if top - base + 1 != len(states):
        raise SystemExit(f"{name}: non-contiguous state range")
    props = b.get("properties", {})
    # Vanilla enumerates states mixed-radix over properties sorted by NAME
    # (StateDefinition keeps a sorted map), most significant first. Verify so
    # decode can be arithmetic.
    order = sorted(props.keys())
    for s in states:
        idx = 0
        for p in order:
            vals = props[p]
            idx = idx * len(vals) + vals.index(s["properties"][p])
        if base + idx != s["id"]:
            raise SystemExit(f"{name}: state enumeration is not mixed-radix")
    rows.append((base, name, order, props))
rows.sort()

# Contiguity across blocks lets decode binary-search on base alone.
for (b1, n1, o1, p1), (b2, n2, _, _) in zip(rows, rows[1:]):
    count = 1
    for p in o1:
        count *= len(p1[p])
    if b1 + count != b2:
        raise SystemExit(f"gap between {n1} and {n2}")

with open(OUT, "w") as f:
    f.write("// Code generated by scripts/gen_anvilpalette.py from the vanilla\n")
    f.write("// data-generator blocks.json report. DO NOT EDIT.\n")
    f.write("//\n")
    f.write("// The full reverse block-state table: every canonical state id maps to a\n")
    f.write("// block name plus its ordered property layout (first property most\n")
    f.write("// significant, vanilla's enumeration), so the exporter can rebuild the\n")
    f.write("// exact Anvil palette entry for any state.\n\n")
    f.write("package anvil\n\n")
    f.write("type propDef struct {\n\tname string\n\tvals []string\n}\n\n")
    f.write("type blockDef struct {\n\tbase  uint32\n\tname  string\n\tprops []propDef\n}\n\n")
    f.write("// blockDefs is sorted by base state id; ranges are contiguous.\n")
    f.write("var blockDefs = []blockDef{\n")
    for base, name, order, props in rows:
        f.write(f"\t{{{base}, {json.dumps(name)}, ")
        if not order:
            f.write("nil},\n")
            continue
        f.write("[]propDef{")
        f.write(", ".join(
            "{%s, []string{%s}}" % (json.dumps(p),
                                    ", ".join(json.dumps(v) for v in props[p]))
            for p in order))
        f.write("}},\n")
    f.write("}\n")

total = sum(1 for _ in rows)
print(f"wrote {OUT} with {total} blocks")
