#!/usr/bin/env python3
"""Generate internal/worldgen/blockregistry_gen.go: block registry name → id
(the minecraft:block registry, NOT block states) from the canonical
registries report. Block-event frames carry this id.

Run: python3 scripts/gen_blockregistry.py [path-to-registries.json]
"""
import json
import os
import subprocess
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/reports/1.21.11/registries.json")
OUT = "internal/worldgen/blockregistry_gen.go"

entries = json.load(open(SRC))["minecraft:block"]["entries"]
rows = sorted((v["protocol_id"], k.split(":", 1)[1]) for k, v in entries.items())
lines = ["// Code generated by scripts/gen_blockregistry.py from the canonical registries report; DO NOT EDIT.",
         "", "package worldgen", "",
         "// blockRegistryID is the minecraft:block registry (block ids, not states).",
         "var blockRegistryID = map[string]uint32{"]
for pid, name in rows:
    lines.append(f'\t"{name}": {pid},')
lines.append("}")
open(OUT, "w").write("\n".join(lines) + "\n")
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(rows)} blocks")
