#!/usr/bin/env python3
"""Generate ../tachyne-common/protocol/stonecutting_gen.go.

Stonecutting recipes from the vanilla 1.21.11 server jar's datapack
(recipe/*.json, type minecraft:stonecutting). Multi-item ingredients expand
to one row per input item. Order is the sorted recipe path (deterministic):
the SAME slice drives both the gateway's update_recipes packet and the
engine's menu, so the client's button index and the server's selection
agree by construction.

Run: python3 scripts/gen_stonecutting.py [path-to-server.jar]
(needs network only for the minecraft-data items.json id map)
"""
import io, json, sys, urllib.request, os, subprocess, zipfile

ITEMS = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
JAR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "stonecutting_gen.go")

item_id = {i["name"]: i["id"] for i in json.load(urllib.request.urlopen(ITEMS))}

outer = zipfile.ZipFile(JAR)
inner = [n for n in outer.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
z = zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer

rows = []
for path in sorted(z.namelist()):
    if not (path.startswith("data/minecraft/recipe/") and path.endswith(".json")):
        continue
    r = json.loads(z.read(path))
    if r.get("type") != "minecraft:stonecutting":
        continue
    result = r["result"]["id"].removeprefix("minecraft:")
    count = r["result"].get("count", 1)
    if result not in item_id:
        continue
    ing = r["ingredient"]
    for name in ([ing] if isinstance(ing, str) else ing):
        name = name.removeprefix("minecraft:")
        if name in item_id:
            rows.append((item_id[name], item_id[result], count))

L = [
    "// Code generated by tachyne-world/scripts/gen_stonecutting.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// StonecuttingRecipe is one stonecutter row: input item, result item, count.",
    "type StonecuttingRecipe struct {",
    "\tIn, Out int32",
    "\tCount   int8",
    "}",
    "",
    "// StonecuttingRecipes lists the vanilla stonecutting recipes in a fixed",
    "// order. The gateway's update_recipes packet and the engine's stonecutter",
    "// menu both derive from THIS slice, so the client's visible list (filtered",
    "// by input, order preserved) and the server's button indices always agree.",
    "var StonecuttingRecipes = []StonecuttingRecipe{",
]
for inp, out, cnt in rows:
    L.append(f"\t{{{inp}, {out}, {cnt}}},")
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(rows)} rows")
