#!/usr/bin/env python3
"""Generate internal/server/foods_gen.go from the local extract (scripts/extract).

Maps an edible item id to the hunger points it restores and the saturation it
restores — the game's own FOOD component (nutrition, and saturation already
worked out as nutrition × modifier × 2: apple 2.4, bread 6.0, steak 12.8).

It used to read minecraft-data's foods.json, whose saturation fields had to be
rescaled by hand — and at 26.1 one of them changed meaning to the bare
modifier, which would have made every food restore about an eighth of its
saturation. Reading the game avoids guessing at a third party's units.

    python3 scripts/gen_foods.py [version]     # default 1.21.11
"""
import json, os, sys

VER = sys.argv[1] if len(sys.argv) > 1 else "1.21.11"
EXTRACT = os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "foods_gen.go")

foods = [i for i in json.load(open(EXTRACT))["items"] if "nutrition" in i]
rows = sorted((f["id"], f["nutrition"], f["saturation"], f["name"]) for f in foods)

lines = [
    "// Code generated by scripts/gen_foods.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// foodPoints maps an edible item id to the hunger points eating it restores.",
    "var foodPoints = map[int32]int{",
]
for iid, pts, sat, name in rows:
    lines.append(f"\t{iid}: {pts}, // {name}")
lines += [
    "}",
    "",
    "// foodSaturation maps an edible item id to the saturation eating it restores",
    "// (vanilla: foodPoints × saturationModifier × 2).",
    "var foodSaturation = map[int32]float32{",
]
for iid, pts, sat, name in rows:
    lines.append(f"\t{iid}: {sat:g}, // {name}")
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} foods")
