#!/usr/bin/env python3
"""Generate internal/server/entityids_gen.go — entity name → network type id.

So the engine names entities instead of hard-coding numeric type ids that churn
every version. From minecraft-data's canonical-version entities.json. Run outside
the sandbox (needs network):  python3 scripts/gen_entityids.py
"""
import json, urllib.request, os
URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/entities.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "entityids_gen.go")
ents = sorted(json.load(urllib.request.urlopen(URL)), key=lambda e: e["name"])
with open(OUT, "w") as f:
    f.write("// Code generated by scripts/gen_entityids.py from minecraft-data. DO NOT EDIT.\n")
    f.write("// Entity name (no namespace) → network type id, so the engine names entities\n")
    f.write("// instead of hard-coding numeric ids that shift every Minecraft version.\n\n")
    f.write("package server\n\n")
    f.write("var entityByName = map[string]int{\n")
    for e in ents:
        f.write(f'\t{json.dumps(e["name"])}: {e["id"]},\n')
    f.write("}\n\n")
    f.write('''// entityID returns an entity type's network id by name, panicking on an unknown
// name so a typo fails loudly at startup.
func entityID(name string) int {
	id, ok := entityByName[name]
	if !ok {
		panic("server: unknown entity name " + name)
	}
	return id
}
''')
print(f"wrote {OUT} with {len(ents)} entities")
