#!/usr/bin/env python3
"""Generate internal/protocol/protomap_26x_gen.go: packet-ID remap steps for the
26.x protocol versions (775/776) that minecraft-data does not cover.

minecraft-data has no protocol.json for 26.x, so the packet IDs come from
ViaVersion's packet ENUMS instead (each entry carries `NAME, // 0xNN`). We diff
ViaVersion's own enums across versions by name (consistent naming, so no
minecraft-data↔ViaVersion name friction). ViaVersion's 1.21.11 IDs equal our
canonical 774 IDs (verified: LEVEL_CHUNK_WITH_LIGHT 0x2C, PLAYER_INFO_UPDATE 0x44),
so the derived 775 step chains cleanly onto the minecraft-data 774 step.

Findings baked in here:
  - 774→775 (1.21.11 → 26.1): clientbound +2 packets / serverbound +3, play only.
    Configuration/Login IDs are unchanged (26.1 reuses the 1.21.9 config packets).
  - 775→776 (26.1 → 26.2): NO packet-ID changes (26.2 reuses 26.1's packet enums),
    so step 776 is an empty ID remap (its body/registry changes live elsewhere).

These are READ from ViaVersion (GPL) as protocol facts (packet IDs), then emitted as
our own table — no ViaVersion code is copied.

Run outside the sandbox (needs network):  python3 scripts/gen_protomap_26x.py
"""
import json, urllib.request, os, re

RAW = "https://raw.githubusercontent.com/ViaVersion/ViaVersion/master/common/src/main/java/com/viaversion/viaversion/protocols/{}"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "protocol", "protomap_26x_gen.go")

# 774 baselines: clientbound = ViaVersion 1.21.11 enum; serverbound = 1.21.6 enum
# (ViaVersion reuses it through 1.21.11 — serverbound was unchanged since 1.21.6).
ENUMS = {
    "cb774": "v1_21_9to1_21_11/packet/ClientboundPackets1_21_11.java",
    "cb775": "v1_21_11to26_1/packet/ClientboundPackets26_1.java",
    "sb774": "v1_21_5to1_21_6/packet/ServerboundPackets1_21_6.java",
    "sb775": "v1_21_11to26_1/packet/ServerboundPackets26_1.java",
}

LINE = re.compile(r"^\s+([A-Z][A-Z0-9_]*)\b.*//\s*0x([0-9A-Fa-f]+)")


def parse_enum(path):
    name2id = {}
    with urllib.request.urlopen(RAW.format(path)) as r:
        for line in r.read().decode().splitlines():
            m = LINE.match(line)
            if m:
                name2id[m.group(1)] = int(m.group(2), 16)
    return name2id


e = {k: parse_enum(p) for k, p in ENUMS.items()}


def diff_clientbound(lo, hi):
    """canonical(lower) id -> upper id for shifted packets; drops for removed."""
    up, drop = {}, []
    for name, lid in lo.items():
        if name in hi:
            if hi[name] != lid:
                up[lid] = hi[name]
        else:
            drop.append(lid)
    return up, sorted(drop)


def diff_serverbound(lo, hi):
    """upper id -> canonical(lower) id for shifted packets; drops for new packets."""
    down, drop = {}, []
    for name, uid in hi.items():
        if name in lo:
            if lo[name] != uid:
                down[uid] = lo[name]
        else:
            drop.append(uid)
    return down, sorted(drop)


cbUp, cbDrop = diff_clientbound(e["cb774"], e["cb775"])
sbDown, sbDrop = diff_serverbound(e["sb774"], e["sb775"])
print(f"774->775: clientbound idΔ={len(cbUp)} drop={len(cbDrop)}, "
      f"serverbound idΔ={len(sbDown)} drop={len(sbDrop)}")


def imap(d):
    return "{" + ", ".join(f"{k}: {v}" for k, v in sorted(d.items())) + "}"


def dmap(ids):
    return "{" + ", ".join(f"{i}: true" for i in ids) + "}"


L = [
    "// Code generated by scripts/gen_protomap_26x.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// Packet-ID remap steps for 26.x (775/776), derived from ViaVersion packet enums",
    "// (minecraft-data has no 26.x protocol). Registered into protoSteps at init so the",
    "// chain can compose them. 26.2 reuses 26.1's packet enums, so step 776 has no ID",
    "// changes (its body/registry differences are handled by stepBody + translation).",
    "func init() {",
    "\tprotoSteps[775] = idRemap{",
    "\t\tlower: 774, upper: 775,",
    f"\t\tcbUp:   map[State]map[int32]int32{{StatePlay: {imap(cbUp)}}},",
    f"\t\tsbDown: map[State]map[int32]int32{{StatePlay: {imap(sbDown)}}},",
]
if sbDrop:
    L.append(f"\t\tsbDrop: map[State]map[int32]bool{{StatePlay: {dmap(sbDrop)}}},")
if cbDrop:
    L.append(f"\t\tcbDrop: map[State]map[int32]bool{{StatePlay: {dmap(cbDrop)}}},")
L += [
    "\t}",
    "\tprotoSteps[776] = idRemap{lower: 775, upper: 776} // 26.2 reuses 26.1 packet IDs",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"wrote {OUT}")
