#!/usr/bin/env python3
"""Generate internal/server/foods_gen.go from minecraft-data foods.json.

Maps an edible item id to the hunger points it restores (foodPoints) and the
saturation it restores. minecraft-data's `saturation` field is mis-scaled, but
`saturationRatio` = foodPoints × saturationModifier × 4, and the real in-game
saturation = foodPoints × saturationModifier × 2 = saturationRatio / 2 (verified:
apple 4.8/2=2.4, bread 12/2=6.0, steak 25.6/2=12.8).

Run outside the sandbox (needs network):  python3 scripts/gen_foods.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/foods.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "foods_gen.go")

foods = json.load(urllib.request.urlopen(URL))
rows = sorted((f["id"], int(round(f["foodPoints"])), f["saturationRatio"] / 2.0, f["name"]) for f in foods)

lines = [
    "// Code generated by scripts/gen_foods.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// foodPoints maps an edible item id to the hunger points eating it restores.",
    "var foodPoints = map[int32]int{",
]
for iid, pts, sat, name in rows:
    lines.append(f"\t{iid}: {pts}, // {name}")
lines += [
    "}",
    "",
    "// foodSaturation maps an edible item id to the saturation eating it restores",
    "// (vanilla: foodPoints × saturationModifier × 2).",
    "var foodSaturation = map[int32]float32{",
]
for iid, pts, sat, name in rows:
    lines.append(f"\t{iid}: {sat:g}, // {name}")
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} foods")
