#!/usr/bin/env python3
"""Regenerate internal/server/damagetags_gen.go — every damage type and the
tags it belongs to.

Vanilla decides what a hit does to you from the damage TYPE'S TAGS, not from
the thing that dealt it: bypasses_armor says armour neither absorbs the blow
nor wears from it, bypasses_shield says raising a shield will not help,
bypasses_resistance / bypasses_effects / bypasses_enchantments each carve out
one mitigation, and the is_* family is what the protection enchantments key
on. Hard-coding those memberships is how you end up protecting against the
wrong things, so they are generated from the vanilla data instead.

Tag values may reference OTHER tags (bypasses_shield contains #bypasses_armor),
so references are resolved transitively before the bits are emitted.

Reads the canonical server jar's built-in datapack — no network. Behaviour is
audited against the newest tree, but these tags are identical there bar one
entry for content that does not exist canonically, so canonical wins.

Run from the repo root:  python3 scripts/gen_damagetags.py

Stdlib only.
"""
import io
import json
import os
import zipfile

VERSION = "1.21.11"
JAR = os.path.expanduser(f"~/vanilla/server-{VERSION}.jar")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "server", "damagetags_gen.go")


def datapack():
    """The server jar's built-in datapack (it is nested inside the launcher jar)."""
    outer = zipfile.ZipFile(JAR)
    inner = [n for n in outer.namelist()
             if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    return zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer


def read_dir(z, prefix):
    """basename -> parsed json, for every .json directly under prefix."""
    out = {}
    for path in z.namelist():
        if path.startswith(prefix) and path.endswith(".json"):
            rest = path[len(prefix):]
            if "/" not in rest:
                out[rest[:-len(".json")]] = json.loads(z.read(path))
    return out


def entry_id(v):
    """A tag entry is either a plain id or {"id": ..., "required": false}."""
    return v["id"] if isinstance(v, dict) else v


def resolve(name, raw, seen=None):
    """The damage types in a tag, following #tag references transitively."""
    seen = seen or set()
    if name in seen:
        raise SystemExit(f"tag cycle at {name}")
    seen = seen | {name}
    out = set()
    for v in raw[name]["values"]:
        ident = entry_id(v).removeprefix("minecraft:")
        if ident.startswith("#"):
            out |= resolve(ident[1:].removeprefix("minecraft:"), raw, seen)
        else:
            out.add(ident)
    return out


def camel(s):
    return "".join(p.capitalize() for p in s.split("_"))


def main():
    z = datapack()
    types = sorted(read_dir(z, "data/minecraft/damage_type/"))
    raw = read_dir(z, "data/minecraft/tags/damage_type/")
    tags = sorted(raw)
    if len(tags) > 64:
        raise SystemExit(f"{len(tags)} tags no longer fit in a uint64 bitset")

    members = {t: resolve(t, raw) for t in tags}
    for t, ms in members.items():
        for m in ms:
            if m not in types:
                raise SystemExit(f"tag {t} names unknown damage type {m}")

    L = [
        "// Code generated by scripts/gen_damagetags.py. DO NOT EDIT.",
        "",
        "package server",
        "",
        "// dmgTag is one vanilla damage-type tag, as a bit. The tags answer the",
        "// questions the damage pipeline asks of every hit — whether armour absorbs",
        "// it, whether a shield stops it, which protection enchantment guards it.",
        "type dmgTag uint64",
        "",
        "const (",
    ]
    for i, t in enumerate(tags):
        bit = f"tag{camel(t)}"
        decl = f"\t{bit} dmgTag = 1 << iota" if i == 0 else f"\t{bit}"
        L.append(decl)
    L += [
        ")",
        "",
        "// dmgType names one vanilla damage type. The type travels with the damage",
        "// from wherever it was dealt, because by the time a hit reaches the armour",
        "// there is no way to tell a lava burn from a starving stomach.",
        "type dmgType uint8",
        "",
        "const (",
    ]
    for i, t in enumerate(types):
        name = f"dt{camel(t)}"
        L.append(f"\t{name} dmgType = iota" if i == 0 else f"\t{name}")
    L += [
        ")",
        "",
        "// dmgTypeNames is the registry name of each damage type, for diagnostics.",
        "var dmgTypeNames = [...]string{",
    ]
    for t in types:
        L.append(f'\tdt{camel(t)}: "{t}",')
    L += [
        "}",
        "",
        "// dmgTypeTags is the tag set of each damage type.",
        "var dmgTypeTags = [...]dmgTag{",
    ]
    for t in types:
        bits = [f"tag{camel(tag)}" for tag in tags if t in members[tag]]
        if bits:
            L.append(f"\tdt{camel(t)}: {' | '.join(bits)},")
    L += [
        "}",
        "",
        "// dmgTypeExhaustion is the food exhaustion each damage type costs, which",
        "// is a property of the type in vanilla and so belongs here rather than at",
        "// the ~20 places that deal damage. Types absent from this table cost",
        "// nothing (the vanilla default is 0.0).",
        "var dmgTypeExhaustion = [...]float32{",
    ]
    defs = read_dir(z, "data/minecraft/damage_type/")
    for t in types:
        exh = defs[t].get("exhaustion", 0.0)
        if exh:
            L.append(f"\tdt{camel(t)}: {exh},")
    L += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(L))
    print(f"wrote {OUT}: {len(types)} damage types, {len(tags)} tags")


if __name__ == "__main__":
    main()
