#!/usr/bin/env python3
"""Regenerate tachyne-common's protocol/items_gen.go from vanilla's reports.

Maps each placeable item id to the default block-state id of the block with the
same name. Used to resolve "what block does the held item place" when handling
block placement. Items without a matching block (tools, food, buckets, …) are
omitted, as are air.

Run from the repo root, OUTSIDE the sandbox (needs network):

    python3 scripts/gen_items.py

Stdlib only.
"""
import os
import sys

import vanillareport

VER = sys.argv[1] if len(sys.argv) > 1 else "1.21.11"
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "..", "tachyne-common", "protocol", "items_gen.go")


def main():
    items = vanillareport.registry(VER, "item")
    blocks = vanillareport.blocks(VER)
    block_default = {b["name"]: b["defaultState"] for b in blocks}

    pairs = sorted(
        (it["id"], block_default[it["name"]])
        for it in items
        if it["name"] != "air" and it["name"] in block_default
    )

    out = [
        "// Code generated by scripts/gen_items.py from the %s reports. DO NOT EDIT." % VER,
        "",
        "package protocol",
        "",
        "// itemToBlock maps an item id to the default block-state id of the block it",
        "// places. Only items that correspond to a block are present.",
        "var itemToBlock = map[int32]uint32{",
    ]
    for item_id, state in pairs:
        out.append(f"\t{item_id}: {state},")
    out += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(pairs)} placeable items")


if __name__ == "__main__":
    main()
