#!/usr/bin/env python3
"""Generate internal/server/effectcolors_gen.go — each mob effect's colour.

A potion's liquid colour is the mix of its effects' colours (PotionContents.
getColor), and without it every potion the server sends renders the default
purple: a healing potion and a poison look identical. The colours live only in
MobEffects' registration calls, so they are read from there — facts out of the
reference source, reimplemented here, never copied.

Run: python3 scripts/gen_effectcolors.py [path-to-MobEffects.java]
"""
import os, re, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser(
    "~/DecompilerMC/src/1.21.11/server/net/minecraft/world/effect/MobEffects.java")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "effectcolors_gen.go")

# register("name", new SomethingMobEffect(MobEffectCategory.X, 1234567)
# the colour is written either decimal (3402751) or hex (0x2552A5)
PAT = re.compile(r'register\(\s*"([a-z_]+)"\s*,\s*new\s+\w+\(\s*MobEffectCategory\.(\w+)\s*,\s*(0[xX][0-9a-fA-F]+|-?\d+)')

colors, cats = {}, {}
with open(SRC) as f:
    for name, cat, rgb in PAT.findall(f.read()):
        colors[name] = int(rgb, 0) & 0xFFFFFF
        cats[name] = cat

if not colors:
    sys.exit("no effects matched — has MobEffects' registration shape changed?")

L = ["// Code generated by scripts/gen_effectcolors.py; DO NOT EDIT.", "",
     "package server", "",
     "// effectColor is each effect's particle/liquid colour as vanilla registers",
     "// it in MobEffects. A potion's colour is the mix of the effects it carries",
     "// (PotionContents.getColor), and without these every potion renders the",
     "// default purple.", "",
     "var effectColorByName = map[string]int32{"]
w = max(len(n) for n in colors) + 3  # gofmt aligns the values
for name in sorted(colors):
    key = f'"{name}":'
    L.append(f'\t{key:<{w}} 0x{colors[name]:06X}, // {cats[name].lower()}')
L += ["}", ""]

with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"wrote {OUT}: {len(colors)} effect colours")
