#!/usr/bin/env python3
"""Generate internal/server/outline_gen.go: each block state's OUTLINE shape
(BlockState.getShape under an empty context) as its boxes, for the rays that
clip ClipContext.Block.OUTLINE rather than collision — the one a flower, a
tuft of grass or a torch stops although nothing collides with it.

Reads the runtime extract (scripts/extract, fields outlineBoxes and offset):
per state, null for the full cube, [] for no outline, otherwise the boxes
[minX, minY, minZ, maxX, maxY, maxZ] with the block's random nudge at the
origin taken back out; per block with a nudge, its type (xz / xyz) and
bounds. The full cube is the default and not listed; each distinct shape is
stored once and consecutive states sharing one are a single run.

    scripts/gen_outline.py [extract.json]

Stdlib only.
"""
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(__file__))
import canon  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "outline_gen.go")


def f(x):
    return repr(float(x))


def main():
    ext = json.load(open(sys.argv[1] if len(sys.argv) > 1 else canon.extract()))
    shapes, shape_ix = [], {}
    per_state, offsets, top = {}, [], 0
    for b in ext["blocks"]:
        if "outlineBoxes" not in b:
            sys.exit("the extract has no outlineBoxes: rerun scripts/extract")
        lo = b["minStateId"]
        for i, boxes in enumerate(b["outlineBoxes"]):
            sid = lo + i
            top = max(top, sid)
            if boxes is None:
                continue  # the full cube
            key = json.dumps(boxes)
            if key not in shape_ix:
                shape_ix[key] = len(shapes)
                shapes.append(boxes)
            per_state[sid] = shape_ix[key]
        if b.get("offset"):
            o = b["offset"]
            offsets.append((lo, b["maxStateId"], o["type"] == "xyz", o["maxHorizontal"], o["maxVertical"], b["name"]))

    runs = []
    for sid in sorted(per_state):
        v = per_state[sid]
        if runs and runs[-1][1] == sid - 1 and runs[-1][2] == v:
            runs[-1][1] = sid
        else:
            runs.append([sid, sid, v])

    lines = [
        "// Code generated by scripts/gen_outline.py; DO NOT EDIT.",
        "",
        "package server",
        "",
        "// outlineShapes is every distinct outline shape that is not the full",
        "// cube, as its boxes in block-local coordinates (un-nudged). An empty",
        "// list is no outline at all.",
        "var outlineShapes = [...][]outlineBox{",
    ]
    for boxes in shapes:
        inner = ", ".join("{" + ", ".join(f(v) for v in bx) + "}" for bx in boxes)
        lines.append("\t{" + inner + "},")
    lines += [
        "}",
        "",
        "// outlineRuns maps runs of block states to their outline shape; states",
        "// not listed are the full cube.",
        "var outlineRuns = [...]outlineRun{",
    ]
    for lo, hi, v in runs:
        lines.append(f"\t{{{lo}, {hi}, {v}}},")
    lines += [
        "}",
        "",
        "// outlineOffsets lists the blocks whose shape is nudged per position",
        "// (BlockBehaviour.Properties.offsetType).",
        "var outlineOffsets = [...]outlineOffset{",
    ]
    for lo, hi, xyz, mh, mv, name in offsets:
        lines.append(f"\t{{{lo}, {hi}, {str(xyz).lower()}, {f(mh)}, {f(mv)}}}, // {name}")
    lines += ["}", "", "// outlineStateCount is the size of the state registry the table covers.",
              f"const outlineStateCount = {top + 1}", ""]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    subprocess.run(["gofmt", "-w", OUT], check=True)
    print(f"wrote {OUT}: {len(shapes)} shapes, {len(runs)} runs, {len(offsets)} nudged blocks over {top + 1} states")


if __name__ == "__main__":
    main()
