#!/usr/bin/env python3
"""Generate tachyne-common/protocol/canonicalnames_gen.go — the canonical ids of
every entity type and item, and every block's default state, by name.

Hand-written tables in tachyne-common that need a particular entity (the
stand-ins for entities an older client lacks, the gateway's per-type
metadata fixes) name it and resolve the id here, so a canonical version
change regenerates this file instead of silently re-pointing every number.

    python3 scripts/gen_canonicalnames.py     # canonical version: canon.py
"""
import os

import canon
import vanillareport

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "canonicalnames_gen.go")

items = vanillareport.registry(canon.VERSION, "item")
blocks = vanillareport.blocks(canon.VERSION)
ents = vanillareport.registry(canon.VERSION, "entity_type")
attrs = vanillareport.registry(canon.VERSION, "attribute")
if [e["id"] for e in ents] != list(range(len(ents))):
    raise SystemExit("entity ids are not dense from 0")

L = ["// Code generated by tachyne-world/scripts/gen_canonicalnames.py; DO NOT EDIT.",
     "",
     "package protocol",
     "",
     "// CanonicalProtocol is the protocol whose clients number content exactly",
     "// as the engine does (%s): for them every id table is the identity." % canon.VERSION,
     "const CanonicalProtocol = %d" % canon.PROTOCOL,
     "",
     "// canonicalEntityIDs is every entity type's canonical (%s, protocol %d) id," % (canon.VERSION, canon.PROTOCOL),
     "// by name without the namespace. Code that needs an entity names it:",
     "// see CanonicalEntity.",
     "var canonicalEntityIDs = map[string]int32{"]
L += ['\t"%s": %d,' % (e["name"], e["id"]) for e in sorted(ents, key=lambda e: e["name"])]
L += ["}",
      "",
      "// canonicalItemIDs is every item's canonical id, by name.",
      "var canonicalItemIDs = map[string]int32{"]
L += ['\t"%s": %d,' % (e["name"], e["id"]) for e in sorted(items, key=lambda e: e["name"])]
L += ["}",
      "",
      "// canonicalBlockStates is every block's canonical DEFAULT state id, by name.",
      "var canonicalBlockStates = map[string]int32{"]
L += ['\t"%s": %d,' % (b["name"], b["defaultState"]) for b in sorted(blocks, key=lambda b: b["name"])]
L += ["}",
      "",
      "// canonicalAttributeIDs is every attribute's canonical registry id, by its",
      "// namespaced name (update_attributes carries these).",
      "var canonicalAttributeIDs = map[string]int32{"]
L += ['\t"minecraft:%s": %d,' % (e["name"], e["id"]) for e in sorted(attrs, key=lambda e: e["name"])]
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print("wrote %s: %d entity types, %d items, %d blocks" % (os.path.normpath(OUT), len(ents), len(items), len(blocks)))
