#!/usr/bin/env python3
"""Generate ../tachyne-common/protocol/tags26x_gen.go: the 26.2 tag set WITH contents.

26.x clients require every tag their item-component init references to be
present at config time; beyond presence, REAL contents restore client-side
mechanics (mineable/* mining speed, fire resistance, feeding hints).

Sources:
  - Tag values: misode/mcmeta tag 26.2-data-json (one tarball), tags under
    data/minecraft/tags/<registry>/<tag>.json; #refs resolve transitively.
  - Static-registry network ids (block/item/entity_type): ViaVersion
    mapping-26.2.json ordered lists (index = id). These are the CLIENT's ids.
  - Dynamic registries (damage_type, worldgen/biome, banner_pattern,
    instrument, painting_variant, timeline) resolve AT RUNTIME against the
    entry order this server declares in registry_data (see tags26x()).
  - Registries with no safe id source keep nil entries (sent empty).

Run outside the sandbox (needs network):  python3 scripts/gen_tags26x.py
"""
import io, json, tarfile, urllib.request, os, subprocess

TARBALL = "https://github.com/misode/mcmeta/archive/refs/tags/26.2-data-json.tar.gz"
VV = "https://raw.githubusercontent.com/ViaVersion/Mappings/main/mappings/mapping-26.2.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "tags26x_gen.go")

# Registries whose tag entries we emit (resolvable to ids). Everything else's
# tags are emitted with nil entries → sent empty (presence only).
EMIT = {"block", "item", "entity_type", "fluid", "damage_type", "worldgen/biome",
        "banner_pattern", "instrument", "painting_variant", "timeline"}

print("downloading mcmeta 26.2 datapack…")
tar = tarfile.open(fileobj=io.BytesIO(urllib.request.urlopen(TARBALL, timeout=180).read()), mode="r:gz")
tags = {}  # (registry, tag) -> raw json
for member in tar.getmembers():
    parts = member.name.split("/", 1)
    if len(parts) < 2 or not parts[1].startswith("data/minecraft/tags/") or not parts[1].endswith(".json"):
        continue
    path = parts[1].removeprefix("data/minecraft/tags/").removesuffix(".json")
    comps = path.split("/")
    if comps[0] == "worldgen":
        reg, tag = "worldgen/" + comps[1], "/".join(comps[2:])
    else:
        reg, tag = comps[0], "/".join(comps[1:])
    tags[(reg, tag)] = json.load(tar.extractfile(member))


def resolve(reg, tag, depth=0):
    """Flatten a tag to entry names, following #refs within the registry."""
    if depth > 8 or (reg, tag) not in tags:
        return []
    out = []
    for v in tags[(reg, tag)]["values"]:
        if isinstance(v, dict):
            v = v["id"]
        if v.startswith("#"):
            out += resolve(reg, v.lstrip("#").removeprefix("minecraft:"), depth + 1)
        else:
            out.append(v if ":" in v else "minecraft:" + v)
    seen, uniq = set(), []
    for e in out:
        if e not in seen:
            seen.add(e)
            uniq.append(e)
    return uniq


regs = {}  # registry -> {tag: entries or None}
for (reg, tag) in tags:
    entries = resolve(reg, tag) if reg in EMIT else None
    regs.setdefault(reg, {})[tag] = entries

vv = json.load(urllib.request.urlopen(VV, timeout=60))
maps = {"block26xID": vv["blocks"], "item26xID": vv["items"], "entity26xID": vv["entities"]}

L = [
    "// Code generated by scripts/gen_tags26x.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// tag26x is one 26.2 tag: entry NAMES resolve to ids at send time (static",
    "// registries via the generated maps below; dynamic registries against the",
    "// entry order this server declares). nil entries = deliberately sent empty.",
    "type tag26x struct {",
    "\tname    string",
    "\tentries []string",
    "}",
    "",
    "type tagReg26x struct {",
    "\tregistry string",
    "\ttags     []tag26x",
    "}",
    "",
    "var tags26xData = []tagReg26x{",
]
total = withEntries = 0
for reg in sorted(regs):
    L.append(f'\t{{"minecraft:{reg}", []tag26x{{')
    for tag in sorted(regs[reg]):
        total += 1
        entries = regs[reg][tag]
        if entries is None:
            L.append(f'\t\t{{"minecraft:{tag}", nil}},')
        else:
            withEntries += 1
            es = ", ".join(f'"{e}"' for e in entries)
            L.append(f'\t\t{{"minecraft:{tag}", []string{{{es}}}}},')
    L.append("\t}},")
L += ["}", ""]

for goname, lst in maps.items():
    L.append(f"// {goname}: 26.2 network ids by name (ViaVersion mappings order).")
    L.append(f"var {goname} = map[string]int32{{")
    for i, name in enumerate(lst):
        L.append(f'\t"minecraft:{name}": {i},')
    L += ["}", ""]

with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {total} tags ({withEntries} with entries), "
      f"maps: {', '.join(f'{k}={len(v)}' for k, v in maps.items())}")
