#!/usr/bin/env python3
"""Generate a packet-ID remap step between two adjacent protocol versions from
the vanilla datagen packet reports (reports/<ver>/reports/packets.json, made by
`java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports`).
Same literal shape as gen_protomap_26x.py, but local and authoritative: the
server's own report of its packet ids, no third-party enum parsing.

Usage: gen_protomap_reports.py <lowerReportsDir> <upperReportsDir> <lowerProto> <upperProto> <out.go>
"""
import json, sys

lo_dir, hi_dir, lo_v, hi_v, out = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5]
lo = json.load(open(lo_dir + "/packets.json"))
hi = json.load(open(hi_dir + "/packets.json"))
STATES = {"handshake": "StateHandshake", "status": "StateStatus", "login": "StateLogin",
          "configuration": "StateConfiguration", "play": "StatePlay"}

def ids(d): return {n: v["protocol_id"] for n, v in d.items()}

# A packet renamed between the versions maps by its old name (the body
# rewriter, if the payload changed, lives in translate_steps.go).
RENAMES = {"minecraft:punch": "minecraft:swing"}  # 26.3 serverbound

cbUp, cbDrop, sbDown, sbDrop = {}, {}, {}, {}
for state, sname in STATES.items():
    cl, ch = ids(lo.get(state, {}).get("clientbound", {})), ids(hi.get(state, {}).get("clientbound", {}))
    up = {cl[n]: ch[n] for n in cl if n in ch and cl[n] != ch[n]}
    drop = sorted(cl[n] for n in cl if n not in ch)
    if up: cbUp[sname] = up
    if drop: cbDrop[sname] = drop
    sl, sh = ids(lo.get(state, {}).get("serverbound", {})), ids(hi.get(state, {}).get("serverbound", {}))
    for new, old in RENAMES.items():
        if new in sh and old in sl and new not in sl:
            sh[old] = sh.pop(new)
    down = {sh[n]: sl[n] for n in sh if n in sl and sh[n] != sl[n]}
    sdrop = sorted(sh[n] for n in sh if n not in sl)
    if down: sbDown[sname] = down
    if sdrop: sbDrop[sname] = sdrop
    print(f"{state}: cb shifted {len(up)} dropped {drop} | sb shifted {len(down)} new(dropped) {sdrop}")

def gomap(m):
    return "map[State]map[int32]int32{" + ", ".join(
        f"{s}: {{" + ", ".join(f"{a}: {b}" for a, b in sorted(v.items())) + "}" for s, v in m.items()) + "}"
def gobool(m):
    return "map[State]map[int32]bool{" + ", ".join(
        f"{s}: {{" + ", ".join(f"{a}: true" for a in v) + "}" for s, v in m.items()) + "}"

L = [f"// Code generated by scripts/gen_protomap_reports.py from the {lo_v}/{hi_v} datagen packet reports; DO NOT EDIT.",
     "", "package protocol", "",
     f"// Packet-ID remap step {lo_v}→{hi_v}, from the servers' own packet reports.",
     "func init() {", f"\tprotoSteps[{hi_v}] = idRemap{{", f"\t\tlower: {lo_v}, upper: {hi_v},"]
if cbUp: L.append(f"\t\tcbUp:   {gomap(cbUp)},")
if cbDrop: L.append(f"\t\tcbDrop: {gobool(cbDrop)},")
if sbDown: L.append(f"\t\tsbDown: {gomap(sbDown)},")
if sbDrop: L.append(f"\t\tsbDrop: {gobool(sbDrop)},")
L += ["\t}", "}", ""]
open(out, "w").write("\n".join(L))
print("wrote", out)
