#!/usr/bin/env python3
"""Generate internal/worldgen/light_emission_gen.go from minecraft-data blocks.json.

Emits LightEmission(state) -> the light level a block state emits (0 if none),
as a sorted, non-overlapping range table with a binary search. Run outside the
sandbox (needs network):  python3 scripts/gen_light.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "light_emission_gen.go")

blocks = json.load(urllib.request.urlopen(URL))
rows = []
for b in blocks:
    lvl = b.get("emitLight", 0)
    if lvl > 0:
        rows.append((b["minStateId"], b["maxStateId"], lvl, b["name"]))
rows.sort()

lines = [
    "// Code generated by scripts/gen_light.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// lightRanges maps block-state ID ranges to the light level they emit, sorted",
    "// by lo and non-overlapping so LightEmission can binary-search them.",
    "var lightRanges = []struct {",
    "\tlo, hi uint32",
    "\tlvl    uint8",
    "}{",
]
for lo, hi, lvl, name in rows:
    lines.append(f"\t{{{lo}, {hi}, {lvl}}}, // {name}")
lines += [
    "}",
    "",
    "// LightEmission returns the block-light level a state emits, 0 if it emits none.",
    "func LightEmission(state uint32) uint8 {",
    "\tlo, hi := 0, len(lightRanges)",
    "\tfor lo < hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := lightRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.lo:",
    "\t\t\thi = mid",
    "\t\tcase state > r.hi:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.lvl",
    "\t\t}",
    "\t}",
    "\treturn 0",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} emitting block ranges")
