#!/usr/bin/env python3
"""Generate internal/worldgen/tags_gen.go — the vanilla block and item tags
the engine asks about, flattened to entry names.

A hand-kept list of "every wooden button" is right until the next wood set;
the tag is right forever. Each tag here is resolved transitively (nested
#tags expanded) from the canonical version's datapack (scripts/canon.py) and
emitted in the datapack's order. Only the tags the engine names are emitted —
add one to TAGS below before calling worldgen.BlockTag/ItemTag with it (an
unknown name panics, so a test catches the omission).

These are the ENGINE's tags, at the canonical version. The tags a client is
sent are a different table (tachyne-common, per client version).

    python3 scripts/gen_tags.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "tags_gen.go")

TAGS = {
    "block": ["buttons", "fences", "leaves", "pressure_plates", "prevents_nearby_leaf_decay", "wooden_shelves",
              # Tool rules (Player.getDestroySpeed via the tool component)
              "mineable/axe", "mineable/hoe", "mineable/pickaxe", "mineable/shovel",
              "sword_efficient", "sword_instantly_mines", "shears_extreme_breaking_speed",
              "shears_major_breaking_speed", "shears_minor_breaking_speed"],
    "item": ["boats", "clonable_maps", "wooden_tool_materials"],
}

z = canon.inner_jar()


def resolve(kind, name, seen=()):
    if name in seen:
        raise SystemExit(f"tag cycle: {kind}/{name}")
    j = json.loads(z.read(f"data/minecraft/tags/{kind}/{name}.json"))
    out = []
    for v in j["values"]:
        if isinstance(v, dict):
            if v.get("required", True) is False:
                raise SystemExit(f"{kind}/{name}: optional entry {v} (not handled)")
            v = v["id"]
        if v.startswith("#"):
            out += resolve(kind, v[1:].removeprefix("minecraft:"), seen + (name,))
        else:
            out.append(v.removeprefix("minecraft:"))
    return list(dict.fromkeys(out))


L = ["// Code generated by scripts/gen_tags.py from the vanilla datapack. DO NOT EDIT.",
     "",
     "package worldgen",
     ""]
for kind, goname in (("block", "blockTags"), ("item", "itemTags")):
    L += [f"// {goname} are vanilla {kind} tags (canonical {canon.VERSION}), flattened.",
          f"var {goname} = map[string][]string{{"]
    for name in sorted(TAGS[kind]):
        L.append('\t"%s": {%s},' % (name, ", ".join('"%s"' % n for n in resolve(kind, name))))
    L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {os.path.normpath(OUT)}: {sum(len(v) for v in TAGS.values())} tags")
