#!/usr/bin/env python3
"""Generate internal/worldgen/lightfilter_gen.go from minecraft-data blocks.json.

Each block's `filterLight` (0 = fully transparent, 15 = fully opaque, 1 = leaves/
water) is how much sky/block light it dims. The hand-written SkyOpacity only knew
a handful of blocks and treated everything else as opaque — so glass, doors, fences,
slabs, stairs, beds, etc. wrongly blocked light (dark doorways). This emits a
state-range → filter table so SkyOpacity is correct for every block.

Run outside the sandbox (needs network):  python3 scripts/gen_lightfilter.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "lightfilter_gen.go")

blocks = json.load(urllib.request.urlopen(URL))
# Only emit non-opaque ranges; LightFilter defaults to 15 (opaque) for the rest,
# which keeps the table small (most blocks are solid).
rows = []
for b in blocks:
    f = b.get("filterLight", 15)
    if f != 15:
        rows.append((b["minStateId"], b["maxStateId"], f))
rows.sort()

lines = [
    "// Code generated by scripts/gen_lightfilter.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// lightFilterRanges lists block-state ranges whose light filtering is NOT the",
    "// opaque default (15): 0 = transparent (glass/doors/fences/slabs/stairs/beds/…),",
    "// 1 = translucent (leaves/water/ice). Sorted by Min for binary search.",
    "var lightFilterRanges = []struct {",
    "\tMin, Max uint32",
    "\tFilter   int",
    "}{",
]
for mn, mx, f in rows:
    lines.append(f"\t{{{mn}, {mx}, {f}}},")
lines += [
    "}",
    "",
    "// LightFilter returns how much a block dims light (0 transparent … 15 opaque).",
    "func LightFilter(state uint32) int {",
    "\tlo, hi := 0, len(lightFilterRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := lightFilterRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.Filter",
    "\t\t}",
    "\t}",
    "\treturn Opaque // not listed → solid",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} non-opaque ranges")
