#!/usr/bin/env python3
"""Generate tachyne-common/protocol/particles_gen.go — the canonical-770
particle id remapped to every protocol step tachyne's translation chain walks.

The engine emits particles by canonical (1.21.5 / proto 770) id and the chain
renumbers them per client. That table used to be a hand-written switch with one
case per particle somebody had remembered to add; four the engine emits were
missing outright, so squid ink and a furnace minecart's smoke came out as
whatever particle happened to hold that id on the client. Generating the whole
registry removes the class.

Reads the vanilla registry reports (particle_type) for each version.
Run: python3 scripts/gen_particleremap.py
"""
import json, os

HERE = os.path.dirname(__file__)
REPORTS = os.path.expanduser("~/vanilla/reports")
OUT = os.path.join(HERE, "..", "..", "tachyne-common", "protocol", "particles_gen.go")

# The chain's steps, by the report that describes each: 770-772 share the
# 1.21.5 numbering, so the first step that moves anything is 773.
STEPS = [("1.21.5", 770), ("1.21.9", 773), ("26.1", 775), ("26.2", 776), ("26.3", 777)]


def ids(version):
    path = os.path.join(REPORTS, version, "registries.json")
    with open(path) as f:
        reg = json.load(f)["minecraft:particle_type"]["entries"]
    return {name: info["protocol_id"] for name, info in reg.items()}


tables = {proto: ids(v) for v, proto in STEPS}
canon = tables[770]
by_id = {i: n for n, i in canon.items()}
n = max(by_id) + 1

L = ["// Code generated by tachyne-world/scripts/gen_particleremap.py; DO NOT EDIT.",
     "", "package protocol", "",
     "// Particle ids move as versions insert new particles ahead of old ones.",
     "// Each table maps a CANONICAL (770) particle id to its id on that",
     "// protocol step; a particle that no longer exists keeps its canonical id,",
     "// which renders something wrong rather than dropping the packet.",
     f"// {n} canonical particles.", ""]

missing = []
for proto in (773, 775, 776, 777):
    t = tables[proto]
    row = []
    for i in range(n):
        name = by_id.get(i)
        if name is None or name not in t:
            if name is not None:
                missing.append((proto, name))
            row.append(i)
        else:
            row.append(t[name])
    L.append(f"var particleTo{proto} = [{n}]int32{{" + ", ".join(str(v) for v in row) + "}")
    L.append("")

with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"wrote {OUT}: {n} particles × 4 steps"
      + (f"; {len(missing)} gone in later versions: {missing[:5]}" if missing else ""))
