#!/usr/bin/env python3
"""Generate internal/worldgen/fullcube_gen.go from minecraft-data.

For every block STATE, whether its collision shape is exactly the full unit
cube. This is vanilla's BlockBehaviour default for isRedstoneConductor
(BlockStateBase::isCollisionShapeFullBlock): the rule that decides whether a
block carries strong redstone power from a source on one side to consumers
on the others. It is a per-state property — a double slab is a full cube,
a single slab is not; an extended piston base is not, a retracted one is.

Sources (facts only):
  blocks.json               state id ranges per block
  blockCollisionShapes.json shape index per state, shape 1 == [[0,0,0,1,1,1]]

Run outside the sandbox (needs network):  python3 scripts/gen_fullcube.py
Set MCDATA_CACHE=<dir> to read the two files from a local directory instead.
"""
import json, os, urllib.request

VER = "1.21.11"
BASE = f"https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/{VER}/"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "fullcube_gen.go")

def load(name):
    cache = os.environ.get("MCDATA_CACHE")
    if cache:
        with open(os.path.join(cache, name)) as f:
            return json.load(f)
    with urllib.request.urlopen(BASE + name, timeout=60) as r:
        return json.load(r)

blocks = load("blocks.json")
shapes = load("blockCollisionShapes.json")
full_ids = {int(i) for i, sh in shapes["shapes"].items() if sh == [[0, 0, 0, 1, 1, 1]]}
per_block = shapes["blocks"]

full_states = []  # (min,max) runs of state ids that are full cubes
for b in blocks:
    name, lo, hi = b["name"], b["minStateId"], b["maxStateId"]
    v = per_block.get(name)
    if v is None:
        continue
    n = hi - lo + 1
    if isinstance(v, int):
        flags = [v in full_ids] * n
    else:
        if len(v) != n:
            raise SystemExit(f"{name}: {len(v)} shapes for {n} states")
        flags = [x in full_ids for x in v]
    run = None
    for i, f in enumerate(flags):
        sid = lo + i
        if f:
            if run and run[1] == sid - 1:
                run[1] = sid
            else:
                if run:
                    full_states.append(tuple(run))
                run = [sid, sid]
    if run:
        full_states.append(tuple(run))
full_states.sort()

lines = [
    "// Code generated by scripts/gen_fullcube.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// fullCubeRanges lists, as sorted inclusive state-id runs, every block state",
    f"// whose collision shape is exactly the unit cube (minecraft-data {VER}",
    "// blockCollisionShapes). This is vanilla's default isRedstoneConductor rule.",
    "var fullCubeRanges = []struct{ Min, Max uint32 }{",
]
for lo, hi in full_states:
    lines.append(f"\t{{{lo}, {hi}}},")
lines += [
    "}",
    "",
    "// IsFullCube reports whether a state's collision shape is the whole block —",
    "// per STATE: a double slab is, a single slab is not; a retracted piston base",
    "// is, an extended one is not.",
    "func IsFullCube(state uint32) bool {",
    "\tlo, hi := 0, len(fullCubeRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := fullCubeRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn true",
    "\t\t}",
    "\t}",
    "\treturn false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(full_states)} runs")
