#!/usr/bin/env python3
"""Generate internal/server/collisionbounds_gen.go: each block state's
collision shape bounds on the vertical axis (VoxelShape.bounds().minY/maxY),
for the entities that land on blocks by their real height — a falling block
coming to rest half a block up on a slab, a block and a half up on a fence.

Reads the runtime extract (scripts/extract, field collisionBounds): per state,
[] for an empty collision shape, otherwise the bounding box
[minX, minY, minZ, maxX, maxY, maxZ] under an empty collision context.
The full cube [0,1] is the default and not listed; consecutive states sharing
their bounds are stored as one run.

Stdlib only.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import canon  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "collisionbounds_gen.go")


def main():
    ext = json.load(open(canon.extract()))
    per_state = {}
    top = 0
    for b in ext["blocks"]:
        lo = b["minStateId"]
        for i, bb in enumerate(b["collisionBounds"]):
            sid = lo + i
            top = max(top, sid)
            if not bb:
                per_state[sid] = None  # empty
                continue
            y0, y1 = round(bb[1], 6), round(bb[4], 6)
            if (y0, y1) != (0.0, 1.0):
                per_state[sid] = (y0, y1)
    runs = []
    for sid in sorted(per_state):
        v = per_state[sid]
        if runs and runs[-1][1] == sid - 1 and runs[-1][2] == v:
            runs[-1][1] = sid
        else:
            runs.append([sid, sid, v])

    def f(x):
        s = repr(float(x))
        return s

    lines = [
        "// Code generated by scripts/gen_collisionbounds.py; DO NOT EDIT.",
        "",
        "package server",
        "",
        "// collisionRuns lists every block state whose collision shape is not the",
        "// full cube: empty (no collision at all) or bounded vertically by [minY,",
        "// maxY] within its cell (maxY may pass 1: fences and walls stand 1.5).",
        "// States not listed collide as a full block.",
        "var collisionRuns = [...]collisionRun{",
    ]
    for lo, hi, v in runs:
        if v is None:
            lines.append(f"\t{{{lo}, {hi}, true, 0, 0}},")
        else:
            lines.append(f"\t{{{lo}, {hi}, false, {f(v[0])}, {f(v[1])}}},")
    lines += ["}", "", f"// collisionStateCount is the size of the state registry the table covers.",
              f"const collisionStateCount = {top + 1}", ""]
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT}: {len(runs)} runs over {top + 1} states")


if __name__ == "__main__":
    main()
