#!/usr/bin/env python3
"""Generate internal/server/strippables_gen.go — the blocks an axe strips,
paired with what they strip to.

Since 26.x the axe's block changes are data: the `minecraft:axe`
block_transformer, a rule list of "this block -> that block, copying its
properties". Stripping is the subset whose result is a stripped_ block; the
rest (scraping and unwaxing copper) the engine derives from its copper
tables. The pairs are read in the datapack's order.

    python3 scripts/gen_strippables.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "strippables_gen.go")

z = canon.inner_jar()
pairs = []
for entry in json.loads(z.read("data/minecraft/block_transformer/axe.json")):
    provider = entry["block_state_provider"]
    if provider["type"] != "minecraft:rule_based":
        raise SystemExit(f"axe transformer: unhandled provider {provider['type']}")
    for rule in provider["rules"]:
        cond, then = rule["if_true"], rule["then"]
        if then.get("type") != "minecraft:copy_properties":
            continue
        dst = then["source"]["id"].removeprefix("minecraft:")
        if not dst.startswith("stripped_"):
            continue
        if cond.get("type") != "minecraft:matching_blocks" or not isinstance(cond["blocks"], str):
            raise SystemExit(f"axe transformer: unhandled strip condition {cond}")
        pairs.append((cond["blocks"].removeprefix("minecraft:"), dst))
if not pairs:
    raise SystemExit("axe transformer: no strip rules found")

L = ["// Code generated by scripts/gen_strippables.py from the vanilla datapack. DO NOT EDIT.",
     "",
     "package server",
     "",
     f"// stripPairs are the axe's strip rules (canonical {canon.VERSION}): block, stripped block.",
     "var stripPairs = [][2]string{"]
L += ['\t{"%s", "%s"},' % p for p in pairs]
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {os.path.normpath(OUT)}: {len(pairs)} strip pairs")
