#!/usr/bin/env python3
"""Generate internal/worldgen/blockids_gen.go — the block name → state-id maps.

So the engine can name blocks instead of hard-coding numeric state ids (which
churn every version). Emits:
  blockDefaultState[name] -> the block's default state id
  blockStateBase[name]    -> its minStateId (base of the state range)
Both from minecraft-data's canonical-version blocks.json. Run outside the
sandbox (needs network):  python3 scripts/gen_blockids.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "blockids_gen.go")

blocks = json.load(urllib.request.urlopen(URL))
rows = []
for b in blocks:
    name = b["name"]
    default = b.get("defaultState", b["minStateId"])
    rows.append((name, default, b["minStateId"], b["maxStateId"]))
rows.sort()

with open(OUT, "w") as f:
    f.write("// Code generated by scripts/gen_blockids.py from minecraft-data. DO NOT EDIT.\n")
    f.write("// Block name → state id, so worldgen/server can name blocks instead of\n")
    f.write("// hard-coding numeric ids that shift every Minecraft version.\n\n")
    f.write("package worldgen\n\n")
    f.write("// blockDefaultState maps a block name (no namespace) to its DEFAULT state id.\n")
    f.write("var blockDefaultState = map[string]uint32{\n")
    for name, default, _, _ in rows:
        f.write(f'\t{json.dumps(name)}: {default},\n')
    f.write("}\n\n")
    f.write("// blockStateBase maps a block name to its minStateId (the base of its state\n")
    f.write("// range); use with SetProperty/offsets to reach a specific state.\n")
    f.write("var blockStateBase = map[string]uint32{\n")
    for name, _, base, _ in rows:
        f.write(f'\t{json.dumps(name)}: {base},\n')
    f.write("}\n\n")
    f.write("// blockStateMax maps a block name to its maxStateId (top of its state range).\n")
    f.write("var blockStateMax = map[string]uint32{\n")
    for name, _, _, mx in rows:
        f.write(f'\t{json.dumps(name)}: {mx},\n')
    f.write("}\n\n")
    f.write('''// blockID returns a block's default state id by name, panicking on an unknown
// name so a typo fails loudly at startup rather than silently placing air.
func blockID(name string) uint32 {
	s, ok := blockDefaultState[name]
	if !ok {
		panic("worldgen: unknown block name " + name)
	}
	return s
}

// blockBase returns a block's minStateId by name (panics if unknown).
func blockBase(name string) uint32 {
	s, ok := blockStateBase[name]
	if !ok {
		panic("worldgen: unknown block name " + name)
	}
	return s
}
''')
print(f"wrote {OUT} with {len(rows)} blocks")
