#!/usr/bin/env python3
"""Generate internal/worldgen/block_states_gen.go from minecraft-data blocks.json.

For every block with a placement-orientation property (axis / facing / half /
type) OR a connection property (north / east / south / west — fences, glass panes,
iron bars, walls), emit its state layout keyed by default-state ID: the block's
minStateId and its ordered property list (name + value order). That's enough to
recompute an oriented/connected state from the default via mixed-radix arithmetic
(see SetProperty).

Run outside the sandbox (needs network):  python3 scripts/gen_block_states.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "block_states_gen.go")
ORIENT = {"axis", "facing", "half", "type", "rotation"}  # rotation: signs/banners/heads (16-way)
CONNECT = {"north", "east", "south", "west"}  # fences/panes/bars/walls connections

blocks = json.load(urllib.request.urlopen(URL))
rows = []
for b in blocks:
    states = b.get("states", [])
    if not any(s["name"] in ORIENT or s["name"] in CONNECT for s in states):
        continue
    props = []
    for s in states:
        if s["type"] == "bool":
            vals = ["true", "false"]  # Minecraft bool order: true=0, false=1
        else:
            vals = s["values"]
        props.append((s["name"], vals))
    rows.append((b["defaultState"], b["minStateId"], props))
rows.sort()

def govals(vals):
    return "{" + ", ".join(f'"{v}"' for v in vals) + "}"

lines = [
    "// Code generated by scripts/gen_block_states.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// BlockProp is one block-state property: its name and the order of its values",
    "// (the value's index is its contribution to the state ID).",
    "type BlockProp struct {",
    "\tName string",
    "\tVals []string",
    "}",
    "",
    "// BlockInfo is an orientable block's state layout: the first state ID and the",
    "// ordered properties (first = most significant in the mixed-radix state ID).",
    "type BlockInfo struct {",
    "\tMin   uint32",
    "\tProps []BlockProp",
    "}",
    "",
    "// orientInfo maps a block's default state to its layout, for the blocks that",
    "// have a placement-orientation property (axis/facing/half/type) or a",
    "// connection property (north/east/south/west — fences/panes/bars/walls).",
    "var orientInfo = map[uint32]BlockInfo{",
]
for default, mn, props in rows:
    ps = ", ".join(f'{{"{n}", []string{govals(v)}}}' for n, v in props)
    lines.append(f"\t{default}: {{{mn}, []BlockProp{{{ps}}}}},")
lines += [
    "}",
    "",
    "// OrientInfo returns the state layout for an orientable block's default state.",
    "func OrientInfo(defaultState uint32) (BlockInfo, bool) {",
    "\tinfo, ok := orientInfo[defaultState]",
    "\treturn info, ok",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} orientable blocks")
