#!/usr/bin/env python3
"""Generate internal/server/compostables_gen.go — the chance each item adds a
layer to a composter.

Since 26.x an item is compostable by its `minecraft:compostable` component
(the items' component reports): `layers`, a context provider resolved against
the composter. Every vanilla provider is one shape — an empty composter
always takes a layer, otherwise a weighted roll of 1 or 0 layers — or a flat
1, so it reduces to one chance per item, which is what the engine applies.
Any other shape stops the generator rather than being guessed at.

    python3 scripts/gen_compostables.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon
import vanillareport

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "compostables_gen.go")
COMPONENTS = canon.report("reports/minecraft/components/item")
z = canon.inner_jar()


def chance(p, where):
    if isinstance(p, str):
        ns, _, path = p.partition(":")
        return chance(json.loads(z.read(f"data/{ns}/context_int_provider/{path}.json")), p)
    if p == 1:
        return 1.0
    ok = (isinstance(p, dict) and p.get("type") == "minecraft:number_dispatcher"
          and p["cases"] == [{"condition": {"type": "minecraft:match_block", "blocks": "minecraft:composter",
                                            "state": {"level": "0"}}, "value": 1}]
          and p["default"].get("type") == "minecraft:weighted_list")
    if not ok:
        raise SystemExit(f"{where}: unhandled compostable provider {p}")
    dist = p["default"]["distribution"]
    if sorted(d["data"] for d in dist) != [0, 1]:
        raise SystemExit(f"{where}: layers other than 0/1 in {dist}")
    return sum(d["weight"] for d in dist if d["data"] == 1) / sum(d["weight"] for d in dist)


rows = []
for i in vanillareport.registry(canon.VERSION, "item"):
    name = i["name"]
    comp = json.load(open(os.path.join(COMPONENTS, name + ".json")))["components"].get("minecraft:compostable")
    if comp is not None:
        rows.append((name, chance(comp["layers"], name)))

L = ["// Code generated by scripts/gen_compostables.py from vanilla item data. DO NOT EDIT.",
     "",
     "package server",
     "",
     f"// compostChances is each compostable item's chance to add a layer (canonical {canon.VERSION}).",
     "var compostChances = map[string]float64{"]
L += ['\t"%s": %g,' % r for r in rows]
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {os.path.normpath(OUT)}: {len(rows)} compostables")
