#!/usr/bin/env python3
"""Generate internal/server/loot_gen.go from minecraft-data blocks.json.

Each block's `drops` field gives the item id(s) it yields when broken. We emit a
state-range → item table (sorted by min state for binary search) covering the
default "drops itself / drops its item" case for every block. Probabilistic and
special drops (seeds, flint, leaves) are hand-written in loot.go and OVERRIDE this.

Run outside the sandbox (needs network):  python3 scripts/gen_loot.py
"""
import json, urllib.request, os

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/blocks.json"
ITEMS = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "loot_gen.go")

blocks = json.load(urllib.request.urlopen(URL))
item_id = {i["name"]: i["id"] for i in json.load(urllib.request.urlopen(ITEMS))}
rows = []
for b in blocks:
    drops = b.get("drops", [])
    if not drops:
        # minecraft-data lists no drop for beds, but a bed breaks by hand and
        # gives its bed item — patch that specific data gap from the item table.
        # (Other empty-drops blocks — glass, ice, spawner, … — correctly drop
        # nothing without silk touch, so we do NOT blanket-fallback.)
        if b["name"].endswith("_bed") and b["name"] in item_id:
            rows.append((b["minStateId"], b["maxStateId"], item_id[b["name"]]))
        continue
    d = drops[0]
    item = d if isinstance(d, int) else d.get("item", d.get("drop"))
    if not isinstance(item, int):
        continue
    rows.append((b["minStateId"], b["maxStateId"], item))
rows.sort()

lines = [
    "// Code generated by scripts/gen_loot.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// blockDropRanges maps a broken block-state range to the item it drops (the",
    "// minecraft-data default drop). Sorted by Min for binary search via",
    "// generatedDrop. Probabilistic/special drops live in loot.go and override this.",
    "var blockDropRanges = []struct {",
    "\tMin, Max uint32",
    "\tItem     int32",
    "}{",
]
for mn, mx, item in rows:
    lines.append(f"\t{{{mn}, {mx}, {item}}},")
lines += [
    "}",
    "",
    "// generatedDrop returns the default item a block-state drops, if any.",
    "func generatedDrop(state uint32) (int32, bool) {",
    "\tlo, hi := 0, len(blockDropRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := blockDropRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.Item, true",
    "\t\t}",
    "\t}",
    "\treturn 0, false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT} with {len(rows)} block drop ranges")
