#!/usr/bin/env python3
"""Generate internal/server/smelting_gen.go: furnace recipes + fuel burn times.

Smelting recipes come from the mcmeta 1.21.5 datapack (recipe/*.json with
type minecraft:smelting). Ingredients may be item names or #tags; tags resolve
transitively via the datapack's tags/item/*.json. Names map to network ids via
minecraft-data items.json. Result counts are always 1 for smelting; per-recipe
cook time is kept (default 200 ticks).

Fuel burn times are vanilla constants (AbstractFurnaceBlockEntity); the common
set is emitted by name so the ids stay generated.

Run outside the sandbox (needs network):  python3 scripts/gen_smelting.py
"""
import io, json, tarfile, urllib.request, os, subprocess

ITEMS = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
TARBALL = "https://github.com/misode/mcmeta/archive/refs/tags/1.21.5-data-json.tar.gz"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "smelting_gen.go")

item_id = {i["name"]: i["id"] for i in json.load(urllib.request.urlopen(ITEMS))}

# One tarball download instead of ~1000 raw fetches.
print("downloading mcmeta datapack…")
tar = tarfile.open(fileobj=io.BytesIO(urllib.request.urlopen(TARBALL, timeout=120).read()), mode="r:gz")
recipes, tags = {}, {}
for member in tar.getmembers():
    parts = member.name.split("/", 1)
    if len(parts) < 2:
        continue
    path = parts[1]
    if path.startswith("data/minecraft/recipe/") and path.endswith(".json"):
        recipes[path] = json.load(tar.extractfile(member))
    elif path.startswith("data/minecraft/tags/item/") and path.endswith(".json"):
        key = path.removeprefix("data/minecraft/tags/item/").removesuffix(".json")
        tags[key] = json.load(tar.extractfile(member))

tag_cache = {}


def resolve_tag(name, depth=0):
    """#minecraft:logs_that_burn -> flat list of item names."""
    if depth > 8:
        return []
    key = name.lstrip("#").removeprefix("minecraft:")
    if key in tag_cache:
        return tag_cache[key]
    if key not in tags:
        return []
    out = []
    for v in tags[key]["values"]:
        v = v["id"] if isinstance(v, dict) else v
        if v.startswith("#"):
            out += resolve_tag(v, depth + 1)
        else:
            out.append(v.removeprefix("minecraft:"))
    tag_cache[key] = out
    return out


rows = []  # (input id, result id, cook ticks)
for path, r in sorted(recipes.items()):
    if r.get("type") != "minecraft:smelting":
        continue
    result = r["result"]["id"].removeprefix("minecraft:")
    if result not in item_id:
        continue
    cook = r.get("cookingtime", 200)
    ing = r["ingredient"]
    ings = [ing] if isinstance(ing, str) else ing
    names = []
    for i in ings:
        if i.startswith("#"):
            names += resolve_tag(i)
        else:
            names.append(i.removeprefix("minecraft:"))
    for n in names:
        if n in item_id:
            rows.append((item_id[n], item_id[result], cook))
rows.sort()

# Vanilla fuel burn times (ticks), by item name family.
FUELS = {"coal": 1600, "charcoal": 1600, "coal_block": 16000, "blaze_rod": 2400,
         "lava_bucket": 20000, "stick": 100, "crafting_table": 300, "bamboo": 50,
         "dried_kelp_block": 4000}
fuel_rows = []
for name, iid in item_id.items():
    if name in FUELS:
        fuel_rows.append((iid, FUELS[name]))
    elif name.endswith("_planks") or name.endswith("_log") or name.endswith("_wood") or name.endswith("_sapling"):
        fuel_rows.append((iid, 300 if not name.endswith("_sapling") else 100))
fuel_rows.sort()

L = [
    "// Code generated by scripts/gen_smelting.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// smeltResult maps a furnace input item to its smelted output + cook ticks.",
    "var smeltResult = map[int32]struct {",
    "\tOut  int32",
    "\tCook int",
    "}{",
]
for inp, out, cook in rows:
    L.append(f"\t{inp}: {{{out}, {cook}}},")
L += [
    "}",
    "",
    "// fuelTicks maps a fuel item to how long one of it burns (ticks).",
    "var fuelTicks = map[int32]int{",
]
for iid, t in fuel_rows:
    L.append(f"\t{iid}: {t},")
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(rows)} smelting inputs, {len(fuel_rows)} fuels")
