#!/usr/bin/env python3
"""Generate internal/server/dyecolors_gen.go — each dye's FIREWORK colour.

A firework star takes its colours from the dyes it was crafted with, and the
value used is DyeColor's own fireworkColor, which is NOT the dye's text or map
colour. Reading it from the enum keeps the table honest.

Run: python3 scripts/gen_dyecolors.py [path-to-DyeColor.java]
"""
import canon
import os, re, sys

SRC = sys.argv[1] if len(sys.argv) > 1 else os.path.join(canon.src(canon.DATA), "net/minecraft/world/item/DyeColor.java")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "dyecolors_gen.go")

# NAME(id, "name", textureDiffuse, MapColor.X, [MapColor.TERRACOTTA_X,] fireworkColor, textColor)
# — the constructor stores fireworkColor from the argument BEFORE textColor
# (26.x adds the terracotta map colour after the first). Until 2026-09-23 this
# took the last argument, so every firework star wore the dyes' text colours.
PAT = re.compile(
    r'^\s+[A-Z_]+\((\d+),\s*"([a-z_]+)",\s*(0[xX][0-9a-fA-F]+|\d+),\s*MapColor\.\w+,\s*'
    r'(?:MapColor\.\w+,\s*)?(0[xX][0-9a-fA-F]+|\d+),\s*(?:0[xX][0-9a-fA-F]+|\d+)\)', re.M)

rows = [(int(i), n, int(c, 0) & 0xFFFFFF) for i, n, _, c in PAT.findall(open(SRC).read())]
if len(rows) != 16:
    sys.exit(f"matched {len(rows)} dyes, want 16 — has DyeColor's shape changed?")

L = ["// Code generated by scripts/gen_dyecolors.py; DO NOT EDIT.", "",
     "package server", "",
     "// dyeFireworkColor is the colour a dye contributes to a firework star",
     "// (DyeColor.getFireworkColor) — not the dye's own text or map colour.",
     "// Indexed by the DyeColor id, which is what the wire and the loom use.", "",
     "var dyeFireworkColor = [16]int32{"]
for i, n, c in sorted(rows):
    L.append(f"\t0x{c:06X}, // {i} {n}")
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print(f"wrote {OUT}: {len(rows)} dyes")
