#!/usr/bin/env python3
"""Generate internal/server/mapcolors_gen.go — each block state's base map
colour (MapColor.id, 0-61), the colour a filled map paints it.

The colour is asked of the running game, per state (the extractor,
scripts/extract): BlockState.getMapColor, since some blocks colour their
states differently — a bed's foot is its dye colour and its head is wool.
Runs of consecutive states with the same colour are merged, and states with
none (0) are left out, as the lookup's miss is 0.

    python3 scripts/gen_mapcolors.py     # canonical version: canon.py
"""
import json
import os

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "mapcolors_gen.go")

runs = []  # [base, count, colour]
for b in sorted(json.load(open(canon.extract()))["blocks"], key=lambda b: b["minStateId"]):
    colours = b["mapColor"]
    if len(colours) != b["maxStateId"] - b["minStateId"] + 1:
        raise SystemExit("%s: %d map colours for %d states" % (b["name"], len(colours), b["maxStateId"] - b["minStateId"] + 1))
    for i, c in enumerate(colours):
        s = b["minStateId"] + i
        if runs and runs[-1][2] == c and runs[-1][0] + runs[-1][1] == s:
            runs[-1][1] += 1
        else:
            runs.append([s, 1, c])
runs = [r for r in runs if r[2] != 0]

L = ["// Code generated by scripts/gen_mapcolors.py from vanilla block data. DO NOT EDIT.",
     "",
     "package server",
     "",
     "// mapColorRange maps a contiguous run of block-state ids (canonical",
     "// %s) to a vanilla base map color id (0-61). States not covered" % canon.VERSION,
     "// by any range have no map color (0 = none).",
     "type mapColorRange struct {",
     "\tbase, count uint32",
     "\tcolor       uint8",
     "}",
     "",
     "var mapColorRanges = []mapColorRange{"]
L += ["\t{%d, %d, %d}," % tuple(r) for r in runs]
L += ["}",
      "",
      "func mapColorFor(state uint32) uint8 {",
      "\tlo, hi := 0, len(mapColorRanges)-1",
      "\tfor lo <= hi {",
      "\t\tmid := int(uint(lo+hi) >> 1)",
      "\t\tr := mapColorRanges[mid]",
      "\t\tswitch {",
      "\t\tcase state < r.base:",
      "\t\t\thi = mid - 1",
      "\t\tcase state >= r.base+r.count:",
      "\t\t\tlo = mid + 1",
      "\t\tdefault:",
      "\t\t\treturn r.color",
      "\t\t}",
      "\t}",
      "\treturn 0",
      "}",
      ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print("wrote %s: %d ranges" % (os.path.normpath(OUT), len(runs)))
