#!/usr/bin/env python3
"""Generate internal/worldgen/solid_gen.go.

Vanilla's BlockStateBase.isSolid — the test FarmBlock, DirtPathBlock and
everything else asking "is the block above me a lid" uses.

It is NOT "does it collide". calculateSolid is:

    if forceSolidOn  -> true
    if forceSolidOff -> false
    if no cache      -> false
    if the collision shape is empty -> false
    else the bounds must average 0.7291666 across the three axes,
         or stand a full block tall

The force flags are the trap. This generator used to reimplement the
threshold from minecraft-data collision shapes and carry the two flag sets by
hand, with a comment saying "both lists are tiny". Vanilla has **173**
forceSolidOn registrations; the list had two. That put 2,809 block states on
the wrong answer — closed fence gates, signs, cobwebs and sculk veins among
them.

So it no longer reimplements anything: the local extract (see
audit/phase0/extractor) asks the game `state.isSolid()` directly, force flags
and threshold already applied.

    python3 scripts/gen_solid.py [version]     # default 1.21.11
"""
import json, os, subprocess, sys

VER = sys.argv[1] if len(sys.argv) > 1 else "1.21.11"
SRC = os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "solid_gen.go")

runs = []
for b in json.load(open(SRC))["blocks"]:
    lo = b["minStateId"]
    flags = b["isSolid"]
    if b["maxStateId"] - lo + 1 != len(flags):
        raise SystemExit("%s: state count disagrees with isSolid count" % b["name"])
    run = None
    for i, f in enumerate(flags):
        sid = lo + i
        if f:
            if run and run[1] == sid - 1:
                run[1] = sid
            else:
                if run:
                    runs.append(tuple(run))
                run = [sid, sid]
    if run:
        runs.append(tuple(run))
runs.sort()

lines = [
    "// Code generated by scripts/gen_solid.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// solidRanges lists, as sorted inclusive state-id runs, every block state",
    "// vanilla calls SOLID, taken from the game itself (state.isSolid()).",
    "//",
    "// BlockStateBase.calculateSolid is a THRESHOLD on the collision shape's",
    "// bounds, not a yes/no on whether the block collides at all: the bounds must",
    "// average 0.7291666 of a block across the three axes, or stand a full block",
    "// tall. A slab, a chest, a door and a ladder pass; a carpet, a candle, a",
    "// skull and a pitcher crop do not — which is why a field keeps its tilth",
    "// under a crop and loses it under a chest.",
    "var solidRanges = []struct{ Min, Max uint32 }{",
]
for lo, hi in runs:
    lines.append(f"\t{{{lo}, {hi}}},")
lines += [
    "}",
    "",
    "// IsSolid is BlockStateBase.isSolid.",
    "func IsSolid(state uint32) bool {",
    "\tlo, hi := 0, len(solidRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := solidRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn true",
    "\t\t}",
    "\t}",
    "\treturn false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(runs)} runs")
