#!/usr/bin/env python3
"""Embed the vanilla world generator's data: the canonical version's
worldgen density functions, noises, noise settings, material rules and
conditions, world presets and carvers, as minified JSON keyed by
"<registry>/<path>" (e.g. "density_function/overworld/factor"), for the
vanilla generator (internal/worldgen/vanilladensity.go and friends) to
read at boot.

Reads the canonical version's server jar (canon.VERSION) — no network.
Stdlib only.
"""
import io
import json
import os
import zipfile

import canon

VERSION = canon.VERSION
JAR = os.path.expanduser(f"~/vanilla/server-{VERSION}.jar")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "worldgen", "vanilladata_gen.go")
PREFIX = "data/minecraft/worldgen/"
KINDS = ("density_function", "noise", "noise_settings", "material_rule",
         "material_condition", "world_preset", "carver")


def datapack():
    """The server jar's built-in datapack (nested inside the launcher jar)."""
    outer = zipfile.ZipFile(JAR)
    inner = [n for n in outer.namelist()
             if n.startswith("META-INF/versions/") and n.endswith(".jar")]
    return zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer


def main():
    z = datapack()
    out = {}
    for n in z.namelist():
        if not n.startswith(PREFIX) or not n.endswith(".json"):
            continue
        rel = n[len(PREFIX):-len(".json")]
        if rel.split("/", 1)[0] not in KINDS:
            continue
        text = json.dumps(json.loads(z.read(n)), separators=(",", ":"), sort_keys=True)
        if "`" in text:
            raise SystemExit(f"{n}: a backquote cannot go in a raw string")
        out[rel] = text
    if not out:
        raise SystemExit("no worldgen data found in " + JAR)
    lines = [
        "// Code generated by scripts/gen_vanilla_worldgen.py from the "
        f"{VERSION} server jar's worldgen data; DO NOT EDIT.",
        "",
        "package worldgen",
        "",
        "// vanillaWorldgenData is the canonical version's worldgen JSON (density",
        "// functions, noises, noise settings, material rules and conditions, world",
        "// presets, carvers), minified, keyed by \"<registry>/<path>\".",
        "var vanillaWorldgenData = map[string]string{",
    ]
    for k in sorted(out):
        lines.append(f"\t{json.dumps(k)}: `{out[k]}`,")
    lines.append("}")
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"{OUT}: {len(out)} entries, {sum(len(v) for v in out.values())} bytes")


if __name__ == "__main__":
    main()
