#!/usr/bin/env python3
"""Regenerate internal/protocol/damagetypes_gen.go from misode/mcmeta.

damage_type is one of three registries that MUST carry inline NBT even when the
known pack matches (the others are dimension_type and worldgen/biome). This
script pulls the network fields of every 1.21.5 damage type so registry_data.go
can build their NBT.

Run from the repo root. Needs network, so run OUTSIDE the sandbox:

    python3 scripts/gen_damagetypes.py

Stdlib only.
"""
import concurrent.futures
import json
import os
import urllib.request

SUMMARY = "https://raw.githubusercontent.com/misode/mcmeta/1.21.5-summary/registries/data.min.json"
DATA = "https://raw.githubusercontent.com/misode/mcmeta/1.21.5-data-json/data/minecraft/damage_type/"

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "internal", "protocol", "damagetypes_gen.go")


def fetch_json(url):
    with urllib.request.urlopen(url, timeout=30) as r:
        return json.load(r)


def main():
    summary = fetch_json(SUMMARY)["damage_type"]
    names = [(n.split(":", 1)[1] if ":" in n else n) for n in summary]

    def fetch(n):
        return n, fetch_json(DATA + n + ".json")

    rows = {}
    with concurrent.futures.ThreadPoolExecutor(max_workers=12) as ex:
        for n, d in ex.map(fetch, names):
            rows[n] = d

    q = json.dumps
    out = [
        "// Code generated by scripts/gen_damagetypes.py from misode/mcmeta 1.21.5. DO NOT EDIT.",
        "",
        "package protocol",
        "",
        "// damageType holds the network fields of one minecraft:damage_type entry.",
        "type damageType struct {",
        "\tName             string",
        "\tMessageID        string",
        "\tScaling          string",
        "\tExhaustion       float32",
        "\tEffects          string",
        "\tDeathMessageType string",
        "}",
        "",
        "var damageTypes = []damageType{",
    ]
    for n in names:
        d = rows[n]
        out.append("\t{%s, %s, %s, %g, %s, %s}," % (
            q(n), q(d["message_id"]), q(d["scaling"]), float(d["exhaustion"]),
            q(d.get("effects", "")), q(d.get("death_message_type", ""))))
    out += ["}", ""]

    with open(OUT, "w") as f:
        f.write("\n".join(out))
    print(f"wrote {OUT}: {len(names)} damage types")


if __name__ == "__main__":
    main()
