#!/usr/bin/env python3
"""Regenerate internal/server/itemnames_gen.go — item name → id for /give.
Source: PrismarineJS/minecraft-data 1.21.5 items.json. Stdlib only; needs
network — run OUTSIDE the sandbox:  python3 scripts/gen_itemnames.py
"""
import json
import urllib.request

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
OUT = "internal/server/itemnames_gen.go"

items = json.load(urllib.request.urlopen(URL))
lines = [
    "// Code generated by scripts/gen_itemnames.py. DO NOT EDIT.",
    "",
    "package server",
    "",
    "// itemByName maps minecraft item names (no namespace) to 1.21.5 ids.",
    "var itemByName = map[string]int32{",
]
for e in items:
    lines.append(f'\t"{e["name"]}": {e["id"]},')
lines += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(items)} items")
