#!/usr/bin/env python3
"""Generate internal/server/signs_gen.go from the vanilla block-state report.

Signs come in four block kinds per wood type — standing (rotation 0-15), wall
(facing), ceiling-hanging (attached + rotation) and wall-hanging (facing) —
but only the standing/ceiling blocks have items. Emit:
  - signWallVariant:    standing default state  -> wall-sign default state
  - hangingWallVariant: ceiling default state   -> wall-hanging default state
  - signKindRanges:     state-range classification for every sign block

Reads the local datagen report (no network): ~/vanilla/reports/1.21.11/blocks.json
"""
import json, os

SRC = os.path.expanduser("~/vanilla/reports/1.21.11/blocks.json")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "signs_gen.go")

blocks = json.load(open(SRC))

def info(name):
    b = blocks[name]
    ids = [s["id"] for s in b["states"]]
    default = [s["id"] for s in b["states"] if s.get("default")][0]
    return min(ids), max(ids), default

woods = sorted(n.removesuffix("_sign").removeprefix("minecraft:")
               for n in blocks if n.endswith("_sign")
               and "wall" not in n and "hanging" not in n)

wall_variant, hanging_variant, ranges = [], [], []
for w in woods:
    s_min, s_max, s_def = info(f"minecraft:{w}_sign")
    w_min, w_max, w_def = info(f"minecraft:{w}_wall_sign")
    h_min, h_max, h_def = info(f"minecraft:{w}_hanging_sign")
    x_min, x_max, x_def = info(f"minecraft:{w}_wall_hanging_sign")
    wall_variant.append((s_def, w_def, w))
    hanging_variant.append((h_def, x_def, w))
    ranges += [(s_min, s_max, "signStanding", w), (w_min, w_max, "signWall", w),
               (h_min, h_max, "signHangingCeiling", w), (x_min, x_max, "signHangingWall", w)]
ranges.sort()

lines = [
    "// Code generated by scripts/gen_signs.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// Sign block kinds (state-range classification).",
    "const (",
    "\tsignStanding = iota // rotation 0-15, on the ground",
    "\tsignWall            // facing, on a wall",
    "\tsignHangingCeiling  // attached + rotation, under a block",
    "\tsignHangingWall     // facing, bracket on a wall side",
    ")",
    "",
    "// signWallVariant maps a sign item's standing default state (what",
    "// BlockForItem returns) to the same wood's wall-sign default state.",
    "var signWallVariant = map[uint32]uint32{",
]
for d, w, wood in wall_variant:
    lines.append(f"\t{d}: {w}, // {wood}")
lines += [
    "}",
    "",
    "// hangingWallVariant maps a hanging-sign item's ceiling default state to",
    "// the same wood's wall-hanging default state.",
    "var hangingWallVariant = map[uint32]uint32{",
]
for d, w, wood in hanging_variant:
    lines.append(f"\t{d}: {w}, // {wood}")
lines += [
    "}",
    "",
    "// signKindRanges classifies any sign block state (sorted by Min).",
    "var signKindRanges = []struct {",
    "\tMin, Max uint32",
    "\tKind     int",
    "}{",
]
for mn, mx, kind, wood in ranges:
    lines.append(f"\t{{{mn}, {mx}, {kind}}}, // {wood}")
lines += [
    "}",
    "",
    "// signKind classifies a block state as a sign kind; ok=false if not a sign.",
    "func signKind(state uint32) (int, bool) {",
    "\tfor _, r := range signKindRanges {",
    "\t\tif state >= r.Min && state <= r.Max {",
    "\t\t\treturn r.Kind, true",
    "\t\t}",
    "\t\tif state < r.Min {",
    "\t\t\tbreak",
    "\t\t}",
    "\t}",
    "\treturn 0, false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(wall_variant)} woods, {len(ranges)} ranges")
