#!/usr/bin/env python3
"""Generate internal/worldgen/fullcube_gen.go.

For every block STATE, whether its collision shape is exactly the full unit
cube — vanilla's BlockStateBase.isCollisionShapeFullBlock, the rule that
decides whether a block carries strong redstone power from a source on one
side to consumers on the others. A double slab is a full cube, a single slab
is not; a retracted piston base is, an extended one is not.

Source: the local extract (see scripts/extract), which asks the game
directly. It was minecraft-data's blockCollisionShapes; that produced the
same answers state for state (verified before the switch), so this change is
purely about owning the input for every version rather than the newest one a
third party happens to cover.

    python3 scripts/gen_fullcube.py [version]     # default: scripts/canon.py
"""
import canon
import json, os, sys

VER = sys.argv[1] if len(sys.argv) > 1 else canon.VERSION
SRC = os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "fullcube_gen.go")


full_states = []  # (min,max) runs of state ids that are full cubes
for b in json.load(open(SRC))["blocks"]:
    lo, flags = b["minStateId"], b["isFullCube"]
    if b["maxStateId"] - lo + 1 != len(flags):
        raise SystemExit("%s: state count disagrees with isFullCube count" % b["name"])
    run = None
    for i, f in enumerate(flags):
        sid = lo + i
        if f:
            if run and run[1] == sid - 1:
                run[1] = sid
            else:
                if run:
                    full_states.append(tuple(run))
                run = [sid, sid]
    if run:
        full_states.append(tuple(run))

full_states.sort()

lines = [
    "// Code generated by scripts/gen_fullcube.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// fullCubeRanges lists, as sorted inclusive state-id runs, every block state",
    "// whose collision shape is exactly the unit cube, taken from the game",
    "// itself. This is vanilla's default isRedstoneConductor rule.",
    "var fullCubeRanges = []struct{ Min, Max uint32 }{",
]
for lo, hi in full_states:
    lines.append(f"\t{{{lo}, {hi}}},")
lines += [
    "}",
    "",
    "// IsFullCube reports whether a state's collision shape is the whole block —",
    "// per STATE: a double slab is, a single slab is not; a retracted piston base",
    "// is, an extended one is not.",
    "func IsFullCube(state uint32) bool {",
    "\tlo, hi := 0, len(fullCubeRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := fullCubeRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn true",
    "\t\t}",
    "\t}",
    "\treturn false",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print(f"wrote {OUT}: {len(full_states)} runs")
