#!/usr/bin/env python3
"""Generate internal/worldgen/lightfilter_gen.go.

How much a block state dims light: 0 transparent, 1 translucent, 15 opaque.
Vanilla computes it per STATE — 15 when the state renders solid, else 0 if it
propagates skylight down and 1 if it does not — so one block can span all
three. A double slab is opaque while its halves are not; a waterlogged fence
dims by 1 while a dry one does not.

Source: the local extract (~/vanilla/extract/<ver>.json), taken by running
the game — see audit/phase0/extractor. It was minecraft-data, which records
one filterLight per BLOCK, and that flattening put 10,394 of the 29,671
states on the wrong value, including 125 where light passed straight through
a solid block.

    python3 scripts/gen_lightfilter.py [version]     # default 1.21.11
"""
import json, os, sys

VER = sys.argv[1] if len(sys.argv) > 1 else "1.21.11"
SRC = os.path.expanduser("~/vanilla/extract/%s.json" % VER)
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "worldgen", "lightfilter_gen.go")

blocks = json.load(open(SRC))["blocks"]
# Only emit non-opaque ranges; LightFilter defaults to 15 (opaque) for the rest,
# which keeps the table small (most blocks are solid).
rows = []
for b in blocks:
    lo = b["minStateId"]
    vals = b["filterLight"]
    if b["maxStateId"] - lo + 1 != len(vals):
        raise SystemExit("%s: state count disagrees with filter count" % b["name"])
    start = 0
    for i in range(1, len(vals) + 1):
        if i == len(vals) or vals[i] != vals[start]:
            if vals[start] != 15:          # 15 is the table's default
                rows.append((lo + start, lo + i - 1, vals[start], b["name"]))
            start = i
rows.sort()

# Merge runs that are contiguous in state id AND share a filter value, even
# across block boundaries — the table is searched by state, not by block, so
# the split is meaningless to the lookup and costs 14k rows to keep. The
# comment then names the first block of the run.
merged = []
for lo, hi, f, name in rows:
    if merged and merged[-1][1] + 1 == lo and merged[-1][2] == f:
        merged[-1][1] = hi
        merged[-1][4] += 1
    else:
        merged.append([lo, hi, f, name, 1])
rows = [(lo, hi, f, name if n == 1 else "%s +%d more" % (name, n - 1))
        for lo, hi, f, name, n in merged]

lines = [
    "// Code generated by scripts/gen_lightfilter.py; DO NOT EDIT.",
    "",
    "package worldgen",
    "",
    "// lightFilterRanges lists block-state ranges whose light filtering is NOT the",
    "// opaque default (15): 0 = transparent (glass/doors/fences/slabs/stairs/beds/…),",
    "// 1 = translucent (leaves/water/ice, and anything that does not propagate",
    "// skylight — a waterlogged fence or stair). Sorted by Min for binary search.",
    "//",
    "// Per STATE, not per block: a double slab is opaque while its halves are not.",
    "var lightFilterRanges = []struct {",
    "\tMin, Max uint32",
    "\tFilter   int",
    "}{",
]
w = max(len("{%d, %d, %d}," % (a, b, c)) for a, b, c, _ in rows)
for mn, mx, f, name in rows:
    lines.append("\t%-*s // %s" % (w + 1, "{%d, %d, %d}," % (mn, mx, f), name))
lines += [
    "}",
    "",
    "// LightFilter returns how much a block dims light (0 transparent … 15 opaque).",
    "func LightFilter(state uint32) int {",
    "\tlo, hi := 0, len(lightFilterRanges)-1",
    "\tfor lo <= hi {",
    "\t\tmid := (lo + hi) / 2",
    "\t\tr := lightFilterRanges[mid]",
    "\t\tswitch {",
    "\t\tcase state < r.Min:",
    "\t\t\thi = mid - 1",
    "\t\tcase state > r.Max:",
    "\t\t\tlo = mid + 1",
    "\t\tdefault:",
    "\t\t\treturn r.Filter",
    "\t\t}",
    "\t}",
    "\treturn Opaque // not listed → solid",
    "}",
    "",
]
with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("%s: %d non-opaque ranges -> %s" % (VER, len(rows), os.path.normpath(OUT)))
