#!/usr/bin/env python3
"""Generate internal/server/particlenames_gen.go: the particle types /particle
accepts by name, with their CANONICAL (1.21.5, proto 770) ids — the id space
the engine emits and the gateway chain remaps per client
(tachyne-common protocol/particles_gen.go).

Only particles that carry no options are listed: the engine's particle frame
has no field for a colour, a block or an item.

    python3 scripts/gen_particlenames.py
"""
import json
import os

REPORT = os.path.expanduser("~/vanilla/reports/1.21.5/registries.json")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "particlenames_gen.go")

# ParticleTypes whose type carries options in 1.21.5.
WITH_OPTIONS = {"block", "block_marker", "dust", "dust_color_transition", "entity_effect", "falling_dust",
                "item", "vibration", "sculk_charge", "shriek", "dust_pillar", "block_crumble", "trail",
                "tinted_leaves"}

entries = json.load(open(REPORT))["minecraft:particle_type"]["entries"]
L = ["// Code generated by scripts/gen_particlenames.py from the 1.21.5 registry report. DO NOT EDIT.",
     "", "package server", "",
     "// particleByName is the option-free particle types by name, canonical ids.",
     "var particleByName = map[string]int32{"]
for name, e in sorted(entries.items(), key=lambda kv: kv[1]["protocol_id"]):
    short = name.removeprefix("minecraft:")
    if short in WITH_OPTIONS:
        continue
    L.append('\t"%s": %d,' % (short, e["protocol_id"]))
L += ["}", ""]
open(OUT, "w").write("\n".join(L))
import subprocess
subprocess.run(["gofmt", "-w", OUT], check=False)
print("wrote", OUT, len(L) - 7, "particles")
