#!/usr/bin/env python3
"""Regenerates internal/server/stepsounds_gen.go from vanilla's block sound
types, as the running game reports them (the extractor, scripts/extract).

Two facts per version:

  * every SoundType constant: its volume, pitch and sound events (we keep
    step and place);
  * every block's sound type — its default state's, named by the constant.

This used to be read out of the server's source, which could only see a
block that named its sound in its own registration line: the 383 blocks
that copy another block's properties, are built by a helper (slabs, stairs,
walls) or come from a colour set all fell through to stone, so wooden
stairs, copper, wool, glass and candles all walked and placed like stone.

Usage: gen_blocksounds.py [<extract json>]     # default: scripts/canon.py
"""
import canon
import json
import sys
import os

SRC = sys.argv[1] if len(sys.argv) > 1 else canon.extract()
ext = json.load(open(SRC))

# SoundType: constant -> (volume, pitch, step event, place event).
types = {t["name"]: (t["volume"], t["pitch"], t["step"], t["place"]) for t in ext["soundTypes"]}

# Blocks: name -> sound type; a block absent from the table is stone.
blocks = {b["name"]: b["sound"] for b in ext["blocks"] if b["sound"] != "STONE"}
missing = sorted({t for t in blocks.values() if t not in types})
if missing:
    raise SystemExit("blocks name sound types the extract does not list: %s" % missing)


def num(v):
    return ("%g" % v)


out = ["// Code generated by scripts/gen_blocksounds.py from vanilla's block sound types. DO NOT EDIT.",
       "", "package server", "",
       "// blockSoundType names every block's sound type; a block absent here is stone.",
       "var blockSoundType = map[string]string{"]
w = max(len(n) for n in blocks) + 3
for name in sorted(blocks):
    out.append('\t%-*s "%s",' % (w, '"%s":' % name, blocks[name]))
out += ["}", "",
        "// soundTypeSteps is each sound type's volume, pitch and step sound event.",
        "var soundTypeSteps = map[string]stepSound{"]
w = max(len(t) for t in types) + 3
for t in sorted(types):
    vol, pitch, step, _ = types[t]
    out.append('\t%-*s {%s, %s, "minecraft:%s"},' % (w, '"%s":' % t, num(vol), num(pitch), step))
out += ["}", "",
        "// soundTypePlaces is each sound type's place sound event. Its volume and",
        "// pitch are the same pair soundTypeSteps carries — BlockItem.place scales",
        "// them, it does not keep its own.",
        "var soundTypePlaces = map[string]string{"]
for t in sorted(types):
    out.append('\t%-*s "minecraft:%s",' % (w, '"%s":' % t, types[t][3]))
out += ["}", ""]

dest = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "internal/server/stepsounds_gen.go")
open(dest, "w").write("\n".join(out))
print("%d blocks, %d sound types -> %s" % (len(blocks), len(types), os.path.normpath(dest)))
