#!/usr/bin/env python3
"""Generate ../tachyne-common/protocol/smithing_gen.go.

Smithing data from the vanilla 1.21.11 jar: the 12 transform recipes
(diamond -> netherite, base components carried), the 18 trim templates
(template item -> trim_pattern id in OUR declared alphabetical registry
order), the trim materials (addition item -> trim_material id, same order
rule), and the trimmable-armor set. The same tables drive the gateway's
update_recipes item sets AND the engine's menu, so they always agree.

Run: python3 scripts/gen_smithingdata.py [path-to-server.jar]
"""
import io, json, sys, urllib.request, os, subprocess, zipfile

ITEMS = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
JAR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "smithing_gen.go")

item_id = {i["name"]: i["id"] for i in json.load(urllib.request.urlopen(ITEMS))}
outer = zipfile.ZipFile(JAR)
inner = [n for n in outer.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
z = zipfile.ZipFile(io.BytesIO(outer.read(inner[0]))) if inner else outer

def tag_items(name):
    vals = json.loads(z.read(f"data/minecraft/tags/item/{name}.json"))["values"]
    out = []
    for v in vals:
        v = v["id"] if isinstance(v, dict) else v
        if v.startswith("#"):
            out += tag_items(v.lstrip("#").removeprefix("minecraft:"))
        else:
            out.append(v.removeprefix("minecraft:"))
    return out

# OUR declared trim registry orders are the sorted data-dir entries
# (registries_gen is alphabetical) — recompute the same way here.
def registry_order(reg):
    prefix = f"data/minecraft/{reg}/"
    return sorted(p.removeprefix(prefix).removesuffix(".json")
                  for p in z.namelist() if p.startswith(prefix) and p.endswith(".json"))

pattern_ix = {n: i for i, n in enumerate(registry_order("trim_pattern"))}
material_ix = {n: i for i, n in enumerate(registry_order("trim_material"))}

transform, trim_templates = [], []
for path in sorted(z.namelist()):
    if not (path.startswith("data/minecraft/recipe/") and path.endswith(".json")):
        continue
    r = json.loads(z.read(path))
    if r.get("type") == "minecraft:smithing_transform":
        base = r["base"].removeprefix("minecraft:")
        res = r["result"]["id"].removeprefix("minecraft:")
        if base in item_id and res in item_id:
            transform.append((item_id[base], item_id[res]))
    elif r.get("type") == "minecraft:smithing_trim":
        tmpl = r["template"].removeprefix("minecraft:")
        pat = r["pattern"].removeprefix("minecraft:")
        if tmpl in item_id and pat in pattern_ix:
            trim_templates.append((item_id[tmpl], pattern_ix[pat]))
transform.sort(); trim_templates.sort()

materials = []  # (addition item id, material id) — vanilla item->material map
ITEM_MATERIAL = {"iron_ingot": "iron", "copper_ingot": "copper", "gold_ingot": "gold",
                 "lapis_lazuli": "lapis", "emerald": "emerald", "diamond": "diamond",
                 "netherite_ingot": "netherite", "redstone": "redstone", "quartz": "quartz",
                 "amethyst_shard": "amethyst", "resin_brick": "resin"}
for item, mat in sorted(ITEM_MATERIAL.items()):
    if item in item_id and mat in material_ix:
        materials.append((item_id[item], material_ix[mat]))

trimmable = sorted(item_id[n] for n in tag_items("trimmable_armor") if n in item_id)
upgrade_tmpl = item_id["netherite_upgrade_smithing_template"]

L = [
    "// Code generated by tachyne-world/scripts/gen_smithingdata.py; DO NOT EDIT.",
    "",
    "package protocol",
    "",
    "// SmithingUpgradeTemplate is the netherite upgrade template item.",
    f"const SmithingUpgradeTemplate = {upgrade_tmpl}",
    "",
    "// SmithingTransform maps a transform base item to its upgraded result.",
    "var SmithingTransform = map[int32]int32{",
]
L += [f"\t{a}: {b}," for a, b in transform] + ["}"]
L += ["", "// SmithingTrimTemplate maps a trim template item to its trim_pattern id",
      "// (OUR declared alphabetical registry order, identical on every version).",
      "var SmithingTrimTemplate = map[int32]int32{"]
L += [f"\t{a}: {b}," for a, b in trim_templates] + ["}"]
L += ["", "// SmithingTrimMaterial maps an addition item to its trim_material id.",
      "var SmithingTrimMaterial = map[int32]int32{"]
L += [f"\t{a}: {b}," for a, b in materials] + ["}"]
L += ["", "// SmithingTrimmable lists the trimmable armor items.",
      "var SmithingTrimmable = []int32{" + ", ".join(str(i) for i in trimmable) + "}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(transform)} transforms, {len(trim_templates)} templates, {len(materials)} materials, {len(trimmable)} trimmable")
