#!/usr/bin/env python3
"""Generate tachyne-common/protocol/canonicalnames_gen.go — the canonical ids of
every entity type and item, and every block's default state, by name.

Hand-written tables in tachyne-common that need a particular entity (the
stand-ins for entities an older client lacks, the gateway's per-type
metadata fixes) name it and resolve the id here, so a canonical version
change regenerates this file instead of silently re-pointing every number.

    python3 scripts/gen_canonicalnames.py     # canonical version: canon.py
"""
import os

import canon
import vanillareport

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "tachyne-common", "protocol", "canonicalnames_gen.go")

items = vanillareport.registry(canon.VERSION, "item")
blocks = vanillareport.blocks(canon.VERSION)
ents = vanillareport.registry(canon.VERSION, "entity_type")
attrs = vanillareport.registry(canon.VERSION, "attribute")

# Fluid-holding states (FluidState non-empty: water, lava, every waterlogged
# block, kelp, seagrass), one bit per canonical state id — waterlogged and dry
# states alternate, so ranges would be nearly one per state.
import json
blocks_ext = json.load(open(canon.extract()))["blocks"]
nstates = max(b["maxStateId"] for b in blocks_ext) + 1
fluid_bits = [0] * ((nstates + 63) // 64)
nfluid = 0
for b in blocks_ext:
    for i, f in enumerate(b["fluid"]):
        if f:
            s_ = b["minStateId"] + i
            fluid_bits[s_ // 64] |= 1 << (s_ % 64)
            nfluid += 1

L = ["// Code generated by tachyne-world/scripts/gen_canonicalnames.py; DO NOT EDIT.",
     "",
     "package protocol",
     "",
     "// CanonicalProtocol is the protocol whose clients number content exactly",
     "// as the engine does (%s): for them every id table is the identity." % canon.VERSION,
     "const CanonicalProtocol = %d" % canon.PROTOCOL,
     "",
     "// canonicalEntityIDs is every entity type's canonical (%s, protocol %d) id," % (canon.VERSION, canon.PROTOCOL),
     "// by name without the namespace. Code that needs an entity names it:",
     "// see CanonicalEntity.",
     "var canonicalEntityIDs = map[string]int32{"]
L += ['\t"%s": %d,' % (e["name"], e["id"]) for e in sorted(ents, key=lambda e: e["name"])]
L += ["}",
      "",
      "// canonicalItemIDs is every item's canonical id, by name.",
      "var canonicalItemIDs = map[string]int32{"]
L += ['\t"%s": %d,' % (e["name"], e["id"]) for e in sorted(items, key=lambda e: e["name"])]
L += ["}",
      "",
      "// canonicalBlockStates is every block's canonical DEFAULT state id, by name.",
      "var canonicalBlockStates = map[string]int32{"]
L += ['\t"%s": %d,' % (b["name"], b["defaultState"]) for b in sorted(blocks, key=lambda b: b["name"])]
L += ["}",
      "",
      "// canonicalAttributeIDs is every attribute's canonical registry id, by its",
      "// namespaced name (update_attributes carries these).",
      "var canonicalAttributeIDs = map[string]int32{"]
L += ['\t"minecraft:%s": %d,' % (e["name"], e["id"]) for e in sorted(attrs, key=lambda e: e["name"])]
L += ["}",
      "",
      "// canonicalFluidStates has a bit set for every canonical state that holds",
      "// a fluid (its FluidState is not empty) — water and lava, and every",
      "// waterlogged block, kelp and seagrass: %d of %d states." % (nfluid, nstates),
      "var canonicalFluidStates = [...]uint64{"]
for i in range(0, len(fluid_bits), 4):
    L.append("\t" + ", ".join("%#x" % w for w in fluid_bits[i:i + 4]) + ",")
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
print("wrote %s: %d entity types, %d items, %d blocks" % (os.path.normpath(OUT), len(ents), len(items), len(blocks)))
