#!/usr/bin/env python3
"""Generate internal/server/pushreaction_gen.go — how a piston treats each
block state, and which states carry a block entity.

Both are asked of the running game (scripts/extract):
BlockState.getPistonPushReaction() and BlockState.hasBlockEntity(), the two
facts PistonBaseBlock.isPushable reads. The hand-kept lists this replaces
missed every block that takes its reaction from a shared properties helper —
leaves, buttons, beds, candles, pumpkins and melons were pushed where vanilla
pops them.

PUSH_PULL (the default) is left out: it is a lookup's miss.

    python3 scripts/gen_pushreaction.py     # canonical version: canon.py
"""
import json
import os
import subprocess

import canon

OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "pushreaction_gen.go")
KINDS = {  # extract name -> Go var
    "IMMOVEABLE": "pushImmovableRanges",
    "POPPED": "pushPoppedRanges",
    "PUSH": "pushOnlyRanges",
}

blocks = sorted(json.load(open(canon.extract()))["blocks"], key=lambda b: b["minStateId"])
runs = {k: [] for k in KINDS}
be = []


def add(rs, lo, hi):
    if rs and rs[-1][1] + 1 == lo:
        rs[-1][1] = hi
    else:
        rs.append([lo, hi])


for b in blocks:
    for i, r in enumerate(b["pushReaction"]):
        s = b["minStateId"] + i
        if r in KINDS:
            add(runs[r], s, s)
        elif r not in ("PUSH_PULL", "IGNORE_ENTITY"):
            raise SystemExit(f"{b['name']}: unknown push reaction {r}")
    if b["hasBlockEntity"]:
        add(be, b["minStateId"], b["maxStateId"])

L = ["// Code generated by scripts/gen_pushreaction.py from vanilla block data. DO NOT EDIT.",
     "",
     "package server",
     ""]
for r, goname in KINDS.items():
    L += [f"// {goname}: the states whose piston push reaction is {r} (canonical {canon.VERSION}).",
          f"var {goname} = []stateRange{{"]
    L += ["\t{%d, %d}," % tuple(x) for x in runs[r]]
    L += ["}", ""]
L += [f"// blockEntityRanges: the states that carry a block entity (canonical {canon.VERSION}).",
      "var blockEntityRanges = []stateRange{"]
L += ["\t{%d, %d}," % tuple(x) for x in be]
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {os.path.normpath(OUT)}: " + ", ".join(f"{len(v)} {k}" for k, v in runs.items()) + f", {len(be)} block-entity runs")
