#!/usr/bin/env python3
"""Generate internal/server/smelting_gen.go: cooker recipes + fuel burn times.

Recipes come from the vanilla 1.21.11 server jar's datapack (recipe/*.json) —
four cooker types: minecraft:smelting (furnace), minecraft:blasting (blast
furnace), minecraft:smoking (smoker), minecraft:campfire_cooking (campfire).
Ingredients may be item names or #tags; tags resolve transitively via the
jar's tags/item/*.json. Result counts are always 1; per-recipe cook time is
kept (defaults 200/100/100/600 ticks).

Fuel burn times are vanilla constants (the furnace block entity's fuel map);
the common set is emitted by name so the ids stay generated.

Run: python3 scripts/gen_smelting.py [path-to-server.jar]
(needs network only for the minecraft-data items.json id map)
"""
import io, json, sys, urllib.request, os, subprocess, zipfile

ITEMS = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/items.json"
JAR = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/vanilla/server-1.21.11.jar")
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "smelting_gen.go")

item_id = {i["name"]: i["id"] for i in json.load(urllib.request.urlopen(ITEMS))}

# The bundler jar nests the real server jar.
outer = zipfile.ZipFile(JAR)
inner_name = [n for n in outer.namelist() if n.startswith("META-INF/versions/") and n.endswith(".jar")]
z = zipfile.ZipFile(io.BytesIO(outer.read(inner_name[0]))) if inner_name else outer

recipes, tags = {}, {}
for path in z.namelist():
    if path.startswith("data/minecraft/recipe/") and path.endswith(".json"):
        recipes[path] = json.loads(z.read(path))
    elif path.startswith("data/minecraft/tags/item/") and path.endswith(".json"):
        key = path.removeprefix("data/minecraft/tags/item/").removesuffix(".json")
        tags[key] = json.loads(z.read(path))

tag_cache = {}


def resolve_tag(name, depth=0):
    """#minecraft:logs_that_burn -> flat list of item names."""
    if depth > 8:
        return []
    key = name.lstrip("#").removeprefix("minecraft:")
    if key in tag_cache:
        return tag_cache[key]
    if key not in tags:
        return []
    out = []
    for v in tags[key]["values"]:
        v = v["id"] if isinstance(v, dict) else v
        if v.startswith("#"):
            out += resolve_tag(v, depth + 1)
        else:
            out.append(v.removeprefix("minecraft:"))
    tag_cache[key] = out
    return out


COOKERS = [  # (recipe type, go map name, default cook ticks, doc)
    ("minecraft:smelting", "smeltResult", 200, "furnace"),
    ("minecraft:blasting", "blastResult", 100, "blast furnace"),
    ("minecraft:smoking", "smokeResult", 100, "smoker"),
    ("minecraft:campfire_cooking", "campfireResult", 600, "campfire"),
]
tables = {t: [] for t, _, _, _ in COOKERS}
for path, r in sorted(recipes.items()):
    for rtype, _, default, _ in COOKERS:
        if r.get("type") != rtype:
            continue
        result = r["result"]["id"].removeprefix("minecraft:")
        if result not in item_id:
            continue
        cook = r.get("cookingtime", default)
        ing = r["ingredient"]
        ings = [ing] if isinstance(ing, str) else ing
        names = []
        for i in ings:
            if i.startswith("#"):
                names += resolve_tag(i)
            else:
                names.append(i.removeprefix("minecraft:"))
        for n in names:
            if n in item_id:
                tables[rtype].append((item_id[n], item_id[result], cook))
for rows in tables.values():
    rows.sort()

# Vanilla fuel burn times (ticks), by item name family.
FUELS = {"coal": 1600, "charcoal": 1600, "coal_block": 16000, "blaze_rod": 2400,
         "lava_bucket": 20000, "stick": 100, "crafting_table": 300, "bamboo": 50,
         "dried_kelp_block": 4000}
fuel_rows = []
for name, iid in item_id.items():
    if name in FUELS:
        fuel_rows.append((iid, FUELS[name]))
    elif name.endswith("_planks") or name.endswith("_log") or name.endswith("_wood") or name.endswith("_sapling"):
        fuel_rows.append((iid, 300 if not name.endswith("_sapling") else 100))
fuel_rows.sort()

L = [
    "// Code generated by scripts/gen_smelting.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// cookEntry is one cooker recipe: output item + cook time in ticks.",
    "type cookEntry struct {",
    "\tOut  int32",
    "\tCook int",
    "}",
]
for rtype, goname, _, doc in COOKERS:
    L += [
        "",
        f"// {goname} maps a {doc} input item to its cooked output + cook ticks.",
        f"var {goname} = map[int32]cookEntry{{",
    ]
    for inp, out, cook in tables[rtype]:
        L.append(f"\t{inp}: {{{out}, {cook}}},")
    L.append("}")
L += [
    "",
    "// fuelTicks maps a fuel item to how long one of it burns (ticks).",
    "var fuelTicks = map[int32]int{",
]
for iid, t in fuel_rows:
    L.append(f"\t{iid}: {t},")
L += ["}", ""]
with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: " + ", ".join(f"{len(tables[t])} {d}" for t, _, _, d in COOKERS) + f", {len(fuel_rows)} fuels")
