#!/usr/bin/env python3
"""Generate internal/server/recipes_gen.go from minecraft-data recipes.json.

recipes.json (1.21.5) is a dict: result-item-id -> list of recipes, each either
  shaped:    {"inShape": [[itemId|null, ...], ...], "result": {"id", "count"}}
  shapeless: {"ingredients": [itemId, ...],         "result": {"id", "count"}}
All ingredient references are plain item ids (wood variants are separate recipes),
so matching is exact-id — no tag resolution needed.

We emit two tables the server scans on every crafting-grid change:
  - shapedRecipes:    W,H + row-major cells (0 = empty) + result
  - shapelessRecipes: sorted ingredient ids + result
inShape rows can be ragged (trailing empties omitted); we pad to the widest row.

Run outside the sandbox (needs network):  python3 scripts/gen_recipes.py
"""
import json, urllib.request, os, subprocess

URL = "https://raw.githubusercontent.com/PrismarineJS/minecraft-data/master/data/pc/1.21.11/recipes.json"
OUT = os.path.join(os.path.dirname(__file__), "..", "internal", "server", "recipes_gen.go")

recipes = json.load(urllib.request.urlopen(URL))

shaped = []     # (h, w, cells row-major, result, count)
shapeless = []  # (sorted ingredient ids, result, count)
for _, recs in recipes.items():
    for r in recs:
        res, cnt = r["result"]["id"], r["result"]["count"]
        if res <= 0 or cnt <= 0:
            continue  # data quirk: a recipe whose result is air/empty
        if "inShape" in r:
            rows = r["inShape"]
            h = len(rows)
            w = max(len(row) for row in rows)
            cells = []
            for row in rows:
                padded = list(row) + [None] * (w - len(row))
                cells += [c if c is not None else 0 for c in padded]
            shaped.append((h, w, cells, res, cnt))
        else:
            shapeless.append((sorted(r["ingredients"]), res, cnt))

shaped.sort(key=lambda s: (s[3], s[0], s[1], s[2]))
shapeless.sort(key=lambda s: (s[1], s[0]))

L = [
    "// Code generated by scripts/gen_recipes.py; DO NOT EDIT.",
    "",
    "package server",
    "",
    "// shapedRecipes: crafting patterns as WxH row-major cells of item ids (0 =",
    "// empty). A grid matches when its non-empty bounding box equals the pattern",
    "// (or its horizontal mirror). Wood/material variants are separate recipes.",
    "var shapedRecipes = []struct {",
    "\tW, H   uint8",
    "\tCells  []int32",
    "\tResult int32",
    "\tCount  uint8",
    "}{",
]
for h, w, cells, res, cnt in shaped:
    L.append(f"\t{{{w}, {h}, []int32{{{', '.join(map(str, cells))}}}, {res}, {cnt}}},")
L += [
    "}",
    "",
    "// shapelessRecipes: sorted ingredient item-ids -> result. A grid matches when",
    "// its non-empty cells form exactly this multiset.",
    "var shapelessRecipes = []struct {",
    "\tIngredients []int32 // sorted",
    "\tResult      int32",
    "\tCount       uint8",
    "}{",
]
for ings, res, cnt in shapeless:
    L.append(f"\t{{[]int32{{{', '.join(map(str, ings))}}}, {res}, {cnt}}},")
L += ["}", ""]

with open(OUT, "w") as f:
    f.write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print(f"wrote {OUT}: {len(shaped)} shaped + {len(shapeless)} shapeless recipes")
