#!/usr/bin/env python3
"""Generate internal/server/recipebook_legacy_gen.go: what the OLD recipe book
ids meant.

Until 2026-09-22 the recipe book stored a player's recipes as indices into a
table built from a dataset that pre-expanded tag ingredients (twelve crafting
tables, one per wood). The table now follows vanilla — one crafting table whose
cells accept any planks — and the book stores recipe NAMES, as vanilla's does.
Saves written before that still hold the old indices; this maps each one to the
recipe that replaced it, so nobody's book is lost in the change.

It reads the old table out of git history and matches every old entry to the
new recipe that accepts it (same result and count, and every item in a cell
the new cell's set accepts, in either orientation). It refuses to write if any
old entry has no match, or more than one.

The output describes a table that no longer exists, so it is regenerated only
from that same commit:

    git show 095c257:internal/server/recipes_gen.go > /tmp/old.go
    python3 scripts/gen_recipebook_legacy.py /tmp/old.go
"""
import itertools
import os
import re
import subprocess
import sys

OLD = sys.argv[1]
HERE = os.path.dirname(os.path.abspath(__file__))
NEW = os.path.join(HERE, "..", "internal", "server", "recipes_gen.go")
OUT = os.path.join(HERE, "..", "internal", "server", "recipebook_legacy_gen.go")


def ints(s):
    return [int(x) for x in s.split(",") if x.strip()]


old_src, new_src = open(OLD).read(), open(NEW).read()
ob = old_src[old_src.index("var shapedRecipes"):old_src.index("var shapelessRecipes")]
ol = old_src[old_src.index("var shapelessRecipes"):]
old_shaped = [(int(w), int(h), ints(c), int(r), int(n))
              for w, h, c, r, n in re.findall(r'\{(\d+), (\d+), \[\]int32\{([^}]*)\}, (\d+), (\d+)\}', ob)]
old_less = [(ints(c), int(r), int(n)) for c, r, n in re.findall(r'\{\[\]int32\{([^}]*)\}, (\d+), (\d+)\}', ol)]

sb = new_src[new_src.index("var ingredientSets"):new_src.index("var shapedRecipes")]
sets = [set(ints(s)) for s in re.findall(r'\{([^{}]*)\},', sb)]
nb = new_src[new_src.index("var shapedRecipes"):new_src.index("var shapelessRecipes")]
nl = new_src[new_src.index("var shapelessRecipes"):]
new_shaped = [(nm, int(w), int(h), ints(c), int(r), int(n))
              for nm, w, h, c, r, n in re.findall(r'\{"([^"]+)", (\d+), (\d+), \[\]uint16\{([^}]*)\}, (\d+), (\d+)\}', nb)]
new_less = [(nm, ints(c), int(r), int(n))
            for nm, c, r, n in re.findall(r'\{"([^"]+)", \[\]uint16\{([^}]*)\}, (\d+), (\d+)(?:, (?:true|false))?\}', nl)]


def shaped_accepts(cells, new_cells, w):
    for mirror in (False, True):
        if all((item == 0) == (not sets[new_cells[i // w * w + (w - 1 - i % w if mirror else i % w)]])
               and (item == 0 or item in sets[new_cells[i // w * w + (w - 1 - i % w if mirror else i % w)]])
               for i, item in enumerate(cells)):
            return True
    return False


def shapeless_accepts(items, ings):
    return len(items) == len(ings) and any(
        all(it in sets[i] for it, i in zip(items, p)) for p in itertools.permutations(ings))


names, problems = [], []
for i, (w, h, cells, r, n) in enumerate(old_shaped):
    hits = [nm for nm, nw, nh, nc, nr, nn in new_shaped if (nw, nh, nr, nn) == (w, h, r, n) and shaped_accepts(cells, nc, w)]
    (names.append(hits[0]) if len(hits) == 1 else problems.append(("shaped", i, hits)))
for i, (items, r, n) in enumerate(old_less):
    hits = [nm for nm, ni, nr, nn in new_less if (nr, nn) == (r, n) and shapeless_accepts(items, ni)]
    (names.append(hits[0]) if len(hits) == 1 else problems.append(("shapeless", i, hits)))
if problems:
    sys.exit("refusing to write, %d old entries without exactly one match: %s" % (len(problems), problems[:5]))

L = [
    "// Code generated by scripts/gen_recipebook_legacy.py from the recipe table as",
    "// it stood at commit 095c257; DO NOT EDIT, and do not regenerate against a",
    "// later table — see the script.",
    "",
    "package server",
    "",
    "// legacyCraftRecipeCount is how many crafting recipes the old index-based",
    "// book numbered. Its cooking entries followed from this id on, in the same",
    "// order cookBookRecipes still builds them.",
    "const legacyCraftRecipeCount = %d" % len(names),
    "",
    "// legacyRecipeNames[i] is the recipe the old book's id i referred to.",
    "var legacyRecipeNames = [...]string{",
]
L += ['\t"%s",' % nm for nm in names]
L += ["}", ""]
open(OUT, "w").write("\n".join(L))
subprocess.run(["gofmt", "-w", OUT], check=True)
print("%d old ids -> %d recipe names -> %s" % (len(names), len(set(names)), os.path.normpath(OUT)))
